"use strict";(()=>{const d=[["nfe","NF-e rejeitada"],["atendimento","Reclamação urgente"],["ruptura","Produto sem estoque"],["venc","Contas que vencem hoje"],["venc_amanha","Contas que vencem amanhã"],["repasse","Repasse atrasado ou abaixo do previsto"],["aprov","Pagamento para aprovar"],["semanal","Relatório semanal da diretoria"]],c=o=>(d.find(t=>t[0]===o)||[o,o])[1],e={carregado:!1,carregando:!1,destinos:[],envios:[],canais:null,erro:"",rel:null,relCarregando:!1},l=()=>window.Cloud?.role==="owner",v=o=>typeof money=="function"?money(o):String(o);async function i(o){if(!(e.carregando||!o&&e.carregado||!window.Cloud?.ws)){e.carregando=!0,e.erro="";try{const t=Cloud.client,s=Cloud.ws,[a,r,n]=await Promise.all([t.from("alertas_destinos").select("*").eq("workspace_id",s).order("created_at"),t.from("alertas_envios").select("*").eq("workspace_id",s).order("enviado_em",{ascending:!1}).limit(30),Integrations.callFn("integrations",{action:"alertas_canais"}).catch(()=>null)]);if(a.error)throw a.error;e.destinos=a.data||[],e.envios=r.data||[],e.canais=n,e.carregado=!0}catch(t){e.erro=t.message||String(t)}finally{e.carregando=!1,page==="alertasrel"&&render()}}}function p(){if(!window.Cloud?.ws)return'<div class="notice">Conecte a nuvem para enviar alertas por e-mail e WhatsApp.</div>';if(!e.carregado)return i(),'<div class="empty">Carregando…</div>';const o=e.canais||{},t=(a,r)=>`<span class="badge ${a?"ok":"warn"}">${r}: ${a?"conectado":"falta conectar"}</span>`,s=!o.email||!o.whatsapp;return`${e.erro?`<div class="notice warnbox">${esc(e.erro)}</div>`:""}
 <div class="notice"><strong>Os mesmos avisos do celular, também por e-mail e WhatsApp.</strong> Cada pessoa escolhe o que quer receber. O relatório da diretoria chega toda segunda de manhã, com a planilha da semana anexa. <span class="row wrap" style="gap:6px;margin-top:8px">${t(o.email,"E-mail")}${t(o.whatsapp,"WhatsApp")}</span>
 ${s?`<p class="caption" style="margin:8px 0 0">${o.email?"":"E-mail: crie a conta no Resend, verifique o domínio jaarvis.com.br e grave a chave RESEND_API_KEY no servidor. "}${o.whatsapp?"":"WhatsApp: na Meta (WhatsApp Business), aprove um modelo de mensagem e grave WHATSAPP_TOKEN, WHATSAPP_PHONE_ID e WHATSAPP_TEMPLATE. "}Até lá os destinos ficam cadastrados e nada é enviado.</p>`:""}</div>
 <div class="grid two" style="align-items:start;margin-top:16px">
  <div class="tablebox"><div class="tabletop"><div><h2>Quem recebe</h2><p class="caption">${e.destinos.length} destino(s)</p></div></div>
   ${e.destinos.length?`<div class="tablewrap"><table><thead><tr><th>Destino</th><th>Avisos</th><th></th></tr></thead><tbody>${e.destinos.map(a=>`<tr><td><strong>${esc(a.nome||a.destino)}</strong><br><span class="caption">${a.canal==="email"?"E-mail":"WhatsApp"} · ${esc(a.destino)}${a.ativo?"":" · pausado"}</span></td>
    <td class="caption">${(a.tipos||[]).map(c).map(esc).join(" · ")||"nenhum"}</td>
    <td style="white-space:nowrap">${l()?`<button class="small" data-ar-teste="${esc(a.id)}">Testar</button> <button class="small" data-ar-pausar="${esc(a.id)}">${a.ativo?"Pausar":"Retomar"}</button> <button class="small quiet" data-ar-remover="${esc(a.id)}" aria-label="Remover ${esc(a.destino)}">Remover</button>`:""}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">Ninguém cadastrado ainda.</div>'}
  </div>
  ${l()?`<form class="formcard" id="arNovo" style="display:grid;gap:10px"><h2 style="margin:0">Novo destino</h2>
   <div class="row wrap" style="gap:10px"><label style="flex:1;min-width:140px">Canal<select name="canal"><option value="email">E-mail</option><option value="whatsapp">WhatsApp</option></select></label>
    <label style="flex:2;min-width:200px">E-mail ou celular com DDD<input name="destino" required placeholder="diretoria@empresa.com.br ou (47) 99999-1234"></label></div>
   <label>Nome (opcional)<input name="nome" placeholder="Ex.: Diretoria"></label>
   <fieldset style="border:1px solid var(--line);border-radius:10px;padding:10px 12px;display:grid;gap:6px"><legend class="caption" style="padding:0 4px">Avisos</legend>${d.map(([a,r])=>`<label class="row" style="gap:8px;font-weight:400"><input type="checkbox" name="tipos" value="${a}" checked style="width:auto"> ${r}</label>`).join("")}</fieldset>
   <div class="row" style="justify-content:flex-end"><button class="primary">Cadastrar</button></div></form>`:'<div class="notice">Só o dono do workspace cadastra destinos.</div>'}
 </div>
 <div class="tablebox" style="margin-top:16px"><div class="tabletop"><div><h2>Relatório semanal da diretoria</h2><p class="caption">Semana anterior (segunda a domingo): vendas e tarifas por canal, recebido, repasses a receber e atrasados, contas, caixa, atendimento e ruptura.</p></div>
  <div class="row" style="gap:8px"><button class="small" data-ar-prever>${e.relCarregando?"Montando…":"Ver o relatório"}</button>${e.rel?'<button class="small" data-ar-excel>Baixar Excel</button>':""}${l()?'<button class="small primary" data-ar-enviar>Enviar agora</button>':""}</div></div>
  ${e.rel?`<iframe title="Prévia do relatório semanal" sandbox="" srcdoc="${esc(e.rel.html)}" style="width:100%;height:720px;border:0;border-radius:8px;background:#fff"></iframe>`:'<div class="empty">Clique em "Ver o relatório" para montar a prévia da semana passada.</div>'}
 </div>
 <div class="tablebox" style="margin-top:16px"><div class="tabletop"><h2>Últimos envios</h2></div>
  ${e.envios.length?`<div class="tablewrap"><table><thead><tr><th>Quando</th><th>Destino</th><th>Aviso</th><th>Situação</th></tr></thead><tbody>${e.envios.map(a=>`<tr><td>${new Date(a.enviado_em).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}</td><td>${a.canal==="email"?"E-mail":"WhatsApp"} · ${esc(a.destino)}</td><td>${esc(a.assunto||c(a.tipo))}</td><td><span class="badge ${a.status==="enviado"?"ok":a.status==="falhou"?"bad":"warn"}">${a.status==="enviado"?"Enviado":a.status==="falhou"?"Falhou":"Canal não conectado"}</span>${a.erro?`<br><span class="caption">${esc(a.erro)}</span>`:""}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">Nenhum envio ainda.</div>'}
 </div>`}async function m(o){const t=new FormData(o),s=t.get("canal"),a=String(t.get("destino")||"").trim(),r=t.getAll("tipos");if(s==="email"&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(a))return toast("Informe um e-mail válido.");if(s==="whatsapp"&&a.replace(/\D/g,"").length<10)return toast("Informe o celular com DDD.");const{error:n}=await Cloud.client.from("alertas_destinos").insert({workspace_id:Cloud.ws,canal:s,destino:s==="email"?a.toLowerCase():a,nome:String(t.get("nome")||"").trim()||null,tipos:r});if(n)return toast(/duplicate|unique/i.test(n.message)?"Esse destino já está cadastrado.":n.message);toast("Destino cadastrado."),await i(!0)}function u(){if(!e.rel)return;const o=Uint8Array.from(atob(e.rel.xlsx),a=>a.charCodeAt(0)),t=URL.createObjectURL(new Blob([o],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})),s=document.createElement("a");s.href=t,s.download=e.rel.arquivo||"Jarvis - Resumo da semana.xlsx",document.body.appendChild(s),s.click(),s.remove(),setTimeout(()=>URL.revokeObjectURL(t),2e3)}document.addEventListener("submit",async o=>{if(o.target.id!=="arNovo")return;o.preventDefault();const t=o.target.querySelector("button");t.disabled=!0;try{await m(o.target)}finally{t.disabled=!1}}),document.addEventListener("click",async o=>{const t=o.target.closest("[data-ar-teste],[data-ar-pausar],[data-ar-remover],[data-ar-prever],[data-ar-excel],[data-ar-enviar]");if(t){o.preventDefault(),t.disabled=!0;try{const s=t.dataset;if(s.arTeste){const a=await Integrations.callFn("integrations",{action:"alertas_teste",destino:s.arTeste});toast(a.enviados?"Teste enviado.":a.sem_canal?"Canal ainda não conectado no servidor: o teste ficou registrado, nada foi enviado.":"O teste falhou: veja em Últimos envios."),await i(!0)}else if(s.arPausar){const a=e.destinos.find(n=>n.id===s.arPausar),{error:r}=await Cloud.client.from("alertas_destinos").update({ativo:!a.ativo}).eq("id",a.id);if(r)throw r;await i(!0)}else if(s.arRemover){if(t.dataset.confirmar!=="1"){t.dataset.confirmar="1",t.textContent="Confirmar remoção",t.disabled=!1;return}const{error:a}=await Cloud.client.from("alertas_destinos").delete().eq("id",s.arRemover);if(a)throw a;toast("Destino removido."),await i(!0)}else if(s.arPrever!==void 0){e.relCarregando=!0,render();try{e.rel=await Integrations.callFn("integrations",{action:"relatorio_semanal"})}finally{e.relCarregando=!1}render()}else if(s.arExcel!==void 0)u();else if(s.arEnviar!==void 0){const a=await Integrations.callFn("integrations",{action:"relatorio_semanal_enviar"});toast(a.enviados?`Relatório enviado para ${a.enviados} destino(s).`:a.sem_canal?"Canal ainda não conectado: nada foi enviado.":"Ninguém escolheu receber o relatório semanal."),await i(!0)}}catch(s){toast(s.message||String(s))}finally{t.disabled=!1}}}),addPage("alertasrel","bell","Alertas e relatórios",p,"Avisos por e-mail e WhatsApp e o relatório semanal da diretoria, com a planilha da semana.","",()=>{}),window.AlertasRel={carregar:i}})();
