"use strict";(()=>{Object.assign(paths,{bug:"M8 9a4 4 0 0 1 8 0v5a4 4 0 0 1-8 0z M12 9v9 M4 11h4 M16 11h4 M5 17l3-2 M19 17l-3-2 M5 5l3 3 M19 5l-3 3"});const e={lista:null,carregando:!1,erro:"",filtro:"abertos",ws:null},t=r=>r?new Date(r).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"—",c=()=>window.Cloud?.role==="owner";async function n(){if(!(!window.Cloud?.ws||e.carregando)){e.carregando=!0,e.ws=Cloud.ws;try{const{data:r,error:s}=await Cloud.client.from("erros_sistema").select("*").eq("workspace_id",Cloud.ws).order("ultimo_em",{ascending:!1}).limit(300);if(s)throw s;e.lista=r||[],e.erro=""}catch(r){e.erro=r.message||String(r),e.lista=e.lista||[]}finally{e.carregando=!1}page==="erros"&&!document.querySelector(".modalback")&&render()}}function u(){if(!window.Cloud?.ws)return'<div class="empty">Entre no portal para ver a central de erros.</div>';if(!c())return'<div class="notice">Só o administrador da empresa vê a central de erros.</div>';if(!e.lista||e.ws!==Cloud.ws)return n(),'<div class="empty">Carregando…</div>';const r=e.lista.filter(a=>!a.resolvido_em),s=Date.now()-7*864e5,o=r.filter(a=>new Date(a.ultimo_em)>s),i=new Set(r.flatMap(a=>a.usuarios||[])),d=e.filtro==="abertos"?r:e.lista.filter(a=>a.resolvido_em);return`<div class="notice">Toda falha que acontece na tela de alguém da equipe, ou numa função do servidor, chega aqui sozinha: qual erro, em que tela, quantas vezes e com quem. O suporte usa esta lista para corrigir antes de alguém precisar reclamar.</div>
 ${e.erro?`<div class="notice warnbox">${esc(e.erro)}</div>`:""}
 <div class="grid kpis4"><div class="card kpi"><span class="kpil">Erros em aberto</span><span class="kpiv ${r.length?"gold":""}">${r.length}</span><span class="kpis">${r.filter(a=>a.origem==="servidor").length} no servidor · ${r.filter(a=>a.origem!=="servidor").length} no navegador</span></div>
  <div class="card kpi"><span class="kpil">Últimos 7 dias</span><span class="kpiv">${o.length}</span><span class="kpis">${o.reduce((a,l)=>a+(l.ocorrencias||0),0)} ocorrência(s) somadas</span></div>
  <div class="card kpi"><span class="kpil">Pessoas afetadas</span><span class="kpiv">${i.size}</span><span class="kpis">nos erros em aberto</span></div>
  <div class="card kpi"><span class="kpil">Resolvidos</span><span class="kpiv">${e.lista.length-r.length}</span><span class="kpis">arquivados</span></div></div>
 <div class="crmbar"><div class="segtabs">${[["abertos","Em aberto"],["resolvidos","Resolvidos"]].map(([a,l])=>`<button class="${e.filtro===a?"active":""}" data-ce-filtro="${a}">${l}</button>`).join("")}</div><button class="small" data-ce="atualizar">${icon("refresh")} Atualizar</button></div>
 <div class="tablebox"><div class="tablewrap"><table><thead><tr><th>Erro</th><th>Onde</th><th class="num">Vezes</th><th>Quem</th><th>Primeira · última</th><th>Versão</th><th></th></tr></thead><tbody>
 ${d.map(a=>`<tr class="clickrow" data-ce-abrir="${a.id}"><td><strong>${esc(String(a.mensagem).slice(0,140))}</strong><br><span class="caption mono">${esc(a.assinatura.split(" @ ")[1]||"")}</span></td>
  <td><span class="badge ${a.origem==="servidor"?"purple":"info"}">${a.origem==="servidor"?"Servidor":"Navegador"}</span><br><span class="caption">${esc(a.pagina||"—")}</span></td><td class="num"><strong>${a.ocorrencias}</strong></td>
  <td class="caption">${esc((a.usuarios||[]).map(l=>String(l).split("@")[0]).slice(0,3).join(", ")||"—")}${(a.usuarios||[]).length>3?` +${a.usuarios.length-3}`:""}</td><td class="caption">${t(a.primeiro_em)}<br>${t(a.ultimo_em)}</td><td class="caption mono">${esc(a.versao||"—")}</td>
  <td>${a.resolvido_em?`<span class="caption">resolvido ${t(a.resolvido_em)}</span>`:`<button class="small" data-ce-resolver="${a.id}">${icon("check")} Resolvido</button>`}</td></tr>`).join("")||`<tr><td colspan="7" class="empty">${e.filtro==="abertos"?"Nenhum erro em aberto. ✓":"Nada resolvido ainda."}</td></tr>`}
 </tbody></table></div></div>`}function v(r){const s=e.lista.find(o=>String(o.id)===String(r));s&&modal("Detalhe do erro",`<p><strong>${esc(s.mensagem)}</strong></p><p class="caption">${s.origem==="servidor"?"Função do servidor":"Navegador"} · tela ${esc(s.pagina||"—")} · ${s.ocorrencias} vez(es) · versão ${esc(s.versao||"—")}</p>
 <div class="grid two"><div><small class="caption">Primeira vez</small><br>${t(s.primeiro_em)}</div><div><small class="caption">Última vez</small><br>${t(s.ultimo_em)} · ${esc(s.usuario||"")}</div></div>
 ${s.url?`<p class="caption">Endereço: ${esc(s.url)}</p>`:""}${s.navegador?`<p class="caption">Navegador: ${esc(s.navegador)}</p>`:""}
 <label>Rastro técnico (para o suporte)</label><pre style="max-height:260px;overflow:auto;white-space:pre-wrap;font-size:12px;background:var(--panel2,rgba(127,127,127,.08));padding:10px;border-radius:8px">${esc(s.pilha||"—")}</pre>
 <div class="modalfoot"><button data-action="close">Fechar</button>${s.resolvido_em?"":`<button class="primary" data-ce-resolver="${s.id}">${icon("check")} Marcar como resolvido</button>`}</div>`)}document.addEventListener("click",async r=>{const s=r.target.closest("[data-ce],[data-ce-filtro],[data-ce-abrir],[data-ce-resolver]");if(!s)return;const o=s.dataset;if(o.ceResolver){r.stopPropagation();const i=e.lista.find(a=>String(a.id)===o.ceResolver);if(!i)return;const{error:d}=await Cloud.client.from("erros_sistema").update({resolvido_em:new Date().toISOString(),resolvido_por:Cloud.session?.user?.email||""}).eq("id",i.id);if(d)return toast(d.message);i.resolvido_em=new Date().toISOString(),document.querySelector(".modalback")&&closeModal(),toast("Erro marcado como resolvido. Se acontecer de novo, ele volta para a lista."),render();return}if(o.ceFiltro){e.filtro=o.ceFiltro,render();return}if(o.ce==="atualizar"){await n();return}o.ceAbrir&&v(o.ceAbrir)}),addPage("erros","bug","Central de erros",u,"Falhas vistas no navegador da equipe e no servidor, com quantas vezes, quem e onde — para corrigir antes da reclamação.","",()=>{}),window.CentralErros={abertos:()=>(e.lista||[]).filter(r=>!r.resolvido_em).length,carregar:n};let p=null;setInterval(()=>{window.Cloud?.ws&&Cloud.ws!==p&&c()&&(p=Cloud.ws,n())},5e3)})();
