(()=>{const $=e=>(e?.innerText||"").replace(/ /g," ").trim();function u(){const e=document.querySelector(".pagehead h1");if(!e)return document.title;const t=e.cloneNode(!0);return t.querySelectorAll("button").forEach(o=>o.remove()),t.textContent.trim()||"Tela"}const E=()=>window.Cloud?.wsName||"",A=["janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"],f=()=>{try{const e=/^(\d{4})-(\d{2})$/.exec(typeof month=="string"?month:"");return e?A[+e[2]-1]+" de "+e[1]:""}catch{return""}},B=e=>["Jarvis",u(),f()].filter(Boolean).join(" - ").replace(/[\\/:*?"<>|]+/g,"-")+"."+e,v=e=>Number(e.replace(/\./g,"").replace(",","."));function g(e){let t=e.replace(/\s+/g," ").trim().replace(/[−–—]/g,"-");if(!t||t==="-")return null;const o=t.match(/^\((.+)\)$/);if(o){const n=g(o[1]);if(n&&n.t==="n")return{...n,v:-Math.abs(n.v)}}let a=t.match(/^(-)?\s?R\$\s?(-)?\s?([\d.]+(?:,\d+)?)$/);if(a)return{t:"n",v:v(a[3])*(a[1]||a[2]?-1:1),z:'"R$" #,##0.00;-"R$" #,##0.00'};if(a=t.match(/^([+-]?[\d.]*\d(?:,(\d+))?)\s?%$/),a){const n=(a[2]||"").length;return{t:"n",v:v(a[1].replace("+",""))/100,z:n?"0."+"0".repeat(n)+"%":"0%"}}if(a=t.match(/^(\d{2})\/(\d{2})\/(\d{4})$/),a){const n=new Date(Date.UTC(+a[3],+a[2]-1,+a[1]));if(!isNaN(n))return{t:"d",v:n,z:"dd/mm/yyyy"}}return/^-?(?:\d{1,3}(?:\.\d{3})+|\d+)(?:,\d+)?$/.test(t)&&!/^-?0\d/.test(t)&&!/^\d{6,}$/.test(t)&&t.replace(/\D/g,"").length<=15?{t:"n",v:v(t),z:t.includes(",")?"#,##0.00":"#,##0"}:{t:"s",v:t}}function C(e){const t=e.innerText.replace(/ /g," ").trim();if(!t)return null;const o=g(t);if(o&&o.t!=="s")return o;const a=t.split(`
`).map(n=>n.trim()).filter(Boolean);if(a.length>1){const n=g(a[0]);if(n&&n.t!=="s")return n}return{t:"s",v:a.join(" · ")}}function h(e){return!!(e.offsetParent||e.getClientRects().length)}function D(e,t,o){const a=document.getElementById("view")||document.body,n=".tablebox,.card,.relout,section,.caixa,.formcard,.dg-folha,.cap",d=[...a.querySelectorAll("h2,h3,h4")].filter(i=>h(i)&&i.compareDocumentPosition(e)&Node.DOCUMENT_POSITION_FOLLOWING&&(i.closest(n)||a).contains(e)&&i.closest(n)!==null),p=d[d.length-1];return p&&$(p).split(`
`)[0]||(o===1?u():"Tabela "+(t+1))}function k(e,t){const o={},a=[];let n=0,d=0;const p={};for(const s of t.rows){if(!h(s))continue;let r=0;for(const c of s.cells){if(!h(c)&&c.innerText.trim()==="")continue;for(;p[n+","+r];)r++;const l=c.colSpan||1,w=c.rowSpan||1,b=C(c);if(b){const m=e.utils.encode_cell({r:n,c:r});o[m]=b.t==="d"?{t:"d",v:b.v,z:b.z}:b,c.tagName==="TH"&&(o[m].s={font:{bold:!0}})}if(l>1||w>1){a.push({s:{r:n,c:r},e:{r:n+w-1,c:r+l-1}});for(let m=0;m<w;m++)for(let x=0;x<l;x++)(m||x)&&(p[n+m+","+(r+x)]=1)}r+=l,d=Math.max(d,r)}n++}if(!n)return null;o["!ref"]=e.utils.encode_range({s:{r:0,c:0},e:{r:n-1,c:Math.max(0,d-1)}}),a.length&&(o["!merges"]=a);const i=[];for(const s in o){if(s[0]==="!")continue;const{c:r}=e.utils.decode_cell(s),c=o[s],l=String(c.t==="n"?c.v.toFixed(2):c.t==="d"?"00/00/0000":c.v).length;i[r]=Math.min(60,Math.max(i[r]||8,l+2))}return o["!cols"]=i.map(s=>({wch:s||10})),o}function S(e,t){let o=e.replace(/[\[\]:*?\/\\]/g," ").replace(/\s+/g," ").trim().slice(0,31)||"Tabela",a=2,n=o;for(;t.has(o.toLowerCase());){const d=" ("+a+++")";o=n.slice(0,31-d.length)+d}return t.add(o.toLowerCase()),o}function T(){const e=window.XLSX;if(!e){y("A biblioteca do Excel não carregou. Recarregue a página e tente de novo.");return}const t=document.getElementById("view")||document.querySelector(".content")||document.body,o=e.utils.book_new(),a=new Set;o.Props={Title:u(),Author:"Jarvis",Company:E(),CreatedDate:new Date};const n=[...t.querySelectorAll("table")].filter(i=>h(i)&&i.rows.length>1&&!i.closest('[aria-hidden="true"],.mgtip-pop')),d=n.map(i=>{const s=i.style.display;return i.style.display="none",[i,s]}),p=t.innerText.split(`
`).map(i=>i.replace(/ /g," ").trim()).filter(Boolean);if(d.forEach(([i,s])=>i.style.display=s),p.length){const i={},s=[];let r=null;for(const c of p){const l=g(c);l&&l.t!=="s"?r&&!r.v?r.v=l:s.push(r={a:"",v:l}):s.push(r={a:c,v:null})}i.A1={t:"s",v:u()+(f()?" · "+f():"")},s.forEach((c,l)=>{c.a&&(i[e.utils.encode_cell({r:l+1,c:0})]={t:"s",v:c.a}),c.v&&(i[e.utils.encode_cell({r:l+1,c:1})]=c.v)}),i["!ref"]=e.utils.encode_range({s:{r:0,c:0},e:{r:s.length,c:1}}),i["!cols"]=[{wch:70},{wch:18}],e.utils.book_append_sheet(o,i,S("Resumo",a))}if(n.forEach((i,s)=>{const r=k(e,i);r&&e.utils.book_append_sheet(o,r,S(D(i,s,n.length),a))}),!o.SheetNames.length){y("Nada para exportar nesta tela.");return}e.writeFile(o,B("xlsx"),{compression:!0}),y(`Excel gerado: ${o.SheetNames.length} aba(s).`)}function N(){const e=document.getElementById("view");if(!e)return window.print();document.querySelectorAll(".exp-cab").forEach(a=>a.remove());const t=document.createElement("div");t.className="exp-cab",t.innerHTML=`<b>Jarvis · ${L(u())}</b><span>${L([E(),f(),"emitido em "+new Date().toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})].filter(Boolean).join(" · "))}</span>`,e.parentNode.insertBefore(t,e),document.body.classList.add("exp-imprimindo");const o=()=>{document.body.classList.remove("exp-imprimindo"),t.remove(),removeEventListener("afterprint",o)};addEventListener("afterprint",o),setTimeout(()=>window.print(),60)}const L=e=>String(e).replace(/[&<>"]/g,t=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[t]);function y(e){if(typeof toast=="function")toast(e);else{const t=document.getElementById("toast");t&&(t.textContent=e,t.classList.add("show"),setTimeout(()=>t.classList.remove("show"),2600))}}function q(){const e=document.querySelector(".pagehead .pageactions");!e||e.querySelector(".exp-btns")||e.insertAdjacentHTML("afterbegin",'<div class="exp-btns" role="group" aria-label="Exportar esta tela"><button class="small" data-exp="xlsx" title="Baixar as tabelas desta tela em Excel">Excel</button><button class="small" data-exp="pdf" title="Imprimir ou salvar esta tela em PDF">PDF</button></div>')}if(typeof shell=="function"){const e=shell;shell=function(){const t=e.apply(this,arguments);try{q()}catch{}return t}}window.Exportar={celula:g,excel:T,pdf:N},document.addEventListener("click",e=>{const t=e.target.closest("[data-exp]");if(t){e.preventDefault();try{t.dataset.exp==="pdf"?N():T()}catch(o){console.error(o),y("Não foi possível exportar: "+(o.message||o))}}});const I=`.exp-btns{display:flex;gap:6px}.exp-btns button{display:inline-flex;align-items:center;gap:6px}
.exp-cab{display:none}
@media print{
 @page{size:A4 landscape;margin:10mm}
 body:not(.pg-diag){background:#fff!important;color:#111!important}
 body:not(.pg-diag) .side,body:not(.pg-diag) main>header,body:not(.pg-diag) .pagehead,body:not(.pg-diag) .footer,body:not(.pg-diag) .fab,body:not(.pg-diag) #toast,body:not(.pg-diag) #erpdrop,body:not(.pg-diag) .mgtip-pop,body:not(.pg-diag) .rolatopo,body:not(.pg-diag) .guiabtn{display:none!important}
 body:not(.pg-diag) .erp{display:block!important}body:not(.pg-diag) main,body:not(.pg-diag) .content{margin:0!important;padding:0!important;max-width:none!important;width:auto!important;overflow:visible!important}
 body:not(.pg-diag) .tablewrap,body:not(.pg-diag) .tablebox{overflow:visible!important;max-height:none!important;box-shadow:none!important}
 body:not(.pg-diag) table{font-size:10px!important}body:not(.pg-diag) th,body:not(.pg-diag) td{padding:3px 6px!important}
 body:not(.pg-diag) tr,body:not(.pg-diag) .card,body:not(.pg-diag) .kpi{break-inside:avoid}
 /* A impressão geral do sistema esconde todo botão e todo .hero; na exportação, volta o conteúdo feito de botões
    (barras de gráfico, cartões clicáveis) e somem só os controles. */
 body.exp-imprimindo #view button,body.exp-imprimindo #view .hero{display:revert!important}
 body.exp-imprimindo #view :is(button.small,button.primary,button.quiet,.iconbtn,.guiabtn,.segtabs,.toolbar,.crmbar,.filters,.searchin,.rowacts,.fab,[data-exp]),
 body.exp-imprimindo #view input[type=checkbox],body.exp-imprimindo #view input[type=search]{display:none!important}
 body.exp-imprimindo .exp-cab{display:flex!important;justify-content:space-between;align-items:baseline;gap:16px;border-bottom:1px solid #ccc;padding:0 0 6px;margin:0 0 12px;font:12px Inter,"Segoe UI",sans-serif;color:#111}
 body.exp-imprimindo .exp-cab span{color:#555}}`,_=document.createElement("style");_.textContent=I,document.head.appendChild(_)})();
