(()=>{const A=e=>(e?.innerText||"").replace(/ /g," ").trim();function u(){const e=document.querySelector(".pagehead h1");if(!e)return document.title;const t=e.cloneNode(!0);return t.querySelectorAll("button").forEach(o=>o.remove()),t.textContent.trim()||"Tela"}const E=()=>window.Cloud?.wsName||"",B=["janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"],f=()=>{try{const e=/^(\d{4})-(\d{2})$/.exec(typeof month=="string"?month:"");return e?B[+e[2]-1]+" de "+e[1]:""}catch{return""}},C=e=>["Jarvis",u(),f()].filter(Boolean).join(" - ").replace(/[\\/:*?"<>|]+/g,"-")+"."+e,v=e=>Number(e.replace(/\./g,"").replace(",","."));function g(e){let t=e.replace(/\s+/g," ").trim().replace(/[−–—]/g,"-");if(!t||t==="-")return null;const o=t.match(/^\((.+)\)$/);if(o){const n=g(o[1]);if(n&&n.t==="n")return{...n,v:-Math.abs(n.v)}}let a=t.match(/^(-)?\s?R\$\s?(-)?\s?([\d.]+(?:,\d+)?)$/);if(a)return{t:"n",v:v(a[3])*(a[1]||a[2]?-1:1),z:'"R$" #,##0.00;-"R$" #,##0.00'};if(a=t.match(/^([+-]?[\d.]*\d(?:,(\d+))?)\s?%$/),a){const n=(a[2]||"").length;return{t:"n",v:v(a[1].replace("+",""))/100,z:n?"0."+"0".repeat(n)+"%":"0%"}}if(a=t.match(/^(\d{2})\/(\d{2})\/(\d{4})$/),a){const n=new Date(Date.UTC(+a[3],+a[2]-1,+a[1]));if(!isNaN(n))return{t:"d",v:n,z:"dd/mm/yyyy"}}return/^-?(?:\d{1,3}(?:\.\d{3})+|\d+)(?:,\d+)?$/.test(t)&&!/^-?0\d/.test(t)&&!/^\d{6,}$/.test(t)&&t.replace(/\D/g,"").length<=15?{t:"n",v:v(t),z:t.includes(",")?"#,##0.00":"#,##0"}:{t:"s",v:t}}function S(e){const t=e.dataset?.expNum;if(typeof t=="string"&&t!==""&&isFinite(Number(t)))return{t:"n",v:Number(t),z:"0"};const o=e.innerText.replace(/ /g," ").trim();if(!o)return null;const a=g(o);if(a&&a.t!=="s")return a;const n=o.split(`
`).map(l=>l.trim()).filter(Boolean);if(n.length>1){const l=g(n[0]);if(l&&l.t!=="s")return l}return{t:"s",v:n.join(" · ")}}function h(e){return!!(e.offsetParent||e.getClientRects().length)}function D(e,t,o){const a=document.getElementById("view")||document.body,n=".tablebox,.card,.relout,section,.caixa,.formcard,.dg-folha,.cap",l=[...a.querySelectorAll("h2,h3,h4")].filter(i=>h(i)&&i.compareDocumentPosition(e)&Node.DOCUMENT_POSITION_FOLLOWING&&(i.closest(n)||a).contains(e)&&i.closest(n)!==null),p=l[l.length-1];return p&&A(p).split(`
`)[0]||(o===1?u():"Tabela "+(t+1))}function k(e,t){const o={},a=[];let n=0,l=0;const p={};for(const s of t.rows){if(!h(s))continue;let r=0;for(const c of s.cells){if(!h(c)&&c.innerText.trim()==="")continue;for(;p[n+","+r];)r++;const d=c.colSpan||1,w=c.rowSpan||1,b=S(c);if(b){const m=e.utils.encode_cell({r:n,c:r});o[m]=b.t==="d"?{t:"d",v:b.v,z:b.z}:b,c.tagName==="TH"&&(o[m].s={font:{bold:!0}})}if(d>1||w>1){a.push({s:{r:n,c:r},e:{r:n+w-1,c:r+d-1}});for(let m=0;m<w;m++)for(let x=0;x<d;x++)(m||x)&&(p[n+m+","+(r+x)]=1)}r+=d,l=Math.max(l,r)}n++}if(!n)return null;o["!ref"]=e.utils.encode_range({s:{r:0,c:0},e:{r:n-1,c:Math.max(0,l-1)}}),a.length&&(o["!merges"]=a);const i=[];for(const s in o){if(s[0]==="!")continue;const{c:r}=e.utils.decode_cell(s),c=o[s],d=String(c.t==="n"?c.v.toFixed(2):c.t==="d"?"00/00/0000":c.v).length;i[r]=Math.min(60,Math.max(i[r]||8,d+2))}return o["!cols"]=i.map(s=>({wch:s||10})),o}function T(e,t){let o=e.replace(/[\[\]:*?\/\\]/g," ").replace(/\s+/g," ").trim().slice(0,31)||"Tabela",a=2,n=o;for(;t.has(o.toLowerCase());){const l=" ("+a+++")";o=n.slice(0,31-l.length)+l}return t.add(o.toLowerCase()),o}function N(){const e=window.XLSX;if(!e){y("A biblioteca do Excel não carregou. Recarregue a página e tente de novo.");return}const t=document.getElementById("view")||document.querySelector(".content")||document.body,o=e.utils.book_new(),a=new Set;o.Props={Title:u(),Author:"Jarvis",Company:E(),CreatedDate:new Date};const n=[...t.querySelectorAll("table")].filter(i=>h(i)&&i.rows.length>1&&!i.closest('[aria-hidden="true"],.mgtip-pop')),l=n.map(i=>{const s=i.style.display;return i.style.display="none",[i,s]}),p=t.innerText.split(`
`).map(i=>i.replace(/ /g," ").trim()).filter(Boolean);if(l.forEach(([i,s])=>i.style.display=s),p.length){const i={},s=[];let r=null;for(const c of p){const d=g(c);d&&d.t!=="s"?r&&!r.v?r.v=d:s.push(r={a:"",v:d}):s.push(r={a:c,v:null})}i.A1={t:"s",v:u()+(f()?" · "+f():"")},s.forEach((c,d)=>{c.a&&(i[e.utils.encode_cell({r:d+1,c:0})]={t:"s",v:c.a}),c.v&&(i[e.utils.encode_cell({r:d+1,c:1})]=c.v)}),i["!ref"]=e.utils.encode_range({s:{r:0,c:0},e:{r:s.length,c:1}}),i["!cols"]=[{wch:70},{wch:18}],e.utils.book_append_sheet(o,i,T("Resumo",a))}if(n.forEach((i,s)=>{const r=k(e,i);r&&e.utils.book_append_sheet(o,r,T(D(i,s,n.length),a))}),!o.SheetNames.length){y("Nada para exportar nesta tela.");return}e.writeFile(o,C("xlsx"),{compression:!0}),y(`Excel gerado: ${o.SheetNames.length} aba(s).`)}function L(){const e=document.getElementById("view");if(!e)return window.print();document.querySelectorAll(".exp-cab").forEach(a=>a.remove());const t=document.createElement("div");t.className="exp-cab",t.innerHTML=`<b>Jarvis · ${_(u())}</b><span>${_([E(),f(),"emitido em "+new Date().toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})].filter(Boolean).join(" · "))}</span>`,e.parentNode.insertBefore(t,e),document.body.classList.add("exp-imprimindo");const o=()=>{document.body.classList.remove("exp-imprimindo"),t.remove(),removeEventListener("afterprint",o)};addEventListener("afterprint",o),setTimeout(()=>window.print(),60)}const _=e=>String(e).replace(/[&<>"]/g,t=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[t]);function y(e){if(typeof toast=="function")toast(e);else{const t=document.getElementById("toast");t&&(t.textContent=e,t.classList.add("show"),setTimeout(()=>t.classList.remove("show"),2600))}}function q(){const e=document.querySelector(".pagehead .pageactions");!e||e.querySelector(".exp-btns")||e.insertAdjacentHTML("afterbegin",'<div class="exp-btns" role="group" aria-label="Exportar esta tela"><button class="small" data-exp="xlsx" title="Baixar as tabelas desta tela em Excel">Excel</button><button class="small" data-exp="pdf" title="Imprimir ou salvar esta tela em PDF">PDF</button></div>')}if(typeof shell=="function"){const e=shell;shell=function(){const t=e.apply(this,arguments);try{q()}catch{}return t}}window.Exportar={celula:g,celulaTd:S,excel:N,pdf:L},document.addEventListener("click",e=>{const t=e.target.closest("[data-exp]");if(t){e.preventDefault();try{t.dataset.exp==="pdf"?L():N()}catch(o){console.error(o),y("Não foi possível exportar: "+(o.message||o))}}});const z=`.exp-btns{display:flex;gap:6px}.exp-btns button{display:inline-flex;align-items:center;gap:6px}
.exp-cab{display:none}
@media print{
 @page{size:A4 landscape;margin:10mm}
 body:not(.pg-diag){background:#fff!important;color:#111!important}
 body:not(.pg-diag) .side,body:not(.pg-diag) main>header,body:not(.pg-diag) .pagehead,body:not(.pg-diag) .footer,body:not(.pg-diag) .fab,body:not(.pg-diag) #toast,body:not(.pg-diag) #erpdrop,body:not(.pg-diag) .mgtip-pop,body:not(.pg-diag) .rolatopo,body:not(.pg-diag) .guiabtn{display:none!important}
 body:not(.pg-diag) .erp{display:block!important}body:not(.pg-diag) main,body:not(.pg-diag) .content{margin:0!important;padding:0!important;max-width:none!important;width:auto!important;overflow:visible!important}
 body:not(.pg-diag) .tablewrap,body:not(.pg-diag) .tablebox{overflow:visible!important;max-height:none!important;box-shadow:none!important}
 body:not(.pg-diag) table{font-size:10px!important}body:not(.pg-diag) th,body:not(.pg-diag) td{padding:3px 6px!important}
 body:not(.pg-diag) tr,body:not(.pg-diag) .card,body:not(.pg-diag) .kpi{break-inside:avoid}
 /* A impressão geral do sistema esconde todo botão e todo .hero; na exportação, volta o conteúdo feito de botões
    (barras de gráfico, cartões clicáveis) e somem só os controles. */
 body.exp-imprimindo #view button,body.exp-imprimindo #view .hero{display:revert!important}
 body.exp-imprimindo #view :is(button.small,button.primary,button.quiet,.iconbtn,.guiabtn,.segtabs,.toolbar,.crmbar,.filters,.searchin,.rowacts,.fab,[data-exp]),
 body.exp-imprimindo #view input[type=checkbox],body.exp-imprimindo #view input[type=search]{display:none!important}
 body.exp-imprimindo .exp-cab{display:flex!important;justify-content:space-between;align-items:baseline;gap:16px;border-bottom:1px solid #ccc;padding:0 0 6px;margin:0 0 12px;font:12px Inter,"Segoe UI",sans-serif;color:#111}
 body.exp-imprimindo .exp-cab span{color:#555}}`,$=document.createElement("style");$.textContent=z,document.head.appendChild($)})();
