'use strict';
// Fiscal › Emitir NF-e e Notas emitidas. A tela monta a nota (de um pedido de marketplace ou avulsa), calcula os
// impostos no MESMO motor da emissão (CFOP, ICMS, DIFAL/FCP, PIS/COFINS, IBS/CBS), mostra a prévia do DANFE e emite
// pelo Focus NFe no ambiente configurado (homologação = sem valor fiscal). Notas emitidas: consulta, DANFE, XML,
// cancelamento e carta de correção. Emitir, cancelar e corrigir: dono, gestão e financeiro.
(()=>{
Object.assign(paths,{nfe:'M6 3h9l3 3v15H6z M15 3v3h3 M9 11h6 M9 15h6 M9 7h3'});
const EMIT={nome:'WOLFACH E-COMMERCE S.A.',fantasia:'Compra Store',cnpj:'65.193.225/0001-57',cidade:'Timbó',uf:'SC'};
const PAG=[['17','PIX'],['03','Cartão de crédito'],['04','Cartão de débito'],['15','Boleto'],['01','Dinheiro'],['18','Transferência'],['05','Crédito loja'],['90','Sem pagamento'],['99','Outros']];
const PRES=[['2','Internet'],['1','Presencial'],['3','Teleatendimento'],['9','Outros']];
const UFS=['AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO'];
const STATUS={autorizado:['Autorizada','ok'],processando_autorizacao:['Processando','info'],processando:['Processando','info'],erro_autorizacao:['Rejeitada','bad'],erro:['Erro','bad'],cancelado:['Cancelada',''],denegado:['Denegada','bad']};
const dig=s=>String(s||'').replace(/\D/g,'');
const fmtDoc=s=>{const d=dig(s);return d.length===14?d.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,'$1.$2.$3/$4-$5'):d.length===11?d.replace(/^(\d{3})(\d{3})(\d{3})(\d{2})$/,'$1.$2.$3-$4'):s||''};
const num=v=>Number(String(v??'').replace(/\./g,'').replace(',','.'))||0;
const pode=()=>['owner','member','financeiro'].includes(window.Cloud?.role||'owner');
async function fn(action,body){const r=await Cloud.client.functions.invoke('integrations',{body:{workspace_id:Cloud.ws,action,...body}});if(r.error){let msg=r.error.message;try{msg=(await r.error.context.json()).error||msg}catch{}throw Error(msg)}return r.data}
const nf={origem:'avulsa',pedido:'',dest:{doc:'',nome:'',ie:'',email:'',cep:'',logradouro:'',numero:'',complemento:'',bairro:'',municipio:'',uf:'SC'},itens:[],frete:'',desconto:'',pagamento:'17',presenca:'2',obs:'',sim:null,simErro:'',simulando:false,conf:false,prods:null,status:null,notas:null,filtro:'todas',busca:'',amb:''};
async function carregar(){if(!window.Cloud?.ws||nf.carregando)return;nf.carregando=true;
 try{const [p,n,s]=await Promise.all([Cloud.client.from('produtos').select('id,nome,preco,ncm,origem,gtin,imagem,saldo,ignorar').eq('workspace_id',Cloud.ws).limit(5000),Cloud.client.from('notas_fiscais').select('*').eq('workspace_id',Cloud.ws).order('created_at',{ascending:false}).limit(500),fn('fiscal_status',{}).catch(e=>({erro:e.message}))]);
  nf.prods=(p.data||[]).filter(x=>!x.ignorar);nf.notas=n.data||[];nf.status=s}finally{nf.carregando=false}
 if(['nfemitir','nfnotas'].includes(page)&&!document.querySelector('.modalback'))render()}
const amb=()=>nf.status?.config?.ambiente||nf.status?.ambiente||'homologacao';
function dadosNota(){return {itens:nf.itens.map(i=>({sku:i.sku,title:i.nome,qty:num(i.qtd),price:num(i.preco)})),gross:0,nome:nf.dest.nome,doc:dig(nf.dest.doc),ie:dig(nf.dest.ie)||null,email:nf.dest.email||undefined,
 end:{logradouro:nf.dest.logradouro,numero:nf.dest.numero,complemento:nf.dest.complemento,bairro:nf.dest.bairro,municipio:nf.dest.municipio,uf:nf.dest.uf,cep:dig(nf.dest.cep)},frete:num(nf.frete),desconto:num(nf.desconto),presenca:Number(nf.presenca),forma_pagamento:nf.pagamento}}
function totais(p){const it=p?.items||[],s=k=>it.reduce((a,i)=>a+(Number(i[k])||0),0);const prod=s('valor_bruto'),frete=Number(p?.valor_frete)||s('valor_frete'),desc=Number(p?.valor_desconto)||s('valor_desconto');
 return {prod,frete,desc,total:prod+frete-desc,bcIcms:s('icms_base_calculo'),icms:s('icms_valor'),difal:s('icms_valor_uf_destino'),fcp:s('fcp_valor_uf_destino'),pis:s('pis_valor'),cofins:s('cofins_valor'),cbs:s('cbs_valor'),ibs:s('ibs_valor_total')}}

// ─────────── Emitir NF-e ───────────
function emitirView(){if(!nf.prods){carregar();return '<div class="empty">Carregando…</div>'}
 const prod=amb()==='producao',t=nf.sim?totais(nf.sim.payload):null,semNota=db.orders.filter(o=>!o.nf).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,300);
 const f=(k,t,extra='')=>`<div class="field" ${extra}><label>${t}</label><input data-nf-f="${k}" value="${esc(k.split('.').reduce((o,x)=>o?.[x],nf)??'')}"></div>`;
 return `<div class="nfamb ${prod?'prod':''}">${icon(prod?'alert':'nfe')}<div><strong>${prod?'PRODUÇÃO — a nota terá valor fiscal':'Homologação — nota de teste, sem valor fiscal'}</strong><small>${prod?'Confira tudo antes de emitir.':'Serve para validar dados e regras. O destinatário sai como "emitida em homologação".'} Ambiente e regras em Fiscal › Configuração da NF-e.</small></div></div>
 <div class="segtabs" style="margin:0 0 14px">${[['avulsa','Nota avulsa'],['pedido','De um pedido de marketplace']].map(([k,t])=>`<button class="${nf.origem===k?'active':''}" data-nf-origem="${k}">${t}</button>`).join('')}</div>
 <div class="nfgrid"><div class="nfform">
 ${nf.origem==='pedido'?`<section class="card"><h3>Pedido</h3><p class="caption">Destinatário (endereço do Bling), itens, frete e intermediador vêm do pedido.</p>
  <div class="row wrap" style="gap:8px"><input list="nfPeds" data-nf-f="pedido" value="${esc(nf.pedido)}" placeholder="Número do pedido" style="flex:1;min-width:220px"><datalist id="nfPeds">${semNota.map(o=>`<option value="${esc(o.id)}">${esc(o.platform)} · ${new Date(o.date+'T12:00:00').toLocaleDateString('pt-BR')} · ${money(o.gross)}</option>`).join('')}</datalist><button class="small primary" data-nf="simular">${icon('refresh')} Carregar e calcular</button></div>
  ${nf.sim?.origem?`<div class="nfped"><span class="badge info">${esc(nf.sim.origem.canal||'')}</span> Pedido <b>${esc(nf.sim.origem.pedido)}</b> de ${new Date(nf.sim.origem.data+'T12:00:00').toLocaleDateString('pt-BR')} · ${esc(nf.sim.origem.cliente||'')}</div>`:''}</section>`
 :`<section class="card"><div class="cardhead"><h3>Destinatário</h3><button class="small quiet" data-nf="cnpj">${icon('search')} Buscar CNPJ</button></div>
  <div class="formgrid">${f('dest.doc','CPF ou CNPJ *')}${f('dest.nome','Nome / razão social *','style="grid-column:span 2"')}${f('dest.ie','Inscrição estadual')}${f('dest.email','E-mail','style="grid-column:span 2"')}
  <div class="field"><label>CEP *</label><div class="row" style="gap:6px"><input data-nf-f="dest.cep" value="${esc(nf.dest.cep)}"><button class="small quiet" data-nf="cep" title="Buscar endereço pelo CEP">${icon('search')}</button></div></div>
  ${f('dest.logradouro','Rua / logradouro *','style="grid-column:span 2"')}${f('dest.numero','Número')}${f('dest.complemento','Complemento')}${f('dest.bairro','Bairro')}${f('dest.municipio','Município *')}
  <div class="field"><label>UF *</label><select data-nf-f="dest.uf">${UFS.map(u=>`<option ${nf.dest.uf===u?'selected':''}>${u}</option>`).join('')}</select></div></div>
  <p class="caption">CNPJ com inscrição estadual = contribuinte (CFOP de revenda, sem DIFAL). CPF ou CNPJ sem IE = consumidor final.</p></section>
 <section class="card"><div class="cardhead"><h3>Produtos</h3><span class="caption">${nf.itens.length} item(ns)</span></div>
  <div class="row" style="gap:8px;margin-bottom:10px"><input list="nfProds" id="nfBusca" placeholder="Buscar produto por SKU ou nome e pressionar Enter" style="flex:1"><datalist id="nfProds">${nf.prods.map(p=>`<option value="${esc(p.id)}">${esc(p.nome)}${p.ncm?'':' (sem NCM)'}</option>`).join('')}</datalist><button class="small" data-nf="additem">${icon('plus')} Adicionar</button></div>
  <div class="tablewrap"><table class="nfitens"><thead><tr><th>Produto</th><th>NCM</th><th class="num">Qtd.</th><th class="num">Valor unit.</th><th class="num">Total</th><th></th></tr></thead><tbody>
  ${nf.itens.map((i,k)=>`<tr><td><div class="nfprod">${i.imagem?`<img src="${esc(i.imagem)}" alt="">`:''}<span><b>${esc(i.nome)}</b><br><small class="mono">${esc(i.sku)}</small></span></div></td><td class="${i.ncm?'':'red'}">${esc(i.ncm||'sem NCM')}</td><td class="num"><input class="num" data-nf-it="${k}.qtd" value="${esc(i.qtd)}" style="width:64px"></td><td class="num"><input class="num" data-nf-it="${k}.preco" value="${esc(i.preco)}" style="width:96px"></td><td class="num">${money(num(i.qtd)*num(i.preco))}</td><td><button class="small quiet" data-nf-rm="${k}" aria-label="Remover">✕</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Adicione os produtos da nota.</td></tr>'}</tbody></table></div></section>
 <section class="card"><h3>Transporte, pagamento e observações</h3><div class="formgrid">${f('frete','Frete (R$)')}${f('desconto','Desconto (R$)')}
  <div class="field"><label>Forma de pagamento</label><select data-nf-f="pagamento">${PAG.map(([v,t])=>`<option value="${v}" ${nf.pagamento===v?'selected':''}>${t}</option>`).join('')}</select></div>
  <div class="field"><label>Presença do comprador</label><select data-nf-f="presenca">${PRES.map(([v,t])=>`<option value="${v}" ${nf.presenca===v?'selected':''}>${t}</option>`).join('')}</select></div></div>
  <p class="caption">Informações complementares (DIFAL, tributos aproximados e texto padrão) entram sozinhas pelas regras fiscais.</p></section>`}
 </div><div class="nfside"><section class="card nfres"><h3>Resumo da nota</h3>
  ${nf.simulando?'<p class="caption"><span class="spin"></span> Calculando pelo motor fiscal…</p>':nf.simErro?`<div class="notice warnbox">${esc(nf.simErro)}</div>`:!t?'<p class="caption">Preencha e clique em <b>Calcular impostos</b>: o cálculo é o mesmo da emissão.</p>':`
  <div class="nfkv"><span>Produtos</span><b>${money(t.prod)}</b></div>${t.frete?`<div class="nfkv"><span>Frete</span><b>${money(t.frete)}</b></div>`:''}${t.desc?`<div class="nfkv"><span>Desconto</span><b>− ${money(t.desc)}</b></div>`:''}
  <div class="nfkv tot"><span>Total da nota</span><b>${money(t.total)}</b></div>
  <h4>Impostos</h4><div class="nfkv"><span>Base ICMS</span><b>${money(t.bcIcms)}</b></div><div class="nfkv"><span>ICMS</span><b>${money(t.icms)}</b></div>${t.difal?`<div class="nfkv"><span>DIFAL (UF destino)</span><b>${money(t.difal)}</b></div>`:''}${t.fcp?`<div class="nfkv"><span>FCP</span><b>${money(t.fcp)}</b></div>`:''}
  <div class="nfkv"><span>PIS</span><b>${money(t.pis)}</b></div><div class="nfkv"><span>COFINS</span><b>${money(t.cofins)}</b></div><div class="nfkv"><span>CBS / IBS (teste 2026)</span><b>${money(t.cbs+t.ibs)}</b></div>
  <h4>Operação</h4><p class="caption">${esc(nf.sim.payload.natureza_operacao)} · CFOP ${[...new Set(nf.sim.payload.items.map(i=>i.cfop))].join(', ')} · ${nf.sim.payload.local_destino===1?'dentro do estado':'interestadual'} · ${nf.sim.payload.consumidor_final?'consumidor final':'contribuinte'}${nf.sim.payload.indicador_intermediario?' · com intermediador':''}</p>`}
  <div class="nfacoes"><button class="small" data-nf="simular">${icon('refresh')} Calcular impostos</button><button class="small" data-nf="danfe" ${t?'':'disabled'}>${icon('nfe')} Pré-visualizar DANFE</button>
  ${pode()?`<button class="${nf.conf?'danger':'primary'}" data-nf="emitir" ${t?'':'disabled'}>${icon('check')} ${nf.conf?(prod?'Confirmar: emitir COM valor fiscal':'Confirmar emissão de teste'):(prod?'Emitir NF-e':'Emitir nota de teste')}</button>`:'<p class="caption">Seu papel não emite notas.</p>'}</div></section></div></div>`}

function danfe(){const p=nf.sim?.payload;if(!p)return;const t=totais(p),prod=amb()==='producao';
 modal('Pré-visualização do DANFE',`<div class="danfe"><div class="dfmarca">${prod?'PRÉ-VISUALIZAÇÃO':'SEM VALOR FISCAL — HOMOLOGAÇÃO'}</div>
 <div class="dfcab"><div class="dfemit"><b>${EMIT.nome}</b><span>${EMIT.fantasia}</span><span>CNPJ ${EMIT.cnpj} · ${EMIT.cidade}/${EMIT.uf}</span></div><div class="dfbox"><b>DANFE</b><span>Documento auxiliar da nota fiscal eletrônica</span><span>1 · Saída</span><span>Série ${esc(p.serie)} · Nº (na autorização)</span></div><div class="dfchave"><span>Chave de acesso</span><b>gerada na autorização pela SEFAZ</b><span>Natureza: ${esc(p.natureza_operacao)}</span></div></div>
 <div class="dfsec">Destinatário</div><div class="dfgrid"><div><span>Nome / razão social</span><b>${esc(p.nome_destinatario)}</b></div><div><span>CPF / CNPJ</span><b>${fmtDoc(p.cnpj_destinatario||p.cpf_destinatario)}</b></div><div><span>Endereço</span><b>${esc(p.logradouro_destinatario)}, ${esc(p.numero_destinatario)} ${esc(p.complemento_destinatario||'')} · ${esc(p.bairro_destinatario)}</b></div><div><span>Município / UF · CEP</span><b>${esc(p.municipio_destinatario)}/${esc(p.uf_destinatario)} · ${esc(p.cep_destinatario)}</b></div></div>
 <div class="dfsec">Cálculo do imposto</div><div class="dfgrid dfimp">${[['Base ICMS',t.bcIcms],['Valor ICMS',t.icms],['DIFAL destino',t.difal],['FCP',t.fcp],['Produtos',t.prod],['Frete',t.frete],['Desconto',t.desc],['PIS',t.pis],['COFINS',t.cofins],['Total da nota',t.total]].map(([k,v])=>`<div><span>${k}</span><b>${money(v)}</b></div>`).join('')}</div>
 <div class="dfsec">Produtos / serviços</div><div class="tablewrap"><table class="dftab"><thead><tr><th>Código</th><th>Descrição</th><th>NCM</th><th>CFOP</th><th class="num">Qtd</th><th class="num">V. unit</th><th class="num">V. total</th><th class="num">BC ICMS</th><th class="num">ICMS</th><th class="num">Alíq.</th></tr></thead><tbody>
 ${p.items.map(i=>`<tr><td class="mono">${esc(i.codigo_produto)}</td><td>${esc(i.descricao)}</td><td>${esc(i.codigo_ncm)}</td><td>${esc(i.cfop)}</td><td class="num">${i.quantidade_comercial}</td><td class="num">${money(i.valor_unitario_comercial)}</td><td class="num">${money(i.valor_bruto)}</td><td class="num">${money(i.icms_base_calculo)}</td><td class="num">${money(i.icms_valor)}</td><td class="num">${String(i.icms_aliquota).replace('.',',')}%</td></tr>`).join('')}</tbody></table></div>
 <div class="dfsec">Dados adicionais</div><p class="dfobs">${esc(p.informacoes_adicionais_contribuinte||'')}</p></div>
 <div class="modalfoot"><button data-action="close">Fechar</button></div>`);document.querySelector('.modalback .modal')?.classList.add('modalwide')}

async function simular(){nf.simulando=true;nf.simErro='';nf.conf=false;render();
 try{if(nf.origem==='pedido'){if(!nf.pedido.trim())throw Error('Informe o número do pedido.');nf.sim=await fn('fiscal_simular',{pedido:nf.pedido.trim()})}
  else{const d=dadosNota();if(!d.doc||!d.nome)throw Error('Informe CPF/CNPJ e nome do destinatário.');if(![11,14].includes(d.doc.length))throw Error('CPF precisa de 11 dígitos e CNPJ de 14.');if(!d.itens.length)throw Error('Adicione ao menos um produto.');if(d.itens.some(i=>!(i.qty>0)||!(i.price>0)))throw Error('Confira quantidade e valor dos itens.');nf.sim=await fn('fiscal_simular',{dados:d})}}
 catch(e){nf.sim=null;nf.simErro=e.message}nf.simulando=false;render()}
async function emitir(b){if(!nf.conf){nf.conf=true;render();return}const prod=amb()==='producao';b.disabled=true;b.textContent='Enviando à SEFAZ…';
 try{const r=nf.origem==='pedido'?await fn('fiscal_emitir',{pedido:nf.pedido.trim(),producao:prod}):await fn('fiscal_emitir_avulsa',{dados:dadosNota(),producao:prod});
  if(r.status==='erro'){toast('Recusada: '+(r.mensagem||''));nf.conf=false;render();return}
  toast('Nota enviada. Consultando a SEFAZ…');audit(prod?'NF-e emitida':'NF-e de teste emitida',`${r.ref}${nf.origem==='pedido'?' · pedido '+nf.pedido:' · '+nf.dest.nome}`);
  await new Promise(x=>setTimeout(x,4500));await fn('fiscal_consultar',{ref:r.ref}).catch(()=>{});nf.sim=null;nf.conf=false;if(nf.origem==='avulsa'){nf.itens=[];nf.frete='';nf.desconto=''}nf.notas=null;await carregar();navigate('nfnotas');setTimeout(()=>detalhe(r.ref),400)}
 catch(e){toast(e.message);nf.conf=false;render()}}

// ─────────── Notas emitidas ───────────
function listaNotas(){const q=normalized(nf.busca);return (nf.notas||[]).filter(n=>(!nf.amb||n.ambiente===nf.amb)&&({todas:true,autorizadas:n.status==='autorizado',rejeitadas:/erro|denegado/.test(n.status),canceladas:n.status==='cancelado',processando:/processando/.test(n.status)})[nf.filtro]&&(!q||normalized([n.pedido,n.numero,n.chave,n.ref,n.payload?.nome_destinatario,n.payload?.cpf_destinatario,n.payload?.cnpj_destinatario].join(' ')).includes(q)))}
function notasView(){if(!nf.notas){carregar();return '<div class="empty">Carregando…</div>'}const all=nf.notas,mes=all.filter(n=>String(n.created_at).slice(0,7)===new Date().toISOString().slice(0,7)),aut=mes.filter(n=>n.status==='autorizado'),l=listaNotas();
 const k=(t,v,s,c='')=>`<div class="card kpi"><span class="kpil">${t}</span><span class="kpiv ${c}">${v}</span><span class="kpis">${s}</span></div>`;
 return `<div class="grid kpis4">${k('Autorizadas no mês',aut.length,money(aut.reduce((a,n)=>a+Number(n.valor||0),0)))}${k('Rejeitadas / erro',all.filter(n=>/erro|denegado/.test(n.status)).length,'corrija e emita de novo',all.some(n=>/erro/.test(n.status))?'red':'')}${k('Canceladas',all.filter(n=>n.status==='cancelado').length,'no total')}${k('Ambiente atual',amb()==='producao'?'Produção':'Homologação',amb()==='producao'?'notas com valor fiscal':'notas de teste','')}</div>
 <div class="crmbar"><div class="segtabs">${[['todas','Todas'],['autorizadas','Autorizadas'],['processando','Processando'],['rejeitadas','Rejeitadas'],['canceladas','Canceladas']].map(([f,t])=>`<button class="${nf.filtro===f?'active':''}" data-nf-filtro="${f}">${t}</button>`).join('')}</div>
  <select data-nf-amb aria-label="Ambiente"><option value="">Todos os ambientes</option><option value="homologacao" ${nf.amb==='homologacao'?'selected':''}>Homologação</option><option value="producao" ${nf.amb==='producao'?'selected':''}>Produção</option></select>
  <input type="search" id="nfBuscaNotas" placeholder="Pedido, número, chave, destinatário…" value="${esc(nf.busca)}" style="min-width:240px">${pode()?`<button class="primary small" data-nav="nfemitir">${icon('plus')} Emitir NF-e</button>`:''}</div>
 <div class="tablebox"><div class="tablewrap"><table><thead><tr><th>Emissão</th><th>Número</th><th>Destinatário</th><th>Origem</th><th>Situação</th><th class="num">Valor</th><th></th></tr></thead><tbody>
 ${l.map(n=>{const [t,tom]=STATUS[n.status]||[n.status,''],p=n.payload||{};return `<tr class="clickrow" data-nf-ver="${esc(n.ref)}"><td>${new Date(n.created_at).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}</td><td><b>${esc(n.numero||'—')}</b>${n.serie?`<span class="caption">/${esc(n.serie)}</span>`:''}<br>${n.ambiente==='producao'?'<span class="badge bad">produção</span>':'<span class="badge">teste</span>'}</td><td>${esc(p.nome_destinatario||'—').slice(0,48)}<br><span class="caption">${fmtDoc(p.cnpj_destinatario||p.cpf_destinatario)} · ${esc(p.uf_destinatario||'')}</span></td><td class="caption">${esc(n.pedido||'')}</td><td><span class="badge ${tom}">${esc(t)}</span>${n.mensagem&&/erro|denegado/.test(n.status)?`<br><span class="caption red">${esc(String(n.mensagem).slice(0,80))}</span>`:''}</td><td class="num">${money(Number(n.valor)||0)}</td><td class="row" style="gap:6px;justify-content:flex-end">${n.danfe_url?`<a class="btnlink small" href="${esc(n.danfe_url)}" target="_blank" rel="noopener">DANFE</a>`:''}${n.xml_url?`<a class="btnlink small" href="${esc(n.xml_url)}" target="_blank" rel="noopener">XML</a>`:''}</td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Nenhuma nota neste filtro.</td></tr>'}</tbody></table></div></div>`}
function detalhe(ref){const n=(nf.notas||[]).find(x=>x.ref===ref);if(!n)return;const p=n.payload||{},t=totais(p),[st,tom]=STATUS[n.status]||[n.status,''],cces=n.resposta?.cartas_correcao||[];
 modal(`NF-e ${n.numero?`nº ${esc(n.numero)}`:esc(n.ref)}`,`<div class="row wrap" style="gap:8px;margin-bottom:12px"><span class="badge ${tom}">${esc(st)}</span>${n.ambiente==='producao'?'<span class="badge bad">produção</span>':'<span class="badge">homologação</span>'}<span class="caption">${new Date(n.created_at).toLocaleString('pt-BR')} · por ${esc(n.criado_por||'—')}</span></div>
 ${n.chave?`<p class="caption mono">Chave ${esc(n.chave)}</p>`:''}${n.mensagem?`<div class="notice ${/erro|denegado/.test(n.status)?'warnbox':''}">${esc(n.mensagem)}</div>`:''}
 <div class="dfgrid" style="margin:10px 0"><div><span>Destinatário</span><b>${esc(p.nome_destinatario||'—')}</b></div><div><span>CPF / CNPJ</span><b>${fmtDoc(p.cnpj_destinatario||p.cpf_destinatario)}</b></div><div><span>Destino</span><b>${esc(p.municipio_destinatario||'')}/${esc(p.uf_destinatario||'')}</b></div><div><span>Origem</span><b>${esc(n.pedido||'')}</b></div></div>
 <div class="tablewrap" style="max-height:220px"><table><thead><tr><th>Produto</th><th>CFOP</th><th class="num">Qtd</th><th class="num">Total</th><th class="num">ICMS</th></tr></thead><tbody>${(p.items||[]).map(i=>`<tr><td>${esc(i.descricao)}<br><span class="caption mono">${esc(i.codigo_produto)} · NCM ${esc(i.codigo_ncm)}</span></td><td>${esc(i.cfop)}</td><td class="num">${i.quantidade_comercial}</td><td class="num">${money(i.valor_bruto)}</td><td class="num">${money(i.icms_valor)}</td></tr>`).join('')}</tbody></table></div>
 <div class="dfgrid dfimp" style="margin-top:10px">${[['Total',t.total],['ICMS',t.icms],['DIFAL',t.difal],['PIS + COFINS',t.pis+t.cofins]].map(([k,v])=>`<div><span>${k}</span><b>${money(v)}</b></div>`).join('')}</div>
 ${cces.length?`<h4 style="margin:14px 0 6px">Cartas de correção</h4>${cces.map(c=>`<div class="listline"><span>${new Date(c.em).toLocaleString('pt-BR')}<br><span class="caption">${esc(c.texto)}</span></span>${c.pdf?`<a class="btnlink small" href="${esc(c.pdf)}" target="_blank" rel="noopener">PDF</a>`:''}</div>`).join('')}`:''}
 <div class="modalfoot" style="justify-content:space-between"><div class="row" style="gap:6px">${pode()&&n.status==='autorizado'?`<button class="quiet" data-nf-cancelar="${esc(n.ref)}">Cancelar nota</button><button class="quiet" data-nf-cce="${esc(n.ref)}">Carta de correção</button>`:''}</div><div class="row" style="gap:6px">${n.danfe_url?`<a class="btnlink" href="${esc(n.danfe_url)}" target="_blank" rel="noopener">DANFE</a>`:''}${n.xml_url?`<a class="btnlink" href="${esc(n.xml_url)}" target="_blank" rel="noopener">XML</a>`:''}<button data-nf-consultar="${esc(n.ref)}">${icon('refresh')} Consultar SEFAZ</button><button class="primary" data-action="close">Fechar</button></div></div>`);document.querySelector('.modalback .modal')?.classList.add('modalwide')}
function pedirTexto(ref,tipo){const cancel=tipo==='cancelar';modal(cancel?'Cancelar NF-e':'Carta de correção',`<p class="caption">${cancel?'O cancelamento só é aceito pela SEFAZ dentro do prazo (em geral 24 h após a autorização) e se a mercadoria não circulou.':'Corrige dados que não alteram valores, impostos, destinatário ou data de emissão (ex.: endereço de entrega, transportadora, texto de observação).'}</p>
 <label for="nfTxt">${cancel?'Justificativa (mínimo 15 caracteres)':'Texto da correção (15 a 1.000 caracteres)'}</label><textarea id="nfTxt" style="width:100%;min-height:110px"></textarea>
 <div class="modalfoot"><button data-action="close">Voltar</button><button class="${cancel?'danger':'primary'}" data-nf-enviar="${esc(ref)}" data-tipo="${tipo}">${cancel?'Cancelar a nota':'Enviar correção'}</button></div>`)}

// ─────────── Eventos ───────────
document.addEventListener('input',e=>{const x=e.target;if(x.dataset.nfF){const ks=x.dataset.nfF.split('.');let o=nf;for(const k of ks.slice(0,-1))o=o[k];o[ks[ks.length-1]]=x.value;nf.conf=false;return}
 if(x.dataset.nfIt){const [k,c]=x.dataset.nfIt.split('.');nf.itens[+k][c]=x.value;nf.conf=false;const tr=x.closest('tr');if(tr)tr.children[4].textContent=money(num(nf.itens[+k].qtd)*num(nf.itens[+k].preco));return}
 if(x.id==='nfBuscaNotas'){nf.busca=x.value;const pos=x.selectionStart;render();const n=$('#nfBuscaNotas');n.focus();n.setSelectionRange(pos,pos)}});
document.addEventListener('change',e=>{const x=e.target;if(x.matches('select[data-nf-f]')){const ks=x.dataset.nfF.split('.');let o=nf;for(const k of ks.slice(0,-1))o=o[k];o[ks[ks.length-1]]=x.value}if(x.matches('[data-nf-amb]')){nf.amb=x.value;render()}});
function addItem(){const v=$('#nfBusca')?.value.trim();if(!v)return;const p=nf.prods.find(x=>x.id===v)||nf.prods.find(x=>normalized(x.nome)===normalized(v));if(!p)return toast('Produto não encontrado.');
 const ja=nf.itens.find(i=>i.sku===p.id);if(ja)ja.qtd=String(num(ja.qtd)+1);else nf.itens.push({sku:p.id,nome:p.nome,ncm:p.ncm,imagem:p.imagem,qtd:'1',preco:String(p.preco||'').replace('.',',')});nf.sim=null;nf.conf=false;render();setTimeout(()=>$('#nfBusca')?.focus(),30)}
document.addEventListener('keydown',e=>{if(e.target.id==='nfBusca'&&e.key==='Enter'){e.preventDefault();addItem()}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-nf-origem],[data-nf-rm],[data-nf-filtro],[data-nf-ver],[data-nf-cancelar],[data-nf-cce],[data-nf-enviar],[data-nf-consultar2]');const n2=e.target.closest('.nfgrid [data-nf],.nfres [data-nf]');const bb=b||n2;if(!bb)return;const d=bb.dataset;
 if(d.nfOrigem){nf.origem=d.nfOrigem;nf.sim=null;nf.simErro='';nf.conf=false;render();return}
 if(d.nfRm!==undefined){nf.itens.splice(+d.nfRm,1);nf.sim=null;nf.conf=false;render();return}
 if(d.nfFiltro){nf.filtro=d.nfFiltro;render();return}
 if(d.nfVer&&!e.target.closest('a')){detalhe(d.nfVer);return}
 if(d.nfCancelar){closeModal();pedirTexto(d.nfCancelar,'cancelar');return}
 if(d.nfCce){closeModal();pedirTexto(d.nfCce,'cce');return}
 if(d.nfEnviar){const txt=$('#nfTxt').value.trim();if(txt.length<15)return toast('Escreva pelo menos 15 caracteres.');bb.disabled=true;
  try{if(d.tipo==='cancelar'){await fn('fiscal_cancelar',{ref:d.nfEnviar,justificativa:txt});toast('Cancelamento enviado.');audit('NF-e cancelada',d.nfEnviar)}else{await fn('fiscal_cce',{ref:d.nfEnviar,texto:txt});toast('Carta de correção enviada.')}closeModal();nf.notas=null;await carregar()}catch(x){bb.disabled=false;toast(x.message)}return}
 switch(d.nf){case 'simular':simular();break;case 'danfe':danfe();break;case 'emitir':emitir(bb);break;case 'additem':addItem();break;
  case 'cnpj':{const doc=dig(nf.dest.doc);if(doc.length!==14)return toast('Informe um CNPJ com 14 dígitos (CPF não tem consulta).');bb.disabled=true;try{const r=await fn('cnpj',{cnpj:doc});Object.assign(nf.dest,{nome:r.razao||nf.dest.nome,ie:String(r.ie||'').replace(/\s*\(inativa\)/,''),email:r.email||nf.dest.email,cep:r.cep,logradouro:r.endereco,numero:r.numero,complemento:r.complemento,bairro:r.bairro,municipio:r.cidade,uf:r.uf||nf.dest.uf});toast(`${r.razao} · ${r.situacao}${r.ie?' · IE '+r.ie:' · sem IE'}`)}catch(x){toast(x.message)}render();break}
  case 'cep':{const c=dig(nf.dest.cep);if(c.length!==8)return toast('CEP com 8 dígitos.');try{const r=await fetch(`https://viacep.com.br/ws/${c}/json/`).then(r=>r.json());if(r.erro)throw Error('CEP não encontrado.');Object.assign(nf.dest,{logradouro:r.logradouro||nf.dest.logradouro,bairro:r.bairro||nf.dest.bairro,municipio:r.localidade,uf:r.uf,complemento:nf.dest.complemento||r.complemento||''});render()}catch(x){toast(x.message||'Não consegui buscar o CEP.')}break}}});
document.addEventListener('click',async e=>{const b=e.target.closest('.modalback [data-nf-consultar]');if(!b)return;e.stopImmediatePropagation();b.disabled=true;const ref=b.dataset.nfConsultar;try{const r=await fn('fiscal_consultar',{ref});toast(`${STATUS[r.status]?.[0]||r.status}${r.mensagem?' · '+r.mensagem:''}`)}catch(x){toast(x.message)}closeModal();nf.notas=null;await carregar();detalhe(ref)},true);
addPage('nfemitir','nfe','Emitir NF-e',emitirView,'Nota avulsa ou de um pedido: destinatário, produtos, pagamento, cálculo dos impostos, prévia do DANFE e emissão.','',()=>{});
addPage('nfnotas','receipt','Notas emitidas',notasView,'Todas as NF-e emitidas pelo Jarvis: situação na SEFAZ, DANFE, XML, cancelamento e carta de correção.','',()=>{});
window.NotaFiscal={carregar};
})();
