'use strict';
// Privacidade (LGPD): atender o titular (cliente, fornecedor pessoa física, membro da equipe) — localizar onde os
// dados dele aparecem, exportar tudo num arquivo (acesso e portabilidade, art. 18) e apagar o que não tem guarda
// obrigatória (anotações de CRM). Inclui o registro das operações de tratamento, em linguagem simples.
(()=>{
const st={q:'',res:null};
const so=v=>String(v||'').replace(/\D/g,'');
const mask=d=>{d=so(d);return d.length===11?`${d.slice(0,3)}.***.***-${d.slice(9)}`:d.length===14?`${d.slice(0,2)}.${d.slice(2,5)}.${d.slice(5,8)}/${d.slice(8,12)}-${d.slice(12)}`:d};
function buscar(q){const n=normalized(q).trim(),d=so(q),bate=(nome,doc)=>(d.length>=11&&so(doc)===d)||(!d.length&&n.length>=4&&normalized(nome||'').includes(n));
 const r=[];const add=(fonte,oque,guarda,itens)=>{if(itens.length)r.push({fonte,oque,guarda,itens})};
 add('Pedidos de venda','nome, CPF/CNPJ, cidade, UF, itens e valores','5 anos (documentos fiscais e contábeis)',db.orders.filter(o=>bate(o.customer?.name,o.customer?.doc)).map(o=>({data:o.date,ref:o.id,canal:o.platform,nome:o.customer?.name,doc:o.customer?.doc,cidade:o.customer?.city,uf:o.state||o.customer?.state,valor:o.gross,itens:(o.items||[]).map(i=>`${i.qty}× ${i.title||i.sku}`).join('; ')})));
 add('Vendas diretas','nome, documento, IE, e-mail, telefone, endereço','5 anos (documentos fiscais)',(window.VendaDireta?.vendas?.()||[]).filter(v=>bate(v.cliente?.nome,v.cliente?.doc)).map(v=>({data:v.emissao||v.created_at,ref:v.numero,nome:v.cliente?.nome,doc:v.cliente?.doc,email:v.cliente?.email,telefone:v.cliente?.telefone,endereco:v.cliente?.endereco,valor:v.total,situacao:v.status})));
 add('Contas a receber','nome, documento, parcelas','5 anos (documentos contábeis)',(window.VendaDireta?.titulos?.()||[]).filter(t=>bate(t.cliente,t.cliente_doc)).map(t=>({vencimento:t.vencimento,ref:t.documento||t.id,nome:t.cliente,doc:t.cliente_doc,valor:t.valor,situacao:t.status})));
 add('Notas de entrada e devoluções','nome, documento e endereço da nota','5 anos (documentos fiscais)',(db.purchases||[]).filter(p=>bate(p.fornecedor,p.fornecedorDoc||p.fornecedor_doc)).map(p=>({data:p.emissao,ref:`NF ${p.numero||''}`,nome:p.fornecedor,doc:p.fornecedorDoc||p.fornecedor_doc,tipo:p.tipo,valor:p.valor})));
 add('Atendimento (marketplaces)','apelido do comprador e mensagens trocadas','enquanto houver o caso e 5 anos para defesa em reclamações',(window.Atendimento?.lista?.()||[]).filter(a=>!d.length&&n.length>=4&&normalized((a.comprador||'')+' '+JSON.stringify(a.mensagens||[])).includes(n)).map(a=>({data:a.aberto_em,ref:a.pedido||a.id,tipo:a.tipo,comprador:a.comprador,motivo:a.motivo})));
 const crm=Object.entries(db.crm||{}).filter(([k])=>(d.length>=11&&k==='DOC-'+d)||(!d.length&&n.length>=4&&normalized(k).includes(n.replace(/\s+/g,'-'))));
 add('Anotações de CRM','fase, etiquetas e anotações da equipe','pode ser apagado a pedido do titular',crm.map(([k,v])=>({chave:k,...v})));
 return r}
function view(){const r=st.res;return `<div class="grid two"><section class="card"><div class="cardhead"><div><h2>${icon('search')} Atender um titular</h2><p class="caption">Quando alguém pede para saber, corrigir, levar ou apagar os seus dados (LGPD, art. 18).</p></div></div>
  <div class="searchin">${icon('search')}<input type="search" id="lgpdQ" placeholder="CPF, CNPJ ou nome completo" value="${esc(st.q)}"></div>
  <p class="caption" style="margin-top:8px">Com CPF/CNPJ a busca é exata. Por nome, use o nome completo para não misturar pessoas diferentes.</p>
  ${r?(r.length?`<div class="lgpdres">${r.map(x=>`<div class="lgpdfonte"><div><strong>${x.fonte}</strong><small>${x.oque}</small></div><span class="badge info">${x.itens.length} registro(s)</span><small class="caption">Guarda: ${x.guarda}</small></div>`).join('')}</div>
   <div class="row wrap" style="margin-top:12px"><button class="primary small" data-lgpd="exportar">${icon('download')} Exportar tudo (arquivo para o titular)</button>${r.some(x=>x.fonte==='Anotações de CRM')?`<button class="small" data-lgpd="apagar">Apagar anotações de CRM</button>`:''}</div>
   <div id="lgpdConf"></div>`:'<p class="caption" style="margin-top:12px">Nenhum dado encontrado com essa busca.</p>'):''}</section>
 <section class="card"><h2>Como responder</h2><ol class="lgpdpassos"><li><strong>Confirme a identidade</strong> de quem pede (documento com foto ou a própria conta do marketplace).</li><li><strong>Busque</strong> pelo CPF/CNPJ aqui e <strong>exporte</strong> o arquivo: é a resposta para "quais dados vocês têm" e para a portabilidade.</li><li><strong>Correção:</strong> ajuste no Bling ou no marketplace (a origem do cadastro); a próxima sincronização corrige aqui.</li><li><strong>Exclusão:</strong> anotações de CRM podem ser apagadas aqui. Pedidos, notas e contas têm guarda obrigatória de 5 anos (legislação fiscal) e ficam, com acesso restrito.</li><li><strong>Prazo:</strong> responda em até 15 dias (LGPD, art. 19). Cada exportação e exclusão fica registrada na auditoria.</li></ol></section></div>
 <div class="tablebox" style="margin-top:18px"><div class="tabletop"><div><h2>Registro das operações de tratamento</h2><p class="caption">O que o Jarvis guarda, por quê, com qual base legal e por quanto tempo.</p></div></div><div class="tablewrap"><table><thead><tr><th>Dados</th><th>De quem</th><th>Para quê</th><th>Base legal (LGPD, art. 7º)</th><th>Guarda</th><th>Compartilhado com</th></tr></thead><tbody>
 ${[['Nome, CPF/CNPJ, cidade/UF, itens e valores dos pedidos','Clientes dos marketplaces','Faturar, entregar, conciliar recebimentos, contabilizar','Execução de contrato (V) e obrigação legal (II)','5 anos após o exercício','Bling, marketplaces, Focus NFe, escritório contábil'],
  ['Nome, documento, IE, e-mail, telefone, endereço','Clientes de venda direta (B2B)','Emitir nota, cobrar parcelas','Execução de contrato (V) e obrigação legal (II)','5 anos','Focus NFe, escritório contábil'],
  ['Apelido e mensagens de atendimento','Compradores com reclamação ou pergunta','Resolver o caso e proteger a reputação','Execução de contrato (V) e exercício regular de direitos (VI)','Durante o caso + 5 anos','Mercado Livre (origem)'],
  ['Histórico de compras e anotações de CRM','Clientes','Recompra, relacionamento, análise de vendas','Legítimo interesse (IX), com opção de exclusão','Até o pedido de exclusão','Não é compartilhado'],
  ['Nome, CNPJ/CPF e notas','Fornecedores','Pagar, escriturar compras','Execução de contrato (V) e obrigação legal (II)','5 anos','Escritório contábil'],
  ['E-mail, nome, papel e ações no sistema','Equipe da Compra Store','Controle de acesso e auditoria','Legítimo interesse (IX) e obrigação legal (II)','Enquanto tiver acesso + 5 anos da auditoria','Não é compartilhado']].map(l=>`<tr>${l.map(c=>`<td style="white-space:normal">${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`}
function bind(){const i=$('#lgpdQ');if(!i)return;i.onkeydown=e=>{if(e.key==='Enter'){st.q=i.value.trim();st.res=st.q.length>=4?buscar(st.q):null;render()}};i.onchange=()=>{st.q=i.value.trim();st.res=st.q.length>=4?buscar(st.q):null;render()}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-lgpd]');if(!b)return;const k=b.dataset.lgpd;
 if(k==='exportar'){const r=st.res||[],doc={gerado_em:new Date().toISOString(),controlador:'Compra Store (WOLFACH E-COMMERCE LTDA) · CNPJ 65.193.225/0001-57',busca:st.q,dados:r.map(x=>({fonte:x.fonte,dados_tratados:x.oque,guarda:x.guarda,registros:x.itens}))};
  const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}));a.download=`lgpd-titular-${so(st.q)||'busca'}.json`;a.click();audit('LGPD: dados do titular exportados',mask(st.q)||st.q);return}
 if(k==='apagar'){$('#lgpdConf').innerHTML=`<div class="notice warnbox" style="margin-top:12px">Apagar as anotações de CRM encontradas? Pedidos, notas e contas continuam (guarda fiscal). <div class="row" style="margin-top:8px"><button class="small" data-lgpd="cancelar">Cancelar</button><button class="small primary" data-lgpd="confirmar">Apagar anotações</button></div></div>`;return}
 if(k==='cancelar'){$('#lgpdConf').innerHTML='';return}
 if(k==='confirmar'){const x=(st.res||[]).find(y=>y.fonte==='Anotações de CRM');for(const it of x?.itens||[])delete db.crm[it.chave];save();audit('LGPD: anotações de CRM apagadas',`${(x?.itens||[]).length} registro(s) · ${mask(st.q)||st.q}`);st.res=buscar(st.q);render();toast('Anotações de CRM apagadas.')}});
addPage('privacidade','shield','Privacidade (LGPD)',view,'Atender pedidos de titulares (acesso, portabilidade, correção, exclusão) e o registro do que o sistema guarda, por quê e por quanto tempo.','',bind);
})();
