"use strict";(()=>{Object.assign(paths,{raiox:"M4 19h16 M6 16V9 M10 16V5 M14 16v-4 M18 16V8"});const i={base:""};window.Reiniciar?.registrar(i,["base"]);const l=s=>{const[o,n]=s.split("-").map(Number);return new Date(o,n-2,1,12).toLocaleDateString("sv-SE").slice(0,7)},c=s=>{const[o,n]=s.split("-").map(Number);return new Date(o,n-1,1,12).toLocaleDateString("pt-BR",{month:"short",year:"numeric"}).replace(".","")},e=s=>s==null?"—":(s*100).toFixed(1).replace(".",",")+"%",r=s=>s==null?"—":`${s>0?"+":s<0?"−":""}${Math.abs(s*100).toFixed(2).replace(".",",")} p.p.`,d=s=>s>5e-5?"green":s<-5e-5?"red":"";function p(s,o){const n=o?Math.min(100,Math.abs(s)/o*100):0;return`<span class="rxbar ${s<0?"neg":"pos"}"><i style="width:${n.toFixed(1)}%"></i></span>`}function u(){if(!window.Margem?.raiox)return'<div class="empty">Carregando…</div>';const s=typeof month=="string"?month:new Date().toLocaleDateString("sv-SE").slice(0,7),o=[...new Set((db.orders||[]).map(a=>String(a.date||"").slice(0,7)))].filter(a=>a&&a<s).sort().reverse(),n=i.base&&o.includes(i.base)?i.base:o.includes(l(s))?l(s):o[0];if(!n)return'<div class="empty">Precisa de pelo menos dois meses de vendas para comparar.</div>';const t=Margem.raiox(n,s),b=Math.max(.001,...t.fatores.map(a=>Math.abs(a.efeito)),Math.abs(t.canais.mix),Math.abs(t.canais.marg)),h=[...o.slice(0,5).reverse(),s],$=Margem.tendencia(h),v=t.produtos.itens.filter(a=>a.contrib<-5e-5).slice(0,15),m=[...t.produtos.itens].reverse().filter(a=>a.contrib>5e-5).slice(0,5);return`<div class="crmbar"><span>Comparando <strong>${esc(c(s))}</strong> (competência do cabeçalho) com</span><select data-rx="base" aria-label="Mês de comparação">${o.slice(0,18).map(a=>`<option value="${a}" ${a===n?"selected":""}>${esc(c(a))}</option>`).join("")}</select>
  <span class="caption">Margem de contribuição = vendas − tarifa − frete pago pela loja − custo dos produtos − tributos (pedidos com custo cadastrado).</span></div>
 <div class="grid kpis4"><div class="card kpi"><span class="kpil">Margem ${esc(c(n))}</span><span class="kpiv">${e(t.margemA)}</span><span class="kpis">${money(t.a.lucro)} em ${money(t.a.venda)}</span></div>
  <div class="card kpi"><span class="kpil">Margem ${esc(c(s))}</span><span class="kpiv ${d(t.variacao)}">${e(t.margemB)}</span><span class="kpis">${money(t.b.lucro)} em ${money(t.b.venda)}</span></div>
  <div class="card kpi"><span class="kpil">Variação</span><span class="kpiv ${d(t.variacao)}">${r(t.variacao)}</span><span class="kpis">${t.variacao!=null?`${money(t.b.venda*(t.variacao||0))} a ${t.variacao<0?"menos":"mais"} no mês, no volume atual`:""}</span></div>
  <div class="card kpi"><span class="kpil">Fora da conta</span><span class="kpiv">${t.semCusto.b}</span><span class="kpis">pedido(s) sem custo cadastrado em ${esc(c(s))}</span></div></div>
 <div class="grid two" style="align-items:start">
 <section class="tablebox"><div class="tabletop"><h2>De onde veio a variação</h2><span class="caption">em pontos percentuais da margem</span></div><div class="tablewrap"><table><thead><tr><th>Fator</th><th class="num">${esc(c(n))}</th><th class="num">${esc(c(s))}</th><th class="num">Efeito na margem</th><th style="min-width:120px"></th></tr></thead><tbody>
  ${t.fatores.map(a=>`<tr><td>${a.t}</td><td class="num">${e(a.a)}</td><td class="num">${e(a.b)}</td><td class="num ${d(a.efeito)}"><strong>${r(a.efeito)}</strong></td><td>${p(a.efeito,b)}</td></tr>`).join("")}
  <tr><td><strong>Total</strong></td><td class="num">${e(t.margemA)}</td><td class="num">${e(t.margemB)}</td><td class="num ${d(t.variacao)}"><strong>${r(t.variacao)}</strong></td><td></td></tr></tbody></table></div>
  <p class="caption" style="padding:0 14px 12px">Cada linha mostra o peso do fator nas vendas. Tarifa subindo de 20% para 22% tira 2 pontos da margem.</p></section>
 <section class="tablebox"><div class="tabletop"><h2>Por canal</h2><span class="caption">mix: vender mais no canal de margem menor · margem: o canal ficou pior</span></div><div class="tablewrap"><table><thead><tr><th>Canal</th><th class="num">Peso nas vendas</th><th class="num">Margem</th><th class="num">Efeito</th></tr></thead><tbody>
  ${t.canais.itens.map(a=>`<tr><td><strong>${esc(a.k)}</strong></td><td class="num">${e(a.wA)} → ${e(a.wB)}</td><td class="num">${e(a.ma)} → <span class="${d((a.mb??0)-(a.ma??0))}">${e(a.mb)}</span></td><td class="num ${d(a.contrib)}">${r(a.contrib)}</td></tr>`).join("")}
  <tr><td colspan="3">Efeito mix (troca de peso entre canais)</td><td class="num ${d(t.canais.mix)}">${r(t.canais.mix)}</td></tr><tr><td colspan="3">Efeito margem (cada canal em si)</td><td class="num ${d(t.canais.marg)}">${r(t.canais.marg)}</td></tr></tbody></table></div></section></div>
 <section class="tablebox"><div class="tabletop"><div><h2>Produtos que mais puxaram a margem para baixo</h2><p class="caption">Contribuição de cada produto para a variação (a soma de todos os produtos dá a variação total) e o que mudou nele, por unidade.</p></div><div class="row" style="gap:6px;flex-wrap:wrap"><button class="small" data-nav="margem">${icon("radar")} Preço mínimo (Radar)</button><button class="small" data-nav="concorrencia">${icon("tag")} Ajustar preços no Mercado Livre</button><button class="small" data-nav="catalogo">${icon("tag")} Preço por canal (Shopee, Magalu)</button></div></div><div class="tablewrap"><table><thead><tr><th>Produto</th><th class="num">Vendas ${esc(c(s))}</th><th class="num">Margem</th><th class="num">Mix</th><th class="num">Margem do item</th><th class="num">Contribuição</th><th>O que mudou · o que fazer</th></tr></thead><tbody>
  ${v.map(a=>`<tr><td><strong>${esc(a.b?.nome||a.a?.nome||a.k)}</strong><br><span class="caption mono">${esc(a.k)}</span></td><td class="num">${money(a.b?.venda||0)}<br><span class="caption">${Math.round(a.b?.u||0)} un.</span></td><td class="num">${e(a.ma)} → <span class="${(a.mb??0)<0?"red":""}">${e(a.mb)}</span></td><td class="num ${d(a.eMix)}">${r(a.eMix)}</td><td class="num ${d(a.eMarg)}">${r(a.eMarg)}</td><td class="num red"><strong>${r(a.contrib)}</strong></td><td class="caption">${esc(a.diag)}</td></tr>`).join("")||'<tr><td colspan="7" class="empty">Nenhum produto piorou a margem. ✓</td></tr>'}</tbody></table></div></section>
 ${m.length?`<section class="tablebox"><div class="tabletop"><h2>Os que mais ajudaram</h2></div><div class="tablewrap"><table><thead><tr><th>Produto</th><th class="num">Vendas</th><th class="num">Margem</th><th class="num">Contribuição</th><th>O que mudou</th></tr></thead><tbody>${m.map(a=>`<tr><td><strong>${esc(a.b?.nome||a.a?.nome||a.k)}</strong></td><td class="num">${money(a.b?.venda||0)}</td><td class="num">${e(a.ma)} → ${e(a.mb)}</td><td class="num green">${r(a.contrib)}</td><td class="caption">${esc(a.diag)}</td></tr>`).join("")}</tbody></table></div></section>`:""}
 <section class="tablebox"><div class="tabletop"><h2>Últimos meses</h2><span class="caption">peso de cada fator nas vendas</span></div><div class="tablewrap"><table><thead><tr><th>Mês</th><th class="num">Vendas (com custo)</th><th class="num">Tarifa</th><th class="num">Frete</th><th class="num">Custo</th><th class="num">Tributos</th><th class="num">Margem</th></tr></thead><tbody>
  ${$.map(a=>`<tr><td>${esc(c(a.mes))}</td><td class="num">${money(a.venda)}</td><td class="num">${e(a.tarifa)}</td><td class="num">${e(a.frete)}</td><td class="num">${e(a.custo)}</td><td class="num">${e(a.tributos)}</td><td class="num"><strong>${e(a.margem)}</strong></td></tr>`).join("")}</tbody></table></div></section>`}document.addEventListener("change",s=>{const o=s.target.closest('[data-rx="base"]');o&&(i.base=o.value,render())}),addPage("raiox","raiox","Raio-X da margem",u,"Por que a margem mudou de um mês para o outro: tarifa, frete, custo, tributos, canais e produtos — e o que fazer.","",()=>{})})();
