'use strict';
// Experiência do cliente. Cliente final: NPS e comentários da Central do Cliente, pedidos de ajuda (tempo de resposta,
// prazo, motivos, produtos que mais geram chamado) e o link/QR da Central para a embalagem. Equipe: NPS interno do
// Jarvis, chamados de suporte e uso por pessoa. A cada 30 dias o Jarvis pergunta a cada pessoa quanto ele ajuda.
(()=>{
Object.assign(paths,{smile:'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18z M8.5 14.5c1.8 2 5.2 2 7 0 M9 9.5h.01 M15 9.5h.01',team:'M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8z M2 21c0-3.9 3.1-7 7-7s7 3.1 7 7 M17 11a3 3 0 1 0 0-6 M22 21c0-3-1.8-5.5-4.5-6.5'});
const st={p:null,at:null,ch:null,carregando:false,dias:90};
window.Reiniciar?.registrar(st,['dias']); // estado de tela: volta ao original ao clicar no menu
const ini=d=>new Date(Date.now()-d*864e5).toISOString();
async function carregar(){if(st.carregando)return;if(!window.Cloud?.ws){st.p=[];st.at=[];st.ch=[];setTimeout(render);return}st.carregando=true;const c=Cloud.client,ws=Cloud.ws;
 const [p,a,h]=await Promise.all([c.from('cx_pesquisas').select('*').eq('workspace_id',ws).gte('created_at',ini(365)).order('created_at',{ascending:false}).limit(2000),c.from('atendimentos').select('id,canal,tipo,status,motivo,produto,pedido,prazo,aberto_em,fechado_em,mensagens,comprador').eq('workspace_id',ws).gte('aberto_em',ini(180)).limit(3000),c.from('chamados').select('numero,status,tipo,urgencia,created_at,updated_at,respostas,nome').eq('workspace_id',ws).limit(1000)]);
 st.p=p.data||[];st.at=a.data||[];st.ch=h.data||[];st.carregando=false;if(['cx','cxequipe'].includes(page)&&!document.querySelector('.modalback'))render()}
const nps=l=>{if(!l.length)return null;const pro=l.filter(x=>x.nota>=9).length,det=l.filter(x=>x.nota<=6).length;return Math.round((pro-det)/l.length*100)};
const horas=ms=>ms==null?'—':ms<3600e3?Math.round(ms/60e3)+' min':ms<864e5?(ms/3600e3).toFixed(1).replace('.',',')+' h':(ms/864e5).toFixed(1).replace('.',',')+' d';
function primeiraResp(a){const m=(a.mensagens||[]).find(x=>/vend|equipe|loja|seller|jarvis/i.test(String(x.de||x.from||'')));const t=m?.em||m?.date;return t&&a.aberto_em?new Date(t)-new Date(a.aberto_em):null}
const med=l=>{const v=l.filter(x=>x!=null).sort((a,b)=>a-b);return v.length?v[Math.floor(v.length/2)]:null};
function barras(l,max){return l.map(([k,v,s])=>`<div class="fxbarra"><span title="${esc(k)}">${esc(k)}</span><i><b class="green" style="width:${(v/max*100).toFixed(0)}%"></b></i><em>${s??v}</em></div>`).join('')}
function view(){if(!st.p){carregar();return '<div class="empty">Carregando…</div>'}const desde=ini(st.dias),P=st.p.filter(x=>x.created_at>=desde),N=P.filter(x=>x.tipo==='nps'),C=P.filter(x=>x.tipo==='csat'),A=st.at.filter(x=>(x.aberto_em||'')>=desde);
 const n=nps(N),resp=A.map(primeiraResp),noPrazo=A.filter(a=>{const r=primeiraResp(a);return r!=null&&a.prazo&&new Date(a.aberto_em).getTime()+r<=new Date(a.prazo).getTime()}).length,comResp=resp.filter(x=>x!=null).length;
 const pedidos=db.orders.filter(o=>o.date>=desde.slice(0,10)).length,taxa=pedidos?A.length/pedidos*100:0;
 const motivos=[...A.reduce((m,a)=>m.set(a.motivo||a.tipo||'Outros',(m.get(a.motivo||a.tipo||'Outros')||0)+1),new Map())].sort((a,b)=>b[1]-a[1]).slice(0,8);
 const unid=new Map();for(const o of db.orders)if(o.date>=desde.slice(0,10))for(const i of o.items||[])unid.set(i.title||i.sku,(unid.get(i.title||i.sku)||0)+(Number(i.qty)||0));
 const prods=[...A.reduce((m,a)=>{if(a.produto)m.set(a.produto,(m.get(a.produto)||0)+1);return m},new Map())].map(([k,v])=>[k,v,unid.get(k)?`${v} · ${(v/unid.get(k)*100).toFixed(1).replace('.',',')}% das vendas`:v]).sort((a,b)=>b[1]-a[1]).slice(0,8);
 const link=location.origin+location.pathname.replace(/[^/]*$/,'')+'cliente.html',abertos=A.filter(a=>!a.fechado_em&&!/fech|resol/i.test(a.status||''));
 const k=(t,v,s,c='')=>`<div class="card kpi"><span class="kpil">${t}</span><span class="kpiv ${c}">${v}</span><span class="kpis">${s}</span></div>`;
 return `<div class="crmbar"><div class="segtabs">${[[30,'30 dias'],[90,'90 dias'],[365,'12 meses']].map(([d,t])=>`<button class="${st.dias===d?'active':''}" data-cx-dias="${d}">${t}</button>`).join('')}</div><button class="small" data-nav="atendimento">${icon('chat')} Fila de atendimento</button></div>
 <div class="grid kpis4">${k('NPS do comprador',n==null?'—':n,N.length?`${N.length} avaliação(ões) · ${N.filter(x=>x.nota>=9).length} promotores, ${N.filter(x=>x.nota<=6).length} detratores`:'aguardando as primeiras avaliações',n==null?'':n>=50?'green':n>=0?'gold':'red')}
 ${k('Primeira resposta',horas(med(resp)),`mediana · ${A.length?Math.round(noPrazo/Math.max(1,comResp)*100)+'% dentro do prazo':'sem atendimentos no período'}`)}
 ${k('Chamados por 100 pedidos',taxa.toFixed(1).replace('.',','),`${A.length} atendimento(s) · ${abertos.length} em aberto`,taxa>5?'red':taxa>2?'gold':'green')}
 ${k('Satisfação no atendimento',C.length?(C.reduce((a,x)=>a+x.nota,0)/C.length).toFixed(1).replace('.',',')+' / 10':'—',C.length?`${C.length} resposta(s)`:'pesquisa após cada atendimento')}</div>
 <div class="grid two"><section class="card"><h3>O que mais faz o cliente chamar</h3>${motivos.length?barras(motivos,motivos[0][1]):'<p class="caption">Sem atendimentos no período.</p>'}
  <h3 style="margin-top:16px">Produtos com mais chamados</h3>${prods.length?barras(prods,prods[0][1]):'<p class="caption">Nenhum produto com chamado no período.</p>'}</section>
 <section class="card"><h3>O que os compradores dizem</h3>${P.filter(x=>x.comentario&&x.tipo!=='sistema').slice(0,8).map(x=>`<div class="cxcom"><b class="badge ${x.nota>=9?'ok':x.nota<=6?'bad':'warn'}">${x.nota}</b><div><p>${esc(x.comentario)}</p><small class="caption">${new Date(x.created_at).toLocaleDateString('pt-BR')}${x.canal?' · '+esc(x.canal):''}${x.produto?' · '+esc(String(x.produto).slice(0,40)):''}</small></div></div>`).join('')||'<p class="caption">Os comentários das avaliações aparecem aqui.</p>'}</section></div>
 <section class="card cxlink"><div><h3>Central do Cliente</h3><p class="caption">Página pública onde o comprador acompanha o pedido (com o número e 4 dígitos do CPF), pede ajuda e avalia a compra. Os pedidos de ajuda caem na fila de Atendimento com prazo de 1 dia útil.</p>
  <div class="row wrap" style="gap:8px"><code class="cialinha">${esc(link)}</code><button class="small" data-cx-copiar="${esc(link)}">Copiar link</button><a class="btnlink small" href="${esc(link)}" target="_blank" rel="noopener">Abrir</a><button class="small" data-cx="cartao">${icon('print')} Cartão para a embalagem</button></div>
  <p class="caption" style="margin-top:8px">Nas vendas de marketplace, use o cartão só para manual, montagem e garantia — as regras do Mercado Livre e da Shopee não permitem levar o cliente para comprar fora da plataforma.</p></div><div id="cxQr" class="cxqr"></div></section>`}
function equipeView(){if(!st.p){carregar();return '<div class="empty">Carregando…</div>'}const S=st.p.filter(x=>x.tipo==='sistema'),n=nps(S),ch=st.ch,abertos=ch.filter(c=>c.status!=='resolvido');
 const resp=ch.map(c=>{const r=(c.respostas||[]).find(x=>x.de==='dono');return r?.em?new Date(r.em)-new Date(c.created_at):null});
 const uso=new Map();for(const a of db.audit||[]){if((a.time||'')<ini(7)||!/@/.test(a.actor||''))continue;const q=a.actor.split('@')[0];uso.set(q,(uso.get(q)||0)+1)}const U=[...uso].sort((a,b)=>b[1]-a[1]).slice(0,10);
 const k=(t,v,s,c='')=>`<div class="card kpi"><span class="kpil">${t}</span><span class="kpiv ${c}">${v}</span><span class="kpis">${s}</span></div>`;
 return `<div class="grid kpis4">${k('NPS da equipe com o Jarvis',n==null?'—':n,S.length?`${S.length} resposta(s) · média ${(S.reduce((a,x)=>a+x.nota,0)/S.length).toFixed(1).replace('.',',')}`:'a pergunta aparece a cada 30 dias para cada pessoa',n==null?'':n>=50?'green':n>=0?'gold':'red')}
 ${k('Chamados de suporte em aberto',abertos.length,`${ch.length} no total`,abertos.length?'gold':'')}${k('Primeira resposta ao chamado',horas(med(resp)),'mediana')}${k('Pessoas usando (7 dias)',uso.size,`${[...uso.values()].reduce((a,b)=>a+b,0)} ações registradas`)}</div>
 <div class="grid two"><section class="card"><h3>O que a equipe diz do Jarvis</h3>${S.slice(0,10).map(x=>`<div class="cxcom"><b class="badge ${x.nota>=9?'ok':x.nota<=6?'bad':'warn'}">${x.nota}</b><div><p>${esc(x.comentario||'(sem comentário)')}</p><small class="caption">${new Date(x.created_at).toLocaleDateString('pt-BR')}</small></div></div>`).join('')||'<p class="caption">Ainda sem respostas.</p>'}<div class="row wrap" style="margin-top:10px"><button class="small" data-cx="avaliar">Avaliar o Jarvis agora</button><button class="small quiet" data-nav="suporte">Chamados de suporte</button></div></section>
 <section class="card"><h3>Uso por pessoa · 7 dias</h3>${U.length?barras(U,U[0][1]):'<p class="caption">Sem registros recentes.</p>'}<p class="caption">Ações registradas no log de auditoria (lançamentos, baixas, notas, ajustes). Quem pouco usa talvez precise de treinamento: veja o Manual e a rotina do perfil.</p></section></div>`}
// Pergunta de satisfação com o sistema (a cada 30 dias, por pessoa e aparelho).
function perguntar(forcar){if(!window.Cloud?.ws||(!forcar&&document.querySelector('.cxnps')))return;try{if(!forcar&&Date.now()-Number(localStorage.getItem('jv_nps_em')||0)<30*864e5)return}catch{}
 if(!forcar&&Date.now()-Number(sessionStorage.getItem('jv_inicio')||Date.now())<3*60e3)return;
 const d=document.createElement('div');d.className='cxnps';d.innerHTML=`<button class="cxx" data-cxn="fechar" aria-label="Fechar">×</button><b>De 0 a 10, quanto o Jarvis facilita o seu dia?</b><div class="cxnotas">${[...Array(11)].map((_,i)=>`<button data-cxn-nota="${i}">${i}</button>`).join('')}</div><textarea placeholder="O que melhoraria? (opcional)" rows="2"></textarea><button class="primary small" data-cxn="enviar" disabled>Enviar</button>`;document.body.appendChild(d)}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-cx],[data-cx-dias],[data-cx-copiar],[data-cxn],[data-cxn-nota]');if(!b)return;const d=b.dataset;
 if(d.cxDias){st.dias=+d.cxDias;render();return}
 if(d.cxCopiar){navigator.clipboard?.writeText(d.cxCopiar).then(()=>toast('Link copiado.'),()=>toast('Não consegui copiar.'));return}
 if(d.cx==='avaliar'){perguntar(true);return}
 if(d.cx==='cartao'){const link=location.origin+location.pathname.replace(/[^/]*$/,'')+'cliente.html';const w=window.open('','_blank');if(!w)return toast('Libere pop-ups.');w.document.write(`<html><head><title>Cartão Compra Store</title><style>body{font-family:Arial;margin:0;display:flex;flex-wrap:wrap;gap:8mm;padding:8mm}.c{width:90mm;height:55mm;border:1px dashed #bbb;border-radius:4mm;padding:5mm;box-sizing:border-box;display:flex;gap:4mm;align-items:center}.c h2{margin:0 0 2mm;font-size:13pt;color:#0f7f70}.c p{margin:0;font-size:8.5pt;color:#333}.q{width:30mm;height:30mm;flex:none}</style><script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"><\/script></head><body>${[...Array(8)].map((_,i)=>`<div class="c"><div class="q" id="q${i}"></div><div><h2>Obrigado pela compra! 💛</h2><p>Manual, montagem, garantia e ajuda com o seu pedido:</p><p><b>${link.replace(/^https?:\/\//,'')}</b></p><p>Aponte a câmera para o código.</p></div></div>`).join('')}<script>onload=()=>{for(let i=0;i<8;i++)new QRCode(document.getElementById('q'+i),{text:${JSON.stringify(link)},width:113,height:113});setTimeout(()=>print(),600)}<\/script></body></html>`);w.document.close();return}
 const box=b.closest('.cxnps');if(!box)return;
 if(d.cxnNota){box.querySelectorAll('[data-cxn-nota]').forEach(x=>x.classList.toggle('on',x===b));box.dataset.nota=d.cxnNota;box.querySelector('[data-cxn="enviar"]').disabled=false;return}
 if(d.cxn==='fechar'){try{localStorage.setItem('jv_nps_em',String(Date.now()-23*864e5))}catch{}box.remove();return}
 if(d.cxn==='enviar'){b.disabled=true;const {error}=await Cloud.client.from('cx_pesquisas').insert({workspace_id:Cloud.ws,tipo:'sistema',nota:+box.dataset.nota,comentario:box.querySelector('textarea').value.trim()||null,origem:'interno',user_id:Cloud.session?.user?.id});
  if(error){toast(error.message);b.disabled=false;return}try{localStorage.setItem('jv_nps_em',String(Date.now()))}catch{}box.innerHTML='<b>Obrigado! Sua opinião vai direto para quem cuida do Jarvis. 💛</b>';setTimeout(()=>box.remove(),2500);st.p=null}});
try{if(!sessionStorage.getItem('jv_inicio'))sessionStorage.setItem('jv_inicio',String(Date.now()))}catch{}
setInterval(()=>{if(window.Cloud?.ws&&page!=='login')perguntar(false)},60e3);
function bindCx(){const q=$('#cxQr');if(q&&!q.dataset.ok){q.dataset.ok='1';const go=()=>{try{new QRCode(q,{text:location.origin+location.pathname.replace(/[^/]*$/,'')+'cliente.html',width:132,height:132})}catch{}};if(window.QRCode)go();else{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js';s.onload=go;document.head.appendChild(s)}}}
addPage('cx','smile','Experiência do cliente',view,'NPS e comentários dos compradores, tempo de resposta, motivos e produtos que mais geram chamado, e a Central do Cliente.','',bindCx);
addPage('cxequipe','team','Experiência da equipe',equipeView,'Satisfação da equipe com o Jarvis, chamados de suporte e uso por pessoa.','',()=>{});
})();
