'use strict';
// Fiscal › DIFAL e GNRE. O DIFAL/FCP de cada nota de venda é lido do XML autorizado no Bling (cron a cada 2 min).
// UF sem inscrição estadual: uma GNRE por nota, antes da mercadoria sair. UF com inscrição: apuração no mês e uma guia
// mensal. As guias saem em lote pelo webservice do Portal GNRE com o certificado A1 (ou em XML para enviar pelo site),
// voltam com linha digitável e PDF, viram título no contas a pagar e são pagas pelo arquivo do banco (SISPAG, forma 91).
(()=>{
Object.assign(paths,{guia:'M5 3h14v18H5z M8 7h8 M8 11h8 M8 15h5 M15 17l1.5 1.5L19 16'});
const UFS=['AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO'];
const dBR=d=>d?new Date(String(d).slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const hoje=()=>new Date().toLocaleDateString('sv-SE');
const SIT={pendente:['Sem guia','warn'],mensal:['Apuração mensal','info'],guia:['Em guia','ok'],paga:['Paga','ok'],sem_difal:['Sem DIFAL',''],cancelada:['Nota cancelada',''],ignorada:['Paga por fora','']};
const GST={rascunho:['Rascunho','info'],enviada:['Enviada · aguardando portal','warn'],emitida:['Emitida','ok'],rejeitada:['Rejeitada','bad'],paga:['Paga','ok'],cancelada:['Cancelada','']};
const st={aba:'notas',mes:hoje().slice(0,7),uf:'',sit:'pendente',notas:null,guias:null,diag:null,carregando:false,sel:new Set(),gsel:new Set()};
const fcfg=()=>window.Parametros?.cfg?.()||db.gerencial?.fiscal||{};
const duf=()=>fcfg().difal_uf||{};
const salvarFiscal=n=>{db.gerencial={...(db.gerencial||{}),fiscal:{...(db.gerencial?.fiscal||{}),...n}};save()};
const pode=()=>['owner','member','financeiro'].includes(window.Cloud?.role||'owner');
async function gnre(action,body={}){const r=await Cloud.client.functions.invoke('gnre',{body:{workspace_id:Cloud.ws,action,...body}});if(r.error){let msg=r.error.message;try{msg=(await r.error.context.json()).error||msg}catch{}throw Error(msg)}return r.data}
async function integ(action,body={}){const r=await Cloud.client.functions.invoke('integrations',{body:{workspace_id:Cloud.ws,action,...body}});if(r.error){let msg=r.error.message;try{msg=(await r.error.context.json()).error||msg}catch{}throw Error(msg)}return r.data}

async function carregar(){if(st.carregando||!window.Cloud?.client)return;st.carregando=true;
 try{const ini=`${st.mes}-01`,fim=`${st.mes}-31`;
  const [n,g]=await Promise.all([Cloud.client.from('difal_notas').select('chave,numero,serie,emissao,uf,dest_nome,dest_doc,valor_nota,v_difal,v_fcp,situacao,guia_id').eq('workspace_id',Cloud.ws).gte('emissao',ini).lte('emissao',fim).order('emissao',{ascending:false}).limit(5000),
   Cloud.client.from('gnre_guias').select('id,uf,tipo,referencia,notas,valor_icms,valor_fcp,total,vencimento,status,ambiente,recibo,linha_digitavel,codigo_barras,nosso_numero,motivos,payable_id,created_at').eq('workspace_id',Cloud.ws).order('created_at',{ascending:false}).limit(500)]);
  if(n.error)throw n.error;if(g.error)throw g.error;st.notas=n.data||[];st.guias=g.data||[]}
 catch(e){st.notas=st.notas||[];st.guias=st.guias||[];toast('DIFAL: '+e.message)}finally{st.carregando=false}
 if(!st.diag)gnre('diagnostico').then(d=>{st.diag=d;if(page==='difal')render()}).catch(()=>{st.diag={erro:true}});
 if(page==='difal')render()}

function kpis(){const N=st.notas.filter(x=>x.v_difal+x.v_fcp>0),soma=l=>l.reduce((s,x)=>s+Number(x.v_difal)+Number(x.v_fcp),0),pend=N.filter(x=>x.situacao==='pendente'),men=N.filter(x=>x.situacao==='mensal');
 return `<div class="grid kpis4"><div class="card kpi"><span class="kpil">DIFAL + FCP no mês</span><span class="kpiv">${money(soma(N))}</span><span class="kpis">${N.length} nota(s) · ${new Set(N.map(x=>x.uf)).size} UF(s)</span></div><div class="card kpi"><span class="kpil">Sem guia (por nota)</span><span class="kpiv ${pend.length?'gold':''}">${money(soma(pend))}</span><span class="kpis">${pend.length} nota(s)</span></div><div class="card kpi"><span class="kpil">Apuração mensal</span><span class="kpiv">${money(soma(men))}</span><span class="kpis">UFs com inscrição</span></div><div class="card kpi"><span class="kpil">Guias abertas</span><span class="kpiv">${money(st.guias.filter(g=>['rascunho','enviada','emitida'].includes(g.status)).reduce((s,g)=>s+Number(g.total),0))}</span><span class="kpis">${st.guias.filter(g=>g.status==='emitida').length} emitida(s) a pagar</span></div></div>`}
function notasView(){const q=st.notas.filter(x=>(!st.uf||x.uf===st.uf)&&(st.sit==='todas'||x.situacao===st.sit)),porUf={};
 for(const x of st.notas){if(!(x.v_difal+x.v_fcp>0))continue;const u=porUf[x.uf]||(porUf[x.uf]={n:0,d:0,f:0,p:0});u.n++;u.d+=Number(x.v_difal);u.f+=Number(x.v_fcp);if(x.situacao==='pendente')u.p+=Number(x.v_difal)+Number(x.v_fcp)}
 const sel=q.filter(x=>st.sel.has(x.chave)&&x.situacao==='pendente'),tot=sel.reduce((s,x)=>s+Number(x.v_difal)+Number(x.v_fcp),0);
 return `<div class="grid two" style="align-items:start"><section class="tablebox"><div class="tabletop"><h2>Por UF</h2><span class="caption">${Object.keys(duf()).filter(u=>duf()[u]?.ie).length?'com inscrição = apuração mensal':'sem inscrição cadastrada: tudo por nota'}</span></div><div class="tablewrap" style="max-height:420px"><table><thead><tr><th>UF</th><th>Regime</th><th class="num">Notas</th><th class="num">DIFAL</th><th class="num">FCP</th><th class="num">Sem guia</th></tr></thead><tbody>
 ${Object.entries(porUf).sort((a,b)=>(b[1].d+b[1].f)-(a[1].d+a[1].f)).map(([u,x])=>`<tr class="clickrow" data-df-uf="${u}"><td><strong>${u}</strong></td><td>${duf()[u]?.ie?'<span class="badge info">mensal · IE</span>':'por nota'}</td><td class="num">${x.n}</td><td class="num">${money(x.d)}</td><td class="num">${money(x.f)}</td><td class="num ${x.p?'gold':''}">${x.p?money(x.p):'—'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Nenhuma nota com DIFAL lida neste mês ainda. O Jarvis lê as notas do Bling a cada 2 minutos.</td></tr>'}</tbody></table></div></section>
 <section class="tablebox"><div class="tabletop"><h2>Notas</h2><div class="row"><select data-df="uf"><option value="">Todas as UFs</option>${UFS.map(u=>`<option ${st.uf===u?'selected':''}>${u}</option>`).join('')}</select><select data-df="sit">${[['pendente','Sem guia'],['guia','Em guia'],['mensal','Apuração mensal'],['ignorada','Paga por fora'],['sem_difal','Sem DIFAL'],['cancelada','Canceladas'],['todas','Todas']].map(([k,t])=>`<option value="${k}" ${st.sit===k?'selected':''}>${t}</option>`).join('')}</select></div></div>
 ${pode()&&st.sit==='pendente'?`<div class="row" style="padding:8px 12px;gap:8px;flex-wrap:wrap"><button class="primary small" data-df-preparar ${sel.length?'':'disabled'}>${icon('guia')} Preparar ${sel.length} GNRE · ${money(tot)}</button><button class="small quiet" data-df-ignorar ${sel.length?'':'disabled'}>Já pagas por fora</button></div>`:''}
 <div class="tablewrap" style="max-height:520px"><table><thead><tr>${st.sit==='pendente'?`<th style="width:28px"><input type="checkbox" class="check" data-df-todas ${sel.length&&sel.length===q.length?'checked':''} aria-label="Todas"></th>`:''}<th>Emissão</th><th>NF</th><th>UF · destinatário</th><th>Situação</th><th class="num">DIFAL</th><th class="num">FCP</th></tr></thead><tbody>
 ${q.slice(0,800).map(x=>{const [t,tom]=SIT[x.situacao]||[x.situacao,''];return `<tr>${st.sit==='pendente'?`<td><input type="checkbox" class="check" data-df-sel="${esc(x.chave)}" ${st.sel.has(x.chave)?'checked':''}></td>`:''}<td>${dBR(x.emissao)}</td><td class="mono">${esc(x.numero||'')}</td><td><strong>${esc(x.uf)}</strong> · ${esc(x.dest_nome||'')}</td><td><span class="badge ${tom}">${t}</span></td><td class="num">${money(x.v_difal)}</td><td class="num">${Number(x.v_fcp)?money(x.v_fcp):'—'}</td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Nada aqui.</td></tr>'}</tbody></table></div></section></div>`}
function guiasView(){const G=st.guias,sel=G.filter(g=>st.gsel.has(g.id)&&['rascunho','rejeitada'].includes(g.status)),d=st.diag||{},env=G.some(g=>g.status==='enviada');
 const pagos=new Map((db.payables||[]).map(p=>[p.id,p]));
 return `<div class="row" style="gap:8px;flex-wrap:wrap;margin-bottom:10px">${pode()?`<button class="primary small" data-df-enviar ${sel.length&&d.certificado?'':'disabled'} title="${d.certificado?'':'Instale o certificado A1 (Configuração)'}">${icon('send')} Enviar ${sel.length} ao Portal GNRE</button><button class="small" data-df-xml ${sel.length?'':'disabled'}>${icon('download')} XML do lote (enviar pelo site)</button>${env?`<button class="small" data-df-consultar>${icon('refresh')} Consultar resultado</button>`:''}`:''}<div style="flex:1"></div><button class="small quiet" data-df-sispag>${icon('bank')} Pagar pelo banco (SISPAG)</button></div>
 <div class="tablebox"><div class="tablewrap"><table><thead><tr><th style="width:28px"></th><th>Criada</th><th>UF · tipo</th><th>Referência</th><th>Situação</th><th>Vencimento</th><th>Linha digitável</th><th class="num">Valor</th></tr></thead><tbody>
 ${G.map(g=>{const [t,tom]=GST[g.status]||[g.status,''],p=g.payable_id&&pagos.get(g.payable_id),paga=p?.status==='pago';return `<tr><td>${['rascunho','rejeitada'].includes(g.status)?`<input type="checkbox" class="check" data-df-gsel="${esc(g.id)}" ${st.gsel.has(g.id)?'checked':''}>`:''}</td><td>${dBR(g.created_at)}</td><td><strong>${esc(g.uf)}</strong> · ${g.tipo==='mensal'?'mensal':'por nota'}</td><td class="caption">${g.tipo==='mensal'?esc(g.referencia):`NF ${esc(String(g.referencia||'').slice(25,34).replace(/^0+/,''))}`}${g.notas?.length>1?` · ${g.notas.length} notas`:''}</td>
  <td><span class="badge ${paga?'ok':tom}">${paga?'Paga':t}</span>${g.ambiente==='homologacao'&&g.status!=='rascunho'?'<br><span class="caption">homologação</span>':''}${(g.motivos||[]).length?`<br><span class="caption red">${(g.motivos||[]).map(m=>esc(`${m.codigo||''} ${m.descricao||''}${m.campo?' ('+m.campo+')':''}`)).join(' · ')}</span>`:''}</td><td>${dBR(g.vencimento)}</td>
  <td>${g.linha_digitavel?`<code class="cialinha">${esc(g.linha_digitavel)}</code> <button class="small quiet" data-df-copiar="${esc(g.linha_digitavel)}">Copiar</button>${g.payable_id?'<br><span class="caption">no contas a pagar</span>':''}`:'<span class="caption">—</span>'}${g.status==='emitida'?` <button class="small quiet" data-df-pdf="${esc(g.recibo||'')}">PDF</button>`:''}${['rascunho','rejeitada'].includes(g.status)&&pode()?` <button class="small quiet" data-df-cancelar="${esc(g.id)}">Cancelar</button>`:''}</td><td class="num">${money(g.total)}</td></tr>`}).join('')||'<tr><td colspan="8" class="empty">Nenhuma guia ainda. Prepare na aba Notas.</td></tr>'}</tbody></table></div></div>`}
function mensalView(){const ies=Object.entries(duf()).filter(([,v])=>v?.ie);if(!ies.length)return '<div class="empty">Nenhuma UF com inscrição estadual cadastrada. Sem inscrição, o DIFAL é pago por nota (aba Notas). Cadastre as UFs em Configuração.</div>';
 return `<div class="tablebox"><div class="tablewrap"><table><thead><tr><th>UF</th><th>Inscrição</th><th class="num">Notas no mês</th><th class="num">DIFAL</th><th class="num">FCP</th><th>Vencimento</th><th>Guia</th></tr></thead><tbody>
 ${ies.map(([u,v])=>{const l=st.notas.filter(x=>x.uf===u&&x.situacao==='mensal'),d=l.reduce((s,x)=>s+Number(x.v_difal),0),f=l.reduce((s,x)=>s+Number(x.v_fcp),0),g=st.guias.find(x=>x.tipo==='mensal'&&x.uf===u&&x.referencia===st.mes&&x.status!=='cancelada');
  const [a,m]=st.mes.split('-').map(Number),venc=new Date(a,m,Math.min(Number(v.dia)||10,28)).toLocaleDateString('pt-BR');
  return `<tr><td><strong>${u}</strong></td><td class="mono">${esc(v.ie)}</td><td class="num">${l.length}</td><td class="num">${money(d)}</td><td class="num">${money(f)}</td><td>${venc}</td><td>${g?`<span class="badge ${(GST[g.status]||[])[1]||''}">${(GST[g.status]||[g.status])[0]}</span>`:pode()&&l.length?`<button class="small primary" data-df-mensal="${u}">Gerar guia do mês</button>`:'—'}</td></tr>`}).join('')}</tbody></table></div></div>`}
function configView(){const c=fcfg(),e=c.emitente||{},d=st.diag||{},D=duf();
 const passos=[[true,'Notas de venda lidas do Bling a cada 2 minutos (DIFAL e FCP de cada nota).'],[!!(e.endereco&&e.ibge&&e.cep),'Dados do emitente para a guia (abaixo).'],[!!d.certificado,'Certificado A1 instalado no servidor: rode <code>ops\\gravar-certificado-gnre.ps1</code> (escolhe o .pfx e digita a senha escondida).'],[false,'Acesso ao webservice liberado no Portal GNRE (www.gnre.pe.gov.br › Área do contribuinte › Solicitar acesso ao webservice, com o mesmo certificado).'],[d.ambiente==='producao','Testado em homologação e trocado para produção (<code>ops\\gravar-certificado-gnre.ps1 -Producao</code>).']];
 return `<section class="card"><h3>Para gerar e transmitir as guias</h3><ol class="checklist">${passos.map(([ok,t])=>`<li class="${ok?'ok':''}">${ok?icon('check'):''} ${t}</li>`).join('')}</ol><p class="caption">Servidor: certificado ${d.certificado?'<span class="green">instalado</span>':'<span class="red">não instalado</span>'} · TLS com certificado ${d.cliente_tls?'disponível':'indisponível'} · ambiente GNRE: <strong>${esc(d.ambiente||'—')}</strong>. Sem certificado dá para baixar o XML do lote e enviar pelo site do portal.</p></section>
 <section class="card"><h3>Emitente na guia</h3><div class="grid three"><div style="grid-column:span 2"><label for="dfEnd">Endereço</label><input id="dfEnd" data-df-em="endereco" value="${esc(e.endereco||'')}" placeholder="Rua, número, bairro"></div><div><label for="dfCep">CEP</label><input id="dfCep" data-df-em="cep" value="${esc(e.cep||'')}"></div><div><label for="dfIbge">Código IBGE do município</label><input id="dfIbge" data-df-em="ibge" value="${esc(e.ibge||'')}" placeholder="7 dígitos (Timbó: 4218202)"></div><div><label for="dfTel">Telefone</label><input id="dfTel" data-df-em="telefone" value="${esc(e.telefone||'')}"></div><div><label for="dfRaz">Razão social</label><input id="dfRaz" data-df-em="razao" value="${esc(e.razao||c.razao||'')}"></div></div></section>
 <section class="card"><h3>UFs com inscrição estadual (DIFAL mensal)</h3><p class="caption">Nas UFs em que a empresa é inscrita, o DIFAL de todas as notas do mês vira uma guia só, no dia de vencimento da UF. Nas demais, uma guia por nota. Marque "FCP separado" se a UF exigir o FCP na receita 100129.</p>
 <div class="tablewrap"><table><thead><tr><th>UF</th><th>Inscrição estadual</th><th>Dia do vencimento</th><th>FCP separado</th><th></th></tr></thead><tbody>${UFS.filter(u=>u!==(c.uf||'SC')).map(u=>{const v=D[u]||{};return `<tr><td><strong>${u}</strong></td><td><input class="ufin" data-df-ie="${u}" value="${esc(v.ie||'')}" placeholder="—" style="width:150px"></td><td><input class="ufin" type="number" min="1" max="31" data-df-dia="${u}" value="${esc(v.dia||'')}" placeholder="10" style="width:70px"></td><td><input type="checkbox" class="check" data-df-fcp="${u}" ${v.fcp_separado?'checked':''}></td><td>${d.certificado?`<button class="small quiet" data-df-cfg="${u}">Ler exigências</button>`:''}</td></tr>`}).join('')}</tbody></table></div></section>
 <section class="card"><h3>Leitura das notas</h3><p class="caption">O Jarvis começa no dia 1º do mês em que foi ligado e segue sozinho. Para reler desde outra data:</p><div class="row"><input type="date" id="dfDesde" value="${st.mes}-01"><button class="small" data-df-ler>${icon('refresh')} Ler notas desde esta data</button></div></section>`}
function view(){if(!st.notas){carregar();return '<div class="empty">Carregando…</div>'}
 const A=[['notas','Notas'],['guias',`Guias (${st.guias.filter(g=>['rascunho','enviada','emitida','rejeitada'].includes(g.status)).length})`],['mensal','Apuração mensal'],['config','Configuração']];
 return `<div class="crmbar"><div class="segtabs">${A.map(([k,t])=>`<button class="${st.aba===k?'active':''}" data-df-aba="${k}">${t}</button>`).join('')}</div><div style="flex:1"></div><input type="month" data-df="mes" value="${st.mes}"></div>${kpis()}${({notas:notasView,guias:guiasView,mensal:mensalView,config:configView}[st.aba]||notasView)()}`}

const recarregar=()=>{st.notas=null;st.guias=null;carregar()};
document.addEventListener('click',async e=>{const b=e.target.closest('[data-df-aba],[data-df-uf],[data-df-preparar],[data-df-ignorar],[data-df-enviar],[data-df-xml],[data-df-consultar],[data-df-copiar],[data-df-pdf],[data-df-cancelar],[data-df-mensal],[data-df-cfg],[data-df-ler],[data-df-sispag]');if(!b)return;const d=b.dataset;
 if(d.dfAba){st.aba=d.dfAba;render();return}
 if(d.dfUf){st.uf=d.dfUf;st.sit='todas';render();return}
 if(d.dfSispag!=null)return navigate('sispag');
 if(d.dfCopiar){try{await navigator.clipboard.writeText(d.dfCopiar);toast('Linha digitável copiada.')}catch{toast(d.dfCopiar)}return}
 b.disabled=true;
 try{
  if(d.dfPreparar!=null){const ch=[...st.sel];const r=await gnre('preparar',{chaves:ch});st.sel.clear();toast(`${r.guias.length} guia(s) preparada(s)${r.guias.length<ch.length?` · ${ch.length-r.guias.length} nota(s) cancelada(s) no Bling ficaram de fora`:''}.`);st.aba='guias';recarregar();return}
  if(d.dfIgnorar!=null){if(b.dataset.conf!=='1'){b.disabled=false;b.dataset.conf='1';b.textContent=`Confirmar: ${st.sel.size} já paga(s) fora do Jarvis`;b.classList.add('danger');return}
   const {error}=await Cloud.client.from('difal_notas').update({situacao:'ignorada',updated_at:new Date().toISOString()}).eq('workspace_id',Cloud.ws).in('chave',[...st.sel]).eq('situacao','pendente');if(error)throw error;audit('DIFAL: notas marcadas como pagas fora do Jarvis',`${st.sel.size} nota(s)`);st.sel.clear();recarregar();return}
  if(d.dfEnviar!=null){if(b.dataset.conf!=='1'){b.disabled=false;b.dataset.conf='1';b.textContent=`Confirmar envio (${st.diag?.ambiente==='producao'?'PRODUÇÃO':'homologação'})`;b.classList.add('danger');return}
   const r=await gnre('enviar',{ids:[...st.gsel]});st.gsel.clear();toast(`Lote ${r.recibo} enviado (${r.guias} guia(s)). O portal processa em alguns segundos.`);setTimeout(async()=>{try{await gnre('consultar');recarregar()}catch{}},15000);recarregar();return}
  if(d.dfXml!=null){const r=await gnre('xml',{ids:[...st.gsel]});download(`gnre-lote-${hoje()}.xml`,r.xml,'application/xml');toast(`XML com ${r.guias} guia(s). Envie em www.gnre.pe.gov.br › Lote de GNRE.`);b.disabled=false;return}
  if(d.dfConsultar!=null){const r=await gnre('consultar');const em=r.resultado.filter(x=>x.status==='emitida').length,rj=r.resultado.filter(x=>x.status==='rejeitada').length;toast(em||rj?`${em} emitida(s) e lançada(s) no contas a pagar${rj?` · ${rj} rejeitada(s)`:''}.`:'O portal ainda está processando.');if(em)await window.Cloud?.reload?.();recarregar();return}
  if(d.dfPdf!=null){const {data,error}=await Cloud.client.from('gnre_guias').select('pdf_base64').eq('workspace_id',Cloud.ws).eq('recibo',d.dfPdf).not('pdf_base64','is',null).limit(1);if(error)throw error;const p=data?.[0]?.pdf_base64;if(!p){b.disabled=false;return toast('O portal não devolveu o PDF deste lote.')}
   const bin=Uint8Array.from(atob(p),c=>c.charCodeAt(0));download(`gnre-${d.dfPdf}.pdf`,bin,'application/pdf');b.disabled=false;return}
  if(d.dfCancelar){await gnre('cancelar_rascunho',{id:d.dfCancelar});st.gsel.delete(d.dfCancelar);recarregar();return}
  if(d.dfMensal){const r=await gnre('preparar',{mensal:{uf:d.dfMensal,mes:st.mes}});toast(`Guia mensal de ${d.dfMensal} preparada: ${money(r.guias[0]?.total||0)}.`);st.aba='guias';recarregar();return}
  if(d.dfCfg){const r=await gnre('config_uf',{uf:d.dfCfg});modal(`Exigências de ${d.dfCfg} (receita 100102)`,`<pre style="white-space:pre-wrap;font-size:12px">${esc(JSON.stringify(r,null,1))}</pre><div class="modalfoot"><button class="primary" data-action="close">Fechar</button></div>`);b.disabled=false;return}
  if(d.dfLer!=null){const desde=$('#dfDesde').value;const r=await integ('difal_sync',{desde});toast(`${r.lidas} nota(s) lida(s) · ${r.com_difal} com DIFAL. O restante segue pelo cron.`);recarregar();return}
 }catch(x){b.disabled=false;toast(x.message)}});
document.addEventListener('change',e=>{const x=e.target;
 if(x.matches('[data-df="mes"]')){if(/^\d{4}-\d{2}$/.test(x.value)){st.mes=x.value;st.sel.clear();recarregar()}return}
 if(x.matches('[data-df="uf"]')){st.uf=x.value;render();return}
 if(x.matches('[data-df="sit"]')){st.sit=x.value;st.sel.clear();render();return}
 if(x.matches('[data-df-sel]')){x.checked?st.sel.add(x.dataset.dfSel):st.sel.delete(x.dataset.dfSel);render();return}
 if(x.matches('[data-df-todas]')){const q=st.notas.filter(n=>(!st.uf||n.uf===st.uf)&&n.situacao==='pendente');if(x.checked)q.forEach(n=>st.sel.add(n.chave));else st.sel.clear();render();return}
 if(x.matches('[data-df-gsel]')){x.checked?st.gsel.add(x.dataset.dfGsel):st.gsel.delete(x.dataset.dfGsel);render();return}
 if(x.matches('[data-df-em]')){salvarFiscal({emitente:{...(fcfg().emitente||{}),[x.dataset.dfEm]:x.value.trim()}});toast('Salvo.');return}
 const u=x.dataset.dfIe||x.dataset.dfDia||x.dataset.dfFcp;if(u){const D={...duf()},v={...(D[u]||{})};if(x.dataset.dfIe)v.ie=x.value.replace(/[^\dA-Za-z]/g,'');else if(x.dataset.dfDia)v.dia=Number(x.value)||null;else v.fcp_separado=x.checked;
  if(!v.ie&&!v.fcp_separado&&!v.dia)delete D[u];else D[u]=v;salvarFiscal({difal_uf:D});if(x.dataset.dfIe&&window.Cloud?.client)Cloud.client.from('difal_notas').update({situacao:v.ie?'mensal':'pendente',updated_at:new Date().toISOString()}).eq('workspace_id',Cloud.ws).eq('uf',u).eq('situacao',v.ie?'pendente':'mensal').then(()=>recarregar());audit('DIFAL: configuração da UF',`${u} · ${v.ie?'IE '+v.ie:'sem IE'}`);toast(`${u} salvo. ${v.ie?'Notas novas dessa UF entram na apuração mensal.':''}`)}});
addPage('difal','guia','DIFAL e GNRE',view,'DIFAL e FCP de cada nota lidos do Bling, guias GNRE por nota ou mensais pelo webservice do portal, e pagamento pelo arquivo do banco.','',()=>{});
window.Difal={carregar,avisos:()=>{const p=(st.notas||[]).filter(x=>x.situacao==='pendente');return p.length?[['warn','guia',`${p.length} nota(s) com DIFAL sem guia`,money(p.reduce((s,x)=>s+Number(x.v_difal)+Number(x.v_fcp),0)),'difal']]:[]}};
})();
