'use strict';
// Fiscal › DIFAL e GNRE. O DIFAL/FCP de cada nota de venda é lido do XML autorizado no Bling (cron a cada 2 min).
// UF sem inscrição estadual: uma GNRE por nota, antes da mercadoria sair. UF com inscrição: apuração no mês e uma guia
// mensal. As guias saem em lote pelo webservice do Portal GNRE com o certificado A1 (ou em XML para enviar pelo site),
// voltam com linha digitável e PDF, viram título no contas a pagar e são pagas pelo arquivo do banco (SISPAG, forma 91).
(()=>{
Object.assign(paths,{guia:'M5 3h14v18H5z M8 7h8 M8 11h8 M8 15h5 M15 17l1.5 1.5L19 16'});
const UFS=['AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO'];
const dBR=d=>d?new Date(String(d).slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const hoje=()=>new Date().toLocaleDateString('sv-SE');
const SIT={pendente:['Sem guia','warn'],mensal:['Apuração mensal','info'],guia:['Em guia','ok'],paga:['Paga','ok'],sem_difal:['Sem DIFAL',''],cancelada:['Nota cancelada',''],ignorada:['Paga por fora','']};
const GST={rascunho:['Rascunho','info'],enviada:['Enviada · aguardando portal','warn'],emitida:['Emitida','ok'],rejeitada:['Rejeitada','bad'],paga:['Paga','ok'],cancelada:['Cancelada','']};
const st={gf:{},gfAberto:null,gfBusca:'',gfTmp:new Set(),gVis:[],aba:'notas',dia:'',mesCarregado:null,ufs:new Set(),ufAberto:false,sit:'pendente',notas:null,guias:null,diag:null,carregando:false,sel:new Set(),gsel:new Set(),pag:(()=>{try{return localStorage.getItem('eb_gnre_pag')||'auto'}catch{return 'auto'}})(),pagData:''};
window.Reiniciar?.registrar(st,['aba','dia','ufs','ufAberto','sit','sel','gsel','gf','gfAberto','gfBusca']); // estado de tela: volta ao original ao clicar no menu
// Data de pagamento do lote (mesma regra do servidor, _shared/gnre_regras.ts): automática = dia útil seguinte à emissão
// da nota (sexta, sábado e domingo → segunda; feriados nacionais pulados); ou uma data fixa para todas. Nunca antes de hoje.
const somaDias=(iso,n)=>{const d=new Date(iso.slice(0,10)+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
function pascoa(ano){const a=ano%19,b=Math.floor(ano/100),c=ano%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mes=Math.floor((h+l-7*m+114)/31),dia=((h+l-7*m+114)%31)+1;return `${ano}-${String(mes).padStart(2,'0')}-${String(dia).padStart(2,'0')}`}
const feriado=iso=>{const p=pascoa(Number(iso.slice(0,4)));return ['01-01','04-21','05-01','09-07','10-12','11-02','11-15','11-20','12-25'].includes(iso.slice(5,10))||[-48,-47,-2,60].some(n=>somaDias(p,n)===iso.slice(0,10))};
const diaUtil=iso=>{const w=new Date(iso.slice(0,10)+'T12:00:00Z').getUTCDay();return w!==0&&w!==6&&!feriado(iso)};
function diaUtilSeguinte(iso){let d=somaDias(iso,1);while(!diaUtil(d))d=somaDias(d,1);return d}
function dataPagamento(g,h,opc={}){const alvo=opc.modo==='fixa'&&/^\d{4}-\d{2}-\d{2}$/.test(String(opc.data||''))?String(opc.data):g.tipo==='nota'&&g.emissao?diaUtilSeguinte(g.emissao):g.vencimento;return alvo<h?h:alvo}
const emissaoDe=g=>g.tipo==='nota'?(st.notas||[]).find(n=>n.chave===g.notas?.[0])?.emissao||null:null;
const opcPag=()=>({modo:st.pag,data:st.pag==='fixa'?st.pagData:null});
const fcfg=()=>window.Parametros?.cfg?.()||db.gerencial?.fiscal||{};
const duf=()=>fcfg().difal_uf||{};
const salvarFiscal=n=>{db.gerencial={...(db.gerencial||{}),fiscal:{...(db.gerencial?.fiscal||{}),...n}};save()};
const pode=()=>['owner','member','financeiro'].includes(window.Cloud?.role||'owner');
async function gnre(action,body={}){const r=await Cloud.client.functions.invoke('gnre',{body:{workspace_id:Cloud.ws,action,...body}});if(r.error){let msg=r.error.message;try{msg=(await r.error.context.json()).error||msg}catch{}throw Error(msg)}return r.data}
async function integ(action,body={}){const r=await Cloud.client.functions.invoke('integrations',{body:{workspace_id:Cloud.ws,action,...body}});if(r.error){let msg=r.error.message;try{msg=(await r.error.context.json()).error||msg}catch{}throw Error(msg)}return r.data}

async function carregar(){if(st.carregando||!window.Cloud?.client)return;st.carregando=true;
 try{st.mesCarregado=month;const [ay,am]=month.split('-').map(Number),ini=`${month}-01`,fim=`${month}-${String(new Date(ay,am,0).getDate()).padStart(2,'0')}`; // último dia real do mês
  const [n,g]=await Promise.all([Cloud.client.from('difal_notas').select('chave,numero,serie,emissao,uf,dest_nome,dest_doc,valor_nota,v_difal,v_fcp,situacao,guia_id').eq('workspace_id',Cloud.ws).gte('emissao',ini).lte('emissao',fim).order('emissao',{ascending:false}).limit(5000),
   Cloud.client.from('gnre_guias').select('id,uf,tipo,referencia,notas,valor_icms,valor_fcp,total,vencimento,status,ambiente,recibo,linha_digitavel,codigo_barras,nosso_numero,motivos,payable_id,created_at,retorno').eq('workspace_id',Cloud.ws).order('created_at',{ascending:false}).limit(500)]);
  if(n.error)throw n.error;if(g.error)throw g.error;st.notas=n.data||[];st.guias=g.data||[]}
 catch(e){st.notas=st.notas||[];st.guias=st.guias||[];toast('DIFAL: '+e.message)}finally{st.carregando=false}
 if(!st.diag)gnre('diagnostico').then(d=>{st.diag=d;if(page==='difal')render()}).catch(()=>{st.diag={erro:true}});
 if(page==='difal')render()}

const noDia=x=>!st.dia||x.emissao===st.dia;
function kpis(){const N=st.notas.filter(x=>x.v_difal+x.v_fcp>0&&noDia(x)),soma=l=>l.reduce((s,x)=>s+Number(x.v_difal)+Number(x.v_fcp),0),pend=N.filter(x=>x.situacao==='pendente'),men=N.filter(x=>x.situacao==='mensal');
 return `<div class="grid kpis4"><div class="card kpi"><span class="kpil">DIFAL + FCP ${st.dia?`em ${new Date(st.dia+"T12:00").toLocaleDateString("pt-BR")}`:"no mês"}</span><span class="kpiv">${money(soma(N))}</span><span class="kpis">${N.length} nota(s) · ${new Set(N.map(x=>x.uf)).size} UF(s)</span></div><div class="card kpi"><span class="kpil">Sem guia (por nota)</span><span class="kpiv ${pend.length?'gold':''}">${money(soma(pend))}</span><span class="kpis">${pend.length} nota(s)</span></div><div class="card kpi"><span class="kpil">Apuração mensal</span><span class="kpiv">${money(soma(men))}</span><span class="kpis">UFs com inscrição</span></div><div class="card kpi"><span class="kpil">Guias abertas</span><span class="kpiv">${money(st.guias.filter(g=>['rascunho','enviada','emitida'].includes(g.status)).reduce((s,g)=>s+Number(g.total),0))}</span><span class="kpis">${st.guias.filter(g=>g.status==='emitida').length} emitida(s) a pagar</span></div></div>`}
// Estados: um ou mais (caixas de seleção); nenhum marcado = todos. Mostra quantas notas há em cada UF na visão atual.
function ufSeletor(){const cont={};for(const x of st.notas)if(noDia(x)&&(st.sit==='todas'||x.situacao===st.sit))cont[x.uf]=(cont[x.uf]||0)+1;
 const rot=!st.ufs.size?'Todas as UFs':st.ufs.size<=4?[...st.ufs].sort().join(', '):`${st.ufs.size} UFs`;
 return `<details class="ufsel" ${st.ufAberto?'open':''}><summary>${esc(rot)}</summary><div class="ufsel-painel"><label class="ufsel-todas"><input type="checkbox" class="check" data-df-uftodas ${st.ufs.size?'':'checked'}> Todas as UFs</label><div class="ufsel-grade">${UFS.map(u=>`<label class="${cont[u]?'':'muted'}"><input type="checkbox" class="check" data-df-ufchk="${u}" ${st.ufs.has(u)?'checked':''}> ${u}${cont[u]?` <small>${cont[u]}</small>`:''}</label>`).join('')}</div></div></details>`}
function notasView(){const q=st.notas.filter(x=>noDia(x)&&(!st.ufs.size||st.ufs.has(x.uf))&&(st.sit==='todas'||x.situacao===st.sit)),porUf={};
 for(const x of st.notas){if(!(x.v_difal+x.v_fcp>0)||!noDia(x))continue;const u=porUf[x.uf]||(porUf[x.uf]={n:0,d:0,f:0,p:0});u.n++;u.d+=Number(x.v_difal);u.f+=Number(x.v_fcp);if(x.situacao==='pendente')u.p+=Number(x.v_difal)+Number(x.v_fcp)}
 const sel=q.filter(x=>st.sel.has(x.chave)&&x.situacao==='pendente'),tot=sel.reduce((s,x)=>s+Number(x.v_difal)+Number(x.v_fcp),0);
 return `<div class="grid two" style="align-items:start"><section class="tablebox"><div class="tabletop"><h2>Por UF</h2><span class="caption">${Object.keys(duf()).filter(u=>duf()[u]?.ie).length?'com inscrição = apuração mensal':'sem inscrição cadastrada: tudo por nota'}</span></div><div class="tablewrap" style="max-height:420px"><table><thead><tr><th>UF</th><th>Regime</th><th class="num">Notas</th><th class="num">DIFAL</th><th class="num">FCP</th><th class="num">Sem guia</th></tr></thead><tbody>
 ${Object.entries(porUf).sort((a,b)=>(b[1].d+b[1].f)-(a[1].d+a[1].f)).map(([u,x])=>`<tr class="clickrow" data-df-uf="${u}"><td><strong>${u}</strong></td><td>${duf()[u]?.ie?'<span class="badge info">mensal · IE</span>':'por nota'}</td><td class="num">${x.n}</td><td class="num">${money(x.d)}</td><td class="num">${money(x.f)}</td><td class="num ${x.p?'gold':''}">${x.p?money(x.p):'—'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Nenhuma nota com DIFAL lida neste mês ainda. O Jarvis lê as notas do Bling a cada 2 minutos.</td></tr>'}</tbody></table></div></section>
 <section class="tablebox"><div class="tabletop"><h2>Notas</h2><div class="row">${ufSeletor()}<select data-df="sit">${[['pendente','Sem guia'],['guia','Em guia'],['mensal','Apuração mensal'],['ignorada','Paga por fora'],['sem_difal','Sem DIFAL'],['cancelada','Canceladas'],['todas','Todas']].map(([k,t])=>`<option value="${k}" ${st.sit===k?'selected':''}>${t}</option>`).join('')}</select></div></div>
 ${pode()&&st.sit==='pendente'?`<div class="row" style="padding:8px 12px;gap:8px;flex-wrap:wrap"><button class="primary small" data-df-preparar ${sel.length?'':'disabled'}>${icon('guia')} Preparar ${sel.length} GNRE · ${money(tot)}</button><button class="small quiet" data-df-ignorar ${sel.length?'':'disabled'}>Já pagas por fora</button></div>`:''}
 <div class="tablewrap" style="max-height:520px"><table><thead><tr>${st.sit==='pendente'?`<th style="width:28px"><input type="checkbox" class="check" data-df-todas ${sel.length&&sel.length===q.length?'checked':''} aria-label="Todas"></th>`:''}<th>Emissão</th><th>NF</th><th>UF · destinatário</th><th>Situação</th><th class="num">DIFAL</th><th class="num">FCP</th></tr></thead><tbody>
 ${q.slice(0,800).map(x=>{const [t,tom]=SIT[x.situacao]||[x.situacao,''];return `<tr>${st.sit==='pendente'?`<td><input type="checkbox" class="check" data-df-sel="${esc(x.chave)}" ${st.sel.has(x.chave)?'checked':''}></td>`:''}<td>${dBR(x.emissao)}</td><td class="mono" data-exp-num="${Number(String(x.numero||'').replace(/\D/g,''))||''}">${esc(x.numero||'')}</td><td><strong>${esc(x.uf)}</strong> · ${esc(x.dest_nome||'')}</td><td><span class="badge ${tom}">${t}</span></td><td class="num">${money(x.v_difal)}</td><td class="num">${Number(x.v_fcp)?money(x.v_fcp):'—'}</td></tr>`}).join('')||`<tr><td colspan="7" class="empty">${st.ufs.size?`Nenhuma nota ${{pendente:'sem guia',guia:'em guia',mensal:'na apuração mensal',ignorada:'paga por fora',sem_difal:'sem DIFAL',cancelada:'cancelada'}[st.sit]||''} para ${[...st.ufs].sort().join(', ')} neste período. <button class="small" data-df-uflimpar>Mostrar todas as UFs</button>`:'Nada aqui.'}</td></tr>`}</tbody></table></div></section></div>`}
// Rejeição: falha temporária do portal ou da SEFAZ (404 "enviar o lote novamente", 7xx comunicação) é só reenviar;
// recusa de dado da guia precisa de correção antes. Guia rejeitada no teste (homologação) pode ir para produção.
const TEMPORARIA=/novamente|comunica|indispon|tempor|timeout|time-out|sobrecarg/i;
function rejeicao(g){if(g.status!=='rejeitada')return null;const ms=g.motivos||[];
 if(ms.length&&ms.every(m=>/^(404|7\d\d|999)$/.test(String(m.codigo||''))||TEMPORARIA.test(m.descricao||'')))return {tipo:'temp',txt:'Falha temporária do portal ou da SEFAZ da UF: é só reenviar.'};
 if(g.ambiente==='homologacao')return {tipo:'teste',txt:'Rejeitada no teste: pode enviar em produção.'};
 return {tipo:'dado',txt:'A UF recusou um dado da guia: confira a Configuração (CEP por estado, inscrições) e reenvie. Se repetir, avise o suporte.'}}
// ─────────── Aba Guias: filtro por coluna, como no Excel ───────────
// Cada coluna lista os valores que aparecem nas guias (já filtradas pelas outras colunas), com busca e "selecionar
// tudo". Coluna sem filtro = todos os valores. O "marcar todas" e o envio valem só para as guias que estão à vista.
const GCOLS=[['criada','Criada'],['uf','UF · tipo'],['ref','Referência'],['sit','Situação'],['pag','Vencimento / pagamento'],['linha','Linha digitável'],['valor','Valor']];
const GSIT_EXTRA=g=>g.ambiente==='homologacao'&&g.status!=='rascunho'?' (teste)':'';
function valoresGuia(g,pagos){const [t]=GST[g.status]||[g.status],p=g.payable_id&&pagos.get(g.payable_id),pend=['rascunho','rejeitada'].includes(g.status);
 const pag=pend?dataPagamento({tipo:g.tipo,emissao:emissaoDe(g),vencimento:g.vencimento},hoje(),opcPag()):g.vencimento;
 return {criada:dBR(g.created_at),uf:`${g.uf} · ${g.tipo==='mensal'?'mensal':'por nota'}`,ref:g.tipo==='mensal'?String(g.referencia||''):`NF ${String(g.referencia||'').slice(25,34).replace(/^0+/,'')}`,
  sit:(p?.status==='pago'?'Paga':t)+GSIT_EXTRA(g),pag:pag?dBR(pag):'—',linha:g.linha_digitavel?'Com linha digitável':'Sem linha digitável',valor:money(g.total)}}
const chaveOrdem=v=>{const d=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(v);if(d)return d[3]+d[2]+d[1];const n=/^R\$/.test(v)?Number(v.replace(/[^\d,]/g,'').replace(',','.')):NaN;return isNaN(n)?v:String(n.toFixed(2)).padStart(14,'0')};
const passa=(v,ex)=>Object.entries(st.gf).every(([c,set])=>c===ex||!set||set.has(v[c]));
function painelFiltro(c,linhas){const outros=linhas.filter(x=>passa(x.v,c)),cont=new Map();for(const x of outros)cont.set(x.v[c],(cont.get(x.v[c])||0)+1);
 const q=normalized(st.gfBusca||''),vals=[...cont.keys()].sort((a,b)=>chaveOrdem(a).localeCompare(chaveOrdem(b),'pt-BR',{numeric:true})),vis=vals.filter(v=>!q||normalized(v).includes(q)),set=st.gf[c],busca=!!q,marc=v=>busca?st.gfTmp.has(v):!set||set.has(v);st.gfVals=vals;st.gfVis=vis;
 return `<div class="gfpainel" role="dialog" aria-label="Filtrar coluna" style="visibility:hidden"><input type="search" class="gfbusca" data-df-gfbusca placeholder="Pesquisar" value="${esc(st.gfBusca||'')}">
  <label class="gftudo"><input type="checkbox" class="check" data-df-gftudo ${vis.every(marc)?'checked':''}> (Selecionar tudo${q?' o que foi encontrado':''})</label>
  <div class="gflista">${vis.map(v=>`<label><input type="checkbox" class="check" data-df-gfval="${esc(v)}" ${marc(v)?'checked':''}> <span>${esc(v)}</span> <small>${cont.get(v)}</small></label>`).join('')||'<p class="caption">Nada encontrado.</p>'}</div>
  <div class="row" style="justify-content:space-between;gap:6px;margin-top:8px">${set?'<button class="small quiet" data-df-gflimpar>Limpar filtro</button>':'<span></span>'}<button class="small primary" data-df-gffechar>OK</button></div></div>`}
function cabecalhoFiltro(linhas){setTimeout(posicionarGf,0);return GCOLS.map(([c,t])=>`<th class="gfth${c==='valor'?' num':''}"><span class="gfrot">${t}<button class="gfbtn${st.gf[c]?' on':''}" data-df-gf="${c}" aria-label="Filtrar ${t}" title="${st.gf[c]?'Filtro ativo':'Filtrar'}">${st.gf[c]?'⧩':'▾'}</button></span>${st.gfAberto===c?painelFiltro(c,linhas):''}</th>`).join('')}
document.addEventListener('click',e=>{const t=e.target;
 const b=t.closest('[data-df-gf]');if(b){e.preventDefault();const c=b.dataset.dfGf;if(st.gfAberto===c){st.gfAberto=null}else{st.gfAberto=c;st.gfBusca=''}render();return}
 if(t.closest('[data-df-gffechar]')){const c=st.gfAberto;if(st.gfBusca.trim()){const set=new Set([...st.gfTmp].filter(v=>st.gfVis.includes(v)));st.gf[c]=set;st.gfBusca=''}st.gfAberto=null;render();return}
 if(t.closest('[data-df-gflimpar]')){delete st.gf[st.gfAberto];render();return}
 if(t.closest('[data-df-gflimpartodos]')){st.gf={};st.gfAberto=null;render();return}
 if(st.gfAberto&&!t.closest('.gfpainel')){st.gfAberto=null;document.querySelectorAll('body > .gfpainel').forEach(x=>x.remove());if(page==='difal')render()}});
document.addEventListener('change',e=>{const x=e.target,c=st.gfAberto;if(!c)return;
 if(x.matches('[data-df-gfval]')&&st.gfBusca.trim()){const v=x.dataset.dfGfval;x.checked?st.gfTmp.add(v):st.gfTmp.delete(v);render();return}
 if(x.matches('[data-df-gftudo]')&&st.gfBusca.trim()){st.gfTmp=x.checked?new Set(st.gfVis):new Set();render();return}
 if(x.matches('[data-df-gfval]')){const v=x.dataset.dfGfval,set=new Set(st.gf[c]??st.gfVals);x.checked?set.add(v):set.delete(v);st.gf[c]=st.gfVals.every(y=>set.has(y))?undefined:set;if(!st.gf[c])delete st.gf[c];render();return}
 if(x.matches('[data-df-gftudo]')){if(x.checked)delete st.gf[c];else st.gf[c]=new Set();render()}});
document.addEventListener('input',e=>{const x=e.target;if(!x.matches?.('[data-df-gfbusca]'))return;st.gfBusca=x.value;
 // Cada busca nova começa com todos os encontrados marcados.
 const q=normalized(x.value);st.gfTmp=new Set((st.gfVals||[]).filter(v=>!q||normalized(v).includes(q)));render()});
// O painel fica fixo na tela, logo abaixo do botão da coluna: posicionado depois de cada desenho e ao rolar a página.
// O quadro tem animação (transform), que prenderia o painel dentro dele: o painel vai para o corpo da página.
function posicionarGf(){const novo=document.querySelector('#view .gfpainel');document.querySelectorAll('body > .gfpainel').forEach(x=>{if(novo||!st.gfAberto)x.remove()});
 if(novo){document.body.appendChild(novo);const i=novo.querySelector('[data-df-gfbusca]');if(i){i.focus();const n=i.value.length;i.setSelectionRange(n,n)}}
 const p=document.querySelector('body > .gfpainel'),b=st.gfAberto&&document.querySelector(`[data-df-gf="${st.gfAberto}"]`);if(!p||!b)return;const r=b.getBoundingClientRect();
 if(r.bottom<0||r.top>innerHeight){st.gfAberto=null;render();return}
 p.style.left=Math.max(8,Math.min(r.right-p.offsetWidth,innerWidth-p.offsetWidth-8))+'px';p.style.top=Math.max(8,Math.min(r.bottom+4,innerHeight-p.offsetHeight-8))+'px';p.style.visibility='visible'}
document.addEventListener('scroll',e=>{if(st.gfAberto&&!e.target.closest?.('.gfpainel'))posicionarGf()},{passive:true,capture:true});
addEventListener('resize',()=>st.gfAberto&&posicionarGf());
function guiasView(){const d0=st.diag||{},testes=d0.ambiente==='producao'?st.guias.filter(g=>g.ambiente==='homologacao'&&['emitida','enviada'].includes(g.status)):[];
 // Em produção, as guias de TESTE emitidas na homologação (não se pagam) ficam escondidas, com botão para mostrar.
 const G0=st.verTestes?st.guias:st.guias.filter(g=>!testes.includes(g)),pagos=new Map((db.payables||[]).map(p=>[p.id,p]));
 const linhas=G0.map(g=>({g,v:valoresGuia(g,pagos)})),G=linhas.filter(x=>passa(x.v)).map(x=>x.g),filtrando=Object.values(st.gf).some(Boolean);
 // Guia escondida pelo filtro sai da seleção: o envio leva só o que está à vista.
 st.gVis=G.map(g=>g.id);for(const id of [...st.gsel])if(!st.gVis.includes(id))st.gsel.delete(id);
 const sel=G.filter(g=>st.gsel.has(g.id)&&['rascunho','rejeitada'].includes(g.status)),d=st.diag||{},env=G.some(g=>g.status==='enviada');
 return `<div class="row" style="gap:8px;flex-wrap:wrap;margin-bottom:10px">${pode()?`<button class="primary small" data-df-enviar ${sel.length&&d.certificado?'':'disabled'} title="${d.certificado?'':'Instale o certificado A1 (Configuração)'}">${icon('send')} Enviar ${sel.length} ao Portal GNRE</button><button class="small" data-df-xml ${sel.length?'':'disabled'}>${icon('download')} XML do lote (enviar pelo site)</button>
 <label class="row" style="gap:6px;align-items:center;font-weight:400">Pagamento <select data-df-pagmodo aria-label="Data de pagamento do lote"><option value="auto" ${st.pag!=='fixa'?'selected':''}>Dia útil seguinte à emissão</option><option value="fixa" ${st.pag==='fixa'?'selected':''}>Mesma data para todas</option></select>${st.pag==='fixa'?`<input type="date" data-df-pagdata min="${hoje()}" value="${esc(st.pagData||hoje())}">`:''}</label>${env?`<button class="small" data-df-consultar>${icon('refresh')} Consultar resultado</button>`:''}`:''}<div style="flex:1"></div>${pode()&&G.some(g=>rejeicao(g)?.tipo==='temp')?`<button class="small" data-df-temporarias title="Rejeitadas por falha do portal ou da SEFAZ: basta reenviar">${icon('refresh')} Selecionar as ${G.filter(g=>rejeicao(g)?.tipo==='temp').length} com falha temporária</button>`:''}${pode()&&G.some(g=>['rascunho','rejeitada'].includes(g.status))?`<button class="small" data-df-prontas>${icon('check')} Selecionar as ${G.filter(g=>['rascunho','rejeitada'].includes(g.status)).length} prontas</button>`:''}${testes.length?`<button class="small quiet" data-df-testes>${st.verTestes?'Ocultar':'Mostrar'} ${testes.length} guia(s) de teste</button>`:''}<button class="small quiet" data-df-sispag>${icon('bank')} Pagar pelo banco (SISPAG)</button></div>
 ${filtrando?`<div class="notice" style="display:flex;gap:10px;align-items:center;flex-wrap:wrap;padding:8px 12px">Filtro ativo: ${G.length} de ${G0.length} guia(s) · ${money(G.reduce((x,g)=>x+Number(g.total),0))} <button class="small quiet" data-df-gflimpartodos>Limpar todos os filtros</button></div>`:''}
 <div class="tablebox gftable"><div class="tablewrap"><table><thead><tr><th style="width:28px"></th>${cabecalhoFiltro(linhas)}</tr></thead><tbody>
 ${G.map(g=>{const [t,tom]=GST[g.status]||[g.status,''],p=g.payable_id&&pagos.get(g.payable_id),paga=p?.status==='pago';return `<tr><td>${['rascunho','rejeitada'].includes(g.status)?`<input type="checkbox" class="check" data-df-gsel="${esc(g.id)}" ${st.gsel.has(g.id)?'checked':''}>`:''}</td><td>${dBR(g.created_at)}</td><td><strong>${esc(g.uf)}</strong> · ${g.tipo==='mensal'?'mensal':'por nota'}</td><td class="caption" ${g.tipo==='nota'?`data-exp-num="${Number(String(g.referencia||'').slice(25,34))||''}"`:''}>${g.tipo==='mensal'?esc(g.referencia):`NF ${esc(String(g.referencia||'').slice(25,34).replace(/^0+/,''))}`}${g.notas?.length>1?` · ${g.notas.length} notas`:''}</td>
  <td><span class="badge ${paga?'ok':tom}">${paga?'Paga':t}</span>${g.ambiente==='homologacao'&&g.status!=='rascunho'?(g.status==='rejeitada'?`<br><span class="caption">rejeitada no teste (homologação)${d.ambiente==='producao'?' · pode reenviar em produção':''}</span>`:'<br><span class="caption">guia de TESTE (homologação) · não pagar</span>'):''}${g.status==='enviada'&&g.retorno?`<br><span class="caption">Portal: ${esc(g.retorno.descricao||(g.retorno.guia?`guia na situação ${g.retorno.guia} (aguardando a SEFAZ da UF)`:'em processamento'))} · consultado ${new Date(g.retorno.em).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</span>`:''}${rejeicao(g)?`<br><span class="badge ${rejeicao(g).tipo==='dado'?'bad':'info'}" style="margin-top:4px">${esc(rejeicao(g).txt)}</span>`:''}${(g.motivos||[]).length?`<br><span class="caption red">${(g.motivos||[]).map(m=>esc(`${m.codigo||''} ${m.descricao||''}${m.campo?' ('+m.campo+')':''}`)).join(' · ')}</span>`:''}</td><td>${['rascunho','rejeitada'].includes(g.status)?(()=>{const em=emissaoDe(g),p=dataPagamento({tipo:g.tipo,emissao:em,vencimento:g.vencimento},hoje(),opcPag());return `<strong>${dBR(p)}</strong><br><span class="caption">${st.pag==='fixa'?'data escolhida':g.tipo==='nota'?(em?`emissão ${dBR(em)}`:'pela emissão'):'vencimento da apuração'}</span>`})():dBR(g.vencimento)}</td>
  <td>${g.linha_digitavel?`<code class="cialinha">${esc(g.linha_digitavel)}</code> <button class="small quiet" data-df-copiar="${esc(g.linha_digitavel)}">Copiar</button>${g.payable_id?'<br><span class="caption">no contas a pagar</span>':''}`:'<span class="caption">—</span>'}${g.status==='emitida'?` <button class="small quiet" data-df-pdf="${esc(g.recibo||'')}">PDF</button>`:''}${['rascunho','rejeitada'].includes(g.status)&&pode()?` <button class="small quiet" data-df-cancelar="${esc(g.id)}">Cancelar</button>`:''}</td><td class="num">${money(g.total)}</td></tr>`}).join('')||(filtrando?'<tr><td colspan="8" class="empty">Nenhuma guia com esses filtros. <button class="small" data-df-gflimpartodos>Limpar todos os filtros</button></td></tr>':'<tr><td colspan="8" class="empty">Nenhuma guia ainda. Prepare na aba Notas.</td></tr>')}</tbody></table></div></div>`}
function mensalView(){const ies=Object.entries(duf()).filter(([,v])=>v?.ie);if(!ies.length)return '<div class="empty">Nenhuma UF com inscrição estadual cadastrada. Sem inscrição, o DIFAL é pago por nota (aba Notas). Cadastre as UFs em Configuração.</div>';
 return `<div class="tablebox"><div class="tablewrap"><table><thead><tr><th>UF</th><th>Inscrição</th><th class="num">Notas no mês</th><th class="num">DIFAL</th><th class="num">FCP</th><th>Vencimento</th><th>Guia</th></tr></thead><tbody>
 ${ies.map(([u,v])=>{const l=st.notas.filter(x=>x.uf===u&&x.situacao==='mensal'),d=l.reduce((s,x)=>s+Number(x.v_difal),0),f=l.reduce((s,x)=>s+Number(x.v_fcp),0),g=st.guias.find(x=>x.tipo==='mensal'&&x.uf===u&&x.referencia===month&&x.status!=='cancelada');
  const [a,m]=month.split('-').map(Number),venc=new Date(a,m,Math.min(Number(v.dia)||10,28)).toLocaleDateString('pt-BR');
  return `<tr><td><strong>${u}</strong></td><td class="mono">${esc(v.ie)}</td><td class="num">${l.length}</td><td class="num">${money(d)}</td><td class="num">${money(f)}</td><td>${venc}</td><td>${g?`<span class="badge ${(GST[g.status]||[])[1]||''}">${(GST[g.status]||[g.status])[0]}</span>`:pode()&&l.length?`<button class="small primary" data-df-mensal="${u}">Gerar guia do mês</button>`:'—'}</td></tr>`}).join('')}</tbody></table></div></div>`}
function configView(){const c=fcfg(),e=c.emitente||{},d=st.diag||{},D=duf();
 const passos=[[true,'Notas de venda lidas do Bling a cada 2 minutos (DIFAL e FCP de cada nota).'],[!!(e.endereco&&e.ibge&&e.cep),'Dados do emitente para a guia (abaixo).'],[!!d.certificado,'Certificado A1 instalado no servidor: rode <code>ops\\gravar-certificado-gnre.ps1</code> (escolhe o .pfx e digita a senha escondida).'],[false,'Acesso ao webservice liberado no Portal GNRE (www.gnre.pe.gov.br › Área do contribuinte › Solicitar acesso ao webservice, com o mesmo certificado).'],[d.ambiente==='producao','Testado em homologação e trocado para produção (<code>ops\\gravar-certificado-gnre.ps1 -Producao</code>).']];
 return `<section class="card"><h3>Para gerar e transmitir as guias</h3><ol class="checklist">${passos.map(([ok,t])=>`<li class="${ok?'ok':''}">${ok?icon('check'):''} ${t}</li>`).join('')}</ol><p class="caption">Servidor: certificado ${d.certificado?'<span class="green">instalado</span>':'<span class="red">não instalado</span>'} · TLS com certificado ${d.cliente_tls?'disponível':'indisponível'} · ambiente GNRE: <strong>${esc(d.ambiente||'—')}</strong>. Sem certificado dá para baixar o XML do lote e enviar pelo site do portal.</p></section>
 <section class="card"><h3>Emitente na guia</h3><div class="grid three"><div style="grid-column:span 2"><label for="dfEnd">Endereço</label><input id="dfEnd" data-df-em="endereco" value="${esc(e.endereco||'')}" placeholder="Rua, número, bairro"></div><div><label for="dfCep">CEP</label><input id="dfCep" data-df-em="cep" value="${esc(e.cep||'')}"></div><div><label for="dfIbge">Código IBGE do município</label><input id="dfIbge" data-df-em="ibge" value="${esc(e.ibge||'')}" placeholder="7 dígitos (Timbó: 4218202)"></div><div><label for="dfTel">Telefone</label><input id="dfTel" data-df-em="telefone" value="${esc(e.telefone||'')}"></div><div><label for="dfRaz">Razão social</label><input id="dfRaz" data-df-em="razao" value="${esc(e.razao||c.razao||'')}"></div></div></section>
 ${autoHtml()}${cepUfHtml()}
 <section class="card"><h3>Inscrições estaduais de substituto tributário</h3>${inscricoesHtml()}</section>
 <section class="card"><h3>Leitura das notas</h3><p class="caption">O Jarvis começa no dia 1º do mês em que foi ligado e segue sozinho. Para reler desde outra data:</p><div class="row"><input type="date" id="dfDesde" value="${month}-01"><button class="small" data-df-ler>${icon('refresh')} Ler notas desde esta data</button></div></section>`}
function view(){if(st.notas&&st.mesCarregado!==month){st.notas=null;st.guias=null;st.sel.clear();if(st.dia&&!st.dia.startsWith(month))st.dia=''}
 if(!st.notas){carregar();return '<div class="empty">Carregando…</div>'}
 const A=[['notas','Notas'],['guias',`Guias (${st.guias.filter(g=>['rascunho','enviada','emitida','rejeitada'].includes(g.status)).length})`],['mensal','Apuração mensal'],['config','Configuração']];
 return `<div class="crmbar"><div class="segtabs">${A.map(([k,t])=>`<button class="${st.aba===k?'active':''}" data-df-aba="${k}">${t}</button>`).join('')}</div><div style="flex:1"></div>${st.aba==='notas'?diaBar():''}</div>${kpis()}${({notas:notasView,guias:guiasView,mensal:mensalView,config:configView}[st.aba]||notasView)()}`}

function diaBar(){const [a,m]=month.split('-').map(Number),fim=`${month}-${String(new Date(a,m,0).getDate()).padStart(2,'0')}`,h=hoje(),ont=new Date(Date.now()-864e5).toLocaleDateString('sv-SE');
 return `<div class="row" style="gap:6px;flex-wrap:wrap;align-items:center"><label class="caption" for="dfDia">Emitidas em</label><input id="dfDia" type="date" data-df="dia" value="${st.dia}" min="${month}-01" max="${fim}"><button class="small ${st.dia===h?'primary':'quiet'}" data-df-dia="${h}">Hoje</button><button class="small ${st.dia===ont?'primary':'quiet'}" data-df-dia="${ont}">Ontem</button><button class="small ${!st.dia?'primary':'quiet'}" data-df-dia="">Mês todo</button>${st.dia&&pode()?`<button class="small" data-df-lerdia title="Busca no Bling agora as notas deste dia, sem esperar a leitura automática">${icon('refresh')} Ler notas deste dia agora</button>`:''}</div>`}
const recarregar=()=>{st.notas=null;st.guias=null;carregar()};
function escolherDia(v){st.dia=/^\d{4}-\d{2}-\d{2}$/.test(v||'')?v:'';st.sel.clear();st.sit='pendente';if(st.dia&&!st.dia.startsWith(month)){month=st.dia.slice(0,7);st.notas=null}render()}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-df-temporarias],[data-df-uflimpar],[data-df-prontas],[data-df-testes],[data-df-dia],[data-df-lerdia],[data-df-aba],[data-df-uf],[data-df-preparar],[data-df-ignorar],[data-df-enviar],[data-df-xml],[data-df-consultar],[data-df-copiar],[data-df-pdf],[data-df-cancelar],[data-df-mensal],[data-df-cfg],[data-df-ler],[data-df-sispag]');if(!b)return;const d=b.dataset;
 if(d.dfDia!=null){escolherDia(d.dfDia);return}
 if(d.dfAba){st.aba=d.dfAba;render();return}
 if(d.dfTemporarias!==undefined){st.gsel=new Set(st.guias.filter(g=>st.gVis.includes(g.id)&&rejeicao(g)?.tipo==='temp').map(g=>g.id));render();return}
 if(d.dfUflimpar!==undefined){st.ufs.clear();st.ufAberto=false;st.sel.clear();render();return}
 if(d.dfUf){st.ufs=new Set([d.dfUf]);st.sit='todas';render();return}
 if(d.dfSispag!=null)return navigate('sispag');
 if(d.dfCopiar){try{await navigator.clipboard.writeText(d.dfCopiar);toast('Linha digitável copiada.')}catch{toast(d.dfCopiar)}return}
 b.disabled=true;
 try{
  if(d.dfTestes!=null){st.verTestes=!st.verTestes;render();return}
  if(d.dfProntas!=null){st.gsel=new Set(st.guias.filter(g=>st.gVis.includes(g.id)&&['rascunho','rejeitada'].includes(g.status)&&(st.verTestes||g.ambiente!=='homologacao'||g.status!=='emitida')).map(g=>g.id));render();return}
  if(d.dfPreparar!=null){const ch=[...st.sel];const r=await gnre('preparar',{chaves:ch});st.sel.clear();toast(`${r.guias.length} guia(s) preparada(s)${r.guias.length<ch.length?` · ${ch.length-r.guias.length} nota(s) cancelada(s) no Bling ficaram de fora`:''}.`);st.aba='guias';recarregar();return}
  if(d.dfIgnorar!=null){if(b.dataset.conf!=='1'){b.disabled=false;b.dataset.conf='1';b.textContent=`Confirmar: ${st.sel.size} já paga(s) fora do Jarvis`;b.classList.add('danger');return}
   const {error}=await Cloud.client.from('difal_notas').update({situacao:'ignorada',updated_at:new Date().toISOString()}).eq('workspace_id',Cloud.ws).in('chave',[...st.sel]).eq('situacao','pendente');if(error)throw error;audit('DIFAL: notas marcadas como pagas fora do Jarvis',`${st.sel.size} nota(s)`);st.sel.clear();recarregar();return}
  if(d.dfEnviar!=null){if(b.dataset.conf!=='1'){b.disabled=false;b.dataset.conf='1';b.textContent=`Confirmar envio (${st.diag?.ambiente==='producao'?'PRODUÇÃO':'homologação'})`;b.classList.add('danger');return}
   if(st.pag==='fixa'&&!(st.pagData>=hoje()))throw Error('Escolha a data de pagamento (a partir de hoje).');const r=await gnre('enviar',{ids:[...st.gsel],pagamento:opcPag()});st.gsel.clear();toast(`Lote ${r.recibo} enviado (${r.guias} guia(s)). O portal processa em alguns segundos.`);setTimeout(async()=>{try{await gnre('consultar');recarregar()}catch{}},15000);recarregar();return}
  if(d.dfXml!=null){if(st.pag==='fixa'&&!(st.pagData>=hoje()))throw Error('Escolha a data de pagamento (a partir de hoje).');const r=await gnre('xml',{ids:[...st.gsel],pagamento:opcPag()});download(`gnre-lote-${hoje()}.xml`,r.xml,'application/xml');toast(`XML com ${r.guias} guia(s). Envie em www.gnre.pe.gov.br › Lote de GNRE.`);b.disabled=false;return}
  if(d.dfConsultar!=null){const r=await gnre('consultar');const em=r.resultado.filter(x=>x.status==='emitida'&&!x.teste).length,tst=r.resultado.filter(x=>x.status==='emitida'&&x.teste).length,rj=r.resultado.filter(x=>x.status==='rejeitada').length;toast(em||tst||rj?[em?`${em} emitida(s) e lançada(s) no contas a pagar`:'',tst?`${tst} guia(s) de TESTE emitida(s) (não pagar; as notas voltaram para a fila)`:'',rj?`${rj} rejeitada(s): veja o motivo na lista`:''].filter(Boolean).join(' · ')+'.':'O portal ainda está processando.');if(em)await window.Cloud?.reload?.();recarregar();return}
  if(d.dfPdf!=null){const {data,error}=await Cloud.client.from('gnre_guias').select('pdf_base64').eq('workspace_id',Cloud.ws).eq('recibo',d.dfPdf).not('pdf_base64','is',null).limit(1);if(error)throw error;const p=data?.[0]?.pdf_base64;if(!p){b.disabled=false;return toast('O portal não devolveu o PDF deste lote.')}
   const bin=Uint8Array.from(atob(p),c=>c.charCodeAt(0));download(`gnre-${d.dfPdf}.pdf`,bin,'application/pdf');b.disabled=false;return}
  if(d.dfCancelar){await gnre('cancelar_rascunho',{id:d.dfCancelar});st.gsel.delete(d.dfCancelar);recarregar();return}
  if(d.dfMensal){const r=await gnre('preparar',{mensal:{uf:d.dfMensal,mes:month}});toast(`Guia mensal de ${d.dfMensal} preparada: ${money(r.guias[0]?.total||0)}.`);st.aba='guias';recarregar();return}
  if(d.dfCfg){const r=await gnre('config_uf',{uf:d.dfCfg});modal(`Exigências de ${d.dfCfg} (receita 100102)`,`<pre style="white-space:pre-wrap;font-size:12px">${esc(JSON.stringify(r,null,1))}</pre><div class="modalfoot"><button class="primary" data-action="close">Fechar</button></div>`);b.disabled=false;return}
  if(d.dfLerdia!=null){b.innerHTML='Lendo no Bling…';const r=await integ('difal_sync',{dia:st.dia});toast(`${new Date(st.dia+'T12:00').toLocaleDateString('pt-BR')}: ${r.lidas} nota(s) nova(s) lida(s), ${r.com_difal} com DIFAL${r.completo?'':'. Ainda faltam notas deste dia: clique de novo'}.`);recarregar();return}
  if(d.dfLer!=null){const desde=$('#dfDesde').value;const r=await integ('difal_sync',{desde});toast(`${r.lidas} nota(s) lida(s) · ${r.com_difal} com DIFAL. O restante segue pelo cron.`);recarregar();return}
 }catch(x){b.disabled=false;toast(x.message)}});
document.addEventListener('change',e=>{const x=e.target;
 if(x.matches('[data-df="dia"]')){escolherDia(x.value);return}
 if(x.matches('[data-df-pagmodo]')){st.pag=x.value==='fixa'?'fixa':'auto';if(st.pag==='fixa'&&!st.pagData)st.pagData=hoje();try{localStorage.setItem('eb_gnre_pag',st.pag)}catch{}render();return}
 if(x.matches('[data-df-pagdata]')){st.pagData=x.value;render();return}
 if(x.matches('[data-df-auto]')){salvarFiscal({gnre_auto:x.checked});audit('GNRE automática',x.checked?'ligada':'desligada');toast(x.checked?'GNRE automática ligada: os rascunhos aparecem todo dia às 7 h.':'GNRE automática desligada.');return}
 if(x.matches('[data-df-ufchk]')){const u=x.dataset.dfUfchk;if(x.checked)st.ufs.add(u);else st.ufs.delete(u);st.ufAberto=true;st.sel.clear();render();return}
 if(x.matches('[data-df-uftodas]')){st.ufs.clear();st.ufAberto=true;st.sel.clear();render();return}
 if(x.matches('[data-df="sit"]')){st.sit=x.value;st.sel.clear();render();return}
 if(x.matches('[data-df-sel]')){x.checked?st.sel.add(x.dataset.dfSel):st.sel.delete(x.dataset.dfSel);render();return}
 if(x.matches('[data-df-todas]')){const q=st.notas.filter(n=>noDia(n)&&(!st.ufs.size||st.ufs.has(n.uf))&&n.situacao==='pendente');if(x.checked)q.forEach(n=>st.sel.add(n.chave));else st.sel.clear();render();return}
 if(x.matches('[data-df-gsel]')){x.checked?st.gsel.add(x.dataset.dfGsel):st.gsel.delete(x.dataset.dfGsel);render();return}
 if(x.matches('[data-df-em]')){salvarFiscal({emitente:{...(fcfg().emitente||{}),[x.dataset.dfEm]:x.value.trim()}});toast('Salvo.');return}
 const u=x.dataset.dfIe||x.dataset.dfDia||x.dataset.dfFcp;if(u){const D={...duf()},v={...(D[u]||{})};if(x.dataset.dfIe)v.ie=x.value.replace(/[^\dA-Za-z]/g,'');else if(x.dataset.dfDia)v.dia=Number(x.value)||null;else v.fcp_separado=x.checked;
  if(!v.ie&&!v.fcp_separado&&!v.dia)delete D[u];else D[u]=v;salvarFiscal({difal_uf:D});if(x.dataset.dfIe&&window.Cloud?.client)Cloud.client.from('difal_notas').update({situacao:v.ie?'mensal':'pendente',updated_at:new Date().toISOString()}).eq('workspace_id',Cloud.ws).eq('uf',u).eq('situacao',v.ie?'pendente':'mensal').then(()=>recarregar());audit('DIFAL: configuração da UF',`${u} · ${v.ie?'IE '+v.ie:'sem IE'}`);toast(`${u} salvo. ${v.ie?'Notas novas dessa UF entram na apuração mensal.':''}`)}});

// ─── Inscrições estaduais (substituto tributário) — também aparece em Regras fiscais ───
const stIe={novo:false};
const redesenhar=()=>setTimeout(render,0); // depois dos outros tratadores de clique da página
function inscricoesHtml(){const D=duf(),ufEmit=fcfg().uf||'SC',l=Object.entries(D).filter(([,v])=>v?.ie).sort((a,b)=>a[0].localeCompare(b[0])),usadas=new Set(l.map(([u])=>u)),livres=UFS.filter(u=>u!==ufEmit&&!usadas.has(u));
 return `<p class="caption">Nas UFs em que a empresa é inscrita como substituta tributária, o DIFAL das vendas do mês vira uma guia só, no dia de vencimento da UF. Nas demais, uma GNRE por nota. Marque "FCP separado" se a UF exigir o FCP na receita 100129.</p>
 <div class="tablewrap"><table><thead><tr><th>Estado</th><th>Inscrição estadual</th><th class="num">Dia do vencimento</th><th>FCP separado</th><th></th></tr></thead><tbody>
 ${l.map(([u,v])=>`<tr><td><strong>${u}</strong></td><td><input class="ufin" data-ie-campo="ie" data-ie-uf="${u}" value="${esc(v.ie)}" style="width:170px" aria-label="Inscrição estadual ${u}"></td><td class="num"><input class="ufin" type="number" min="1" max="31" data-ie-campo="dia" data-ie-uf="${u}" value="${esc(v.dia||'')}" placeholder="10" style="width:70px" aria-label="Dia do vencimento ${u}"></td><td><input type="checkbox" class="check" data-ie-campo="fcp" data-ie-uf="${u}" ${v.fcp_separado?'checked':''} aria-label="FCP separado ${u}"></td><td><button class="small quiet" data-ie-remover="${u}" title="Remover inscrição de ${u}">${icon('x')}</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhuma inscrição cadastrada: o DIFAL é pago por nota em todas as UFs.</td></tr>'}
 ${stIe.novo?`<tr><td><select id="ieNovoUf">${livres.map(u=>`<option>${u}</option>`).join('')}</select></td><td><input id="ieNovoNum" class="ufin" placeholder="Número da inscrição" style="width:170px"></td><td class="num"><input id="ieNovoDia" class="ufin" type="number" min="1" max="31" placeholder="10" style="width:70px"></td><td><input id="ieNovoFcp" type="checkbox" class="check"></td><td><button class="small primary" data-ie-salvar>Salvar</button> <button class="small quiet" data-ie-cancelar>Cancelar</button></td></tr>`:''}
 </tbody></table></div>${stIe.novo||!pode()?'':`<button class="small" data-ie-add style="margin-top:8px">${icon('plus')} Adicionar outra inscrição</button>`}`}
function gravarIe(u,v,antes){const D={...duf()};if(v)D[u]=v;else delete D[u];salvarFiscal({difal_uf:D});
 const tinha=!!antes?.ie,tem=!!v?.ie;if(tinha!==tem&&window.Cloud?.client)try{Cloud.client.from('difal_notas').update({situacao:tem?'mensal':'pendente',updated_at:new Date().toISOString()}).eq('workspace_id',Cloud.ws).eq('uf',u).eq('situacao',tem?'pendente':'mensal').is('guia_id',null).then(()=>{if(page==='difal')recarregar()},()=>{})}catch(e){console.warn('DIFAL: notas não reclassificadas',e)}
 audit('Inscrição estadual (substituto tributário)',`${u} · ${v?.ie?'IE '+v.ie:'removida'}`)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-ie-add],[data-ie-cancelar],[data-ie-salvar],[data-ie-remover]');if(!b)return;const d=b.dataset;
 if(d.ieAdd!=null){stIe.novo=true;redesenhar();setTimeout(()=>$('#ieNovoNum')?.focus(),30);return}
 if(d.ieCancelar!=null){stIe.novo=false;redesenhar();return}
 if(d.ieSalvar!=null){const u=$('#ieNovoUf')?.value,ie=String($('#ieNovoNum')?.value||'').replace(/[^\dA-Za-z]/g,'');if(!u||!ie)return toast('Escolha o estado e informe a inscrição.');
  gravarIe(u,{ie,dia:Number($('#ieNovoDia')?.value)||null,fcp_separado:!!$('#ieNovoFcp')?.checked},duf()[u]);stIe.novo=false;redesenhar();toast(`Inscrição de ${u} salva. Notas novas de ${u} entram na apuração mensal.`);return}
 if(d.ieRemover){if(b.dataset.conf!=='1'){b.dataset.conf='1';b.textContent='Confirmar';b.classList.add('danger');return}const u=d.ieRemover,antes=duf()[u];gravarIe(u,null,antes);redesenhar();toast(`Inscrição de ${u} removida: o DIFAL de ${u} volta a ser por nota.`)}});
document.addEventListener('change',e=>{const x=e.target.closest('[data-ie-campo]');if(!x)return;const u=x.dataset.ieUf,antes=duf()[u]||{},v={...antes};
 if(x.dataset.ieCampo==='ie'){v.ie=x.value.replace(/[^\dA-Za-z]/g,'');if(!v.ie){x.value=antes.ie||'';return toast('Para tirar a inscrição, use o botão de remover.')}}
 else if(x.dataset.ieCampo==='dia')v.dia=Number(x.value)||null;else v.fcp_separado=x.checked;
 gravarIe(u,v,antes);toast(`${u} salvo.`)});
addPage('difal','guia','DIFAL e GNRE',view,'DIFAL e FCP de cada nota lidos do Bling, guias GNRE por nota ou mensais pelo webservice do portal, e pagamento pelo arquivo do banco.','',()=>{});
window.Difal={carregar,inscricoesHtml,dataPagamento,diaUtilSeguinte,avisos:()=>{const p=(st.notas||[]).filter(x=>x.situacao==='pendente');return p.length?[['warn','guia',`${p.length} nota(s) com DIFAL sem guia`,money(p.reduce((s,x)=>s+Number(x.v_difal)+Number(x.v_fcp),0)),'difal']]:[]}};
// Lista de estados: abre/fecha pelo título; clique fora fecha (sem redesenhar a tela).
document.addEventListener('click',e=>{const sum=e.target.closest('.ufsel > summary');if(sum){st.ufAberto=!sum.parentElement.open;return}
 if(st.ufAberto&&!e.target.closest('.ufsel')){st.ufAberto=false;document.querySelectorAll('.ufsel[open]').forEach(d=>d.open=false)}});
// CEP do emitente diferente por estado: só as guias daquela UF usam (ex.: MT exige o CEP do município do emitente).
const cepFmt=v=>{const d=String(v||'').replace(/\D/g,'');return d.length===8?`${d.slice(0,2)}.${d.slice(2,5)}-${d.slice(5)}`:d};
// GNRE automática (servidor, todo dia às 7 h): prepara os rascunhos das notas do dia anterior e avisa.
function autoHtml(){const on=fcfg().gnre_auto===true;return `<section class="card"><h3>GNRE automática</h3><label class="check-l"><input type="checkbox" class="check" data-df-auto ${on?'checked':''} ${pode()?'':'disabled'}> Preparar as guias sozinho todo dia às 7 h</label><p class="caption">Toda manhã o Jarvis cria os rascunhos das guias das notas emitidas no dia anterior (segunda-feira: sexta, sábado e domingo), já com a data de pagamento, e avisa no celular e no e-mail (marque “Guias GNRE prontas para enviar” em Alertas e relatórios). O envio ao portal continua sendo o seu clique em Guias. Notas de estados com inscrição seguem na apuração mensal.</p></section>`}
function cepUfHtml(){const m=fcfg().gnre_cep_uf||{},l=Object.entries(m).sort((a,b)=>a[0].localeCompare(b[0])),livres=UFS.filter(u=>!m[u]);
 return `<section class="card"><h3>CEP do emitente por estado</h3><p class="caption">Use quando um estado exigir outro CEP do emitente na guia. Só as guias desse estado usam o CEP daqui; as demais continuam com o CEP do emitente acima (${esc(cepFmt(fcfg().emitente?.cep))}).</p>
 <div class="tablewrap"><table><thead><tr><th>Estado</th><th>CEP do emitente nas guias</th><th></th></tr></thead><tbody>${l.map(([u,c])=>`<tr><td><strong>${u}</strong></td><td>${esc(cepFmt(c))}</td><td>${pode()?`<button class="small quiet" data-cepuf-tirar="${u}">${icon('x')} Remover</button>`:''}</td></tr>`).join('')||'<tr><td colspan="3" class="empty">Nenhum: todas as guias usam o CEP do emitente.</td></tr>'}</tbody></table></div>
 ${pode()?`<div class="row" style="gap:8px;margin-top:8px"><select id="cepUfUf" aria-label="Estado">${livres.map(u=>`<option>${u}</option>`).join('')}</select><input id="cepUfCep" class="ufin" placeholder="00.000-000" inputmode="numeric" style="width:130px" aria-label="CEP"><button class="small" data-cepuf-add>${icon('plus')} Adicionar</button></div>`:''}</section>`}
document.addEventListener('click',e=>{const b=e.target.closest('[data-cepuf-add],[data-cepuf-tirar]');if(!b)return;const m={...(fcfg().gnre_cep_uf||{})};
 if(b.dataset.cepufTirar){const u=b.dataset.cepufTirar;delete m[u];salvarFiscal({gnre_cep_uf:m});audit('GNRE: CEP do emitente por estado',`${u} removido`);toast(`${u} volta a usar o CEP do emitente.`);render();return}
 const u=$('#cepUfUf')?.value,c=String($('#cepUfCep')?.value||'').replace(/\D/g,'');if(!u||c.length!==8)return toast('Escolha o estado e informe o CEP com 8 dígitos.');
 m[u]=c;salvarFiscal({gnre_cep_uf:m});audit('GNRE: CEP do emitente por estado',`${u} · ${cepFmt(c)}`);toast(`Guias de ${u} vão com o CEP ${cepFmt(c)}.`);render()});
})();
