'use strict';
// Folha de pagamento. Mesmo acesso da Jornada (só o criador: RLS public.e_criador). Calcula a partir do contrato de cada
// pessoa (ponto_colaboradores), das horas do espelho de ponto (Ponto e jornada) e dos lançamentos do mês:
// salário/pró-labore/bolsa, horas extras 50%/100% + DSR, faltas + DSR perdido, atrasos, INSS progressivo, IRRF (com
// desconto simplificado e redutor de 2026), vale-transporte, FGTS e encargos da empresa. O fechamento congela o holerite
// e pode gerar as contas a pagar (salários, INSS, FGTS, IRRF), sempre por clique do dono.
(()=>{
const PADRAO={vigencia:'2026-01',salario_minimo:1621,
 inss:[[1621.00,7.5],[2902.84,9],[4354.27,12],[8475.55,14]],
 irrf:[[2428.80,0,0],[2826.65,7.5,182.16],[3751.05,15,394.16],[4664.68,22.5,675.49],[null,27.5,908.73]],
 irrf_dependente:189.59,irrf_simplificado:607.20,redutor_isento_ate:5000,redutor_ate:7350,redutor_a:978.62,redutor_b:0.133145,
 fgts:8,inss_patronal:20,rat:2,terceiros:5.8,prolabore_inss:11,prolabore_patronal:20,vt:6,divisor:220,he50:50,he100:100};
const st={ok:false,carregando:false,P:null,lanc:[],fech:[],aba:'mes',comp:null};
window.Reiniciar?.registrar(st,['aba','comp']); // estado de tela: volta ao original ao clicar no menu
const pad=n=>String(n).padStart(2,'0'),r2=v=>Math.round((Number(v)||0)*100)/100,R=v=>money(r2(v));
const compAtual=()=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-1);return `${d.getFullYear()}-${pad(d.getMonth()+1)}`};
const compLabel=v=>{const [y,m]=v.split('-').map(Number);return new Date(y,m-1,15).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})};
const VINC={clt:'CLT',prolabore:'Pró-labore',estagio:'Estágio'},quem=()=>window.Cloud?.session?.user?.email||'criador';
const P=()=>({...PADRAO,...(st.P||{})}),PT=()=>window.Ponto,colabs=()=>(PT()?.estado?.().colabs||[]);

async function carregar(forca){if(st.carregando||(!forca&&st.ok)||!window.Cloud?.ws)return;st.carregando=true;const c=Cloud.client,ws=Cloud.ws;
 try{await PT()?.garantir?.();await window.Pessoas?.garantir?.();const [a,b,d]=await Promise.all([c.from('folha_parametros').select('dados').eq('workspace_id',ws).maybeSingle(),c.from('folha_lancamentos').select('*').eq('workspace_id',ws).order('created_at'),c.from('folha_fechamentos').select('*').eq('workspace_id',ws)]);
  for(const x of [b,d])if(x.error)throw x.error;st.P=a.data?.dados||null;st.lanc=b.data;st.fech=d.data;st.ok=true;if(!st.comp)st.comp=compAtual()}
 catch(x){toast('Folha: '+(x.message||x))}st.carregando=false;if(page==='folha'&&!document.querySelector('.modalback'))render()}

// ── Cálculo ──
function inssProgressivo(base,f){let t=0,ant=0;for(const [lim,pct] of f){if(base<=ant)break;t+=(Math.min(base,lim)-ant)*pct/100;ant=lim}return r2(t)}
function irrfTabela(base,f){for(const [lim,pct,ded] of f)if(lim==null||base<=lim)return r2(Math.max(0,base*pct/100-ded));return 0}
function diaUtil5(comp){let [y,m]=comp.split('-').map(Number);m++;if(m>12){m=1;y++}let d=0,n=0;while(n<5){d++;if(new Date(y,m-1,d).getDay()!==0)n++}return `${y}-${pad(m)}-${pad(d)}`}
function dia20(comp){let [y,m]=comp.split('-').map(Number);m++;if(m>12){m=1;y++}const dt=new Date(y,m-1,20),w=dt.getDay();if(w===6)dt.setDate(19);if(w===0)dt.setDate(18);return `${dt.getFullYear()}-${pad(dt.getMonth()+1)}-${pad(dt.getDate())}`}
// Contrato vigente na competência: aplica a mudança programada (proximo_em) dali em diante.
function vigente(c,comp){return c.proximo_em&&c.proximo_vinculo&&comp>=c.proximo_em.slice(0,7)?{...c,vinculo:c.proximo_vinculo,salario:c.proximo_salario??c.salario,admissao:c.proximo_em}:c}
function calcular(c0,comp){const c=vigente(c0,comp),p=P(),[y,m]=comp.split('-').map(Number),ini=`${comp}-01`,fimDia=new Date(y,m,0).getDate(),fim=`${comp}-${pad(fimDia)}`;
 if(c.admissao&&c.admissao>fim)return null;if(c.demissao&&c.demissao<ini)return null;
 let dias=30;if(c.admissao&&c.admissao>=ini)dias=Math.max(0,30-(Number(c.admissao.slice(8))-1));if(c.demissao&&c.demissao<=fim)dias=Math.min(dias,Math.min(30,Number(c.demissao.slice(8))));
 let diasFer=0;const fer=(window.Pessoas?.ferias?.()||[]).filter(x=>x.colaborador_id===c0.id&&x.status!=='cancelada'&&x.gozo_ini<=fim&&x.gozo_fim>=ini);
 for(const x of fer){const a=x.gozo_ini>ini?x.gozo_ini:ini,b=x.gozo_fim<fim?x.gozo_fim:fim;diasFer+=Math.round((new Date(b+'T12:00:00Z')-new Date(a+'T12:00:00Z'))/864e5)+1}
 diasFer=Math.min(diasFer,dias);dias=Math.max(0,dias-diasFer);
 const it=[],av=[],add=(cod,desc,ref,valor,tipo,trib=true)=>{valor=r2(valor);if(valor>0)it.push({cod,desc,ref,valor,tipo,trib})},sal=Number(c.salario)||0,base=sal*dias/30;
 if(diasFer)av.push(`${diasFer} dia(s) de férias no mês: pagos no recibo de férias (Pessoas › Férias), fora do salário deste mês.`);
 if(!sal)av.push('Cadastre o salário no contrato.');
 add('001',{clt:'Salário base',prolabore:'Pró-labore',estagio:'Bolsa-auxílio'}[c.vinculo]||'Salário',`${dias} dias`,base,'p');
 if(c.vinculo==='clt'&&c.politica_horas==='pagar'&&PT()?.linhasMes){const L=PT().linhasMes(c,comp),vh=sal/(Number(p.divisor)||220);let he50=0,he100=0,faltas=[],atraso=0;
  const feriados=new Set(L.filter(l=>l.r?.tipo==='feriado').map(l=>l.data));
  for(const l of L){if(!l.conta||l.delta==null)continue;if(l.delta>0){if(l.wd===0||feriados.has(l.data))he100+=l.delta;else he50+=l.delta}
   else if(l.delta<0){if(!l.r||l.r.tipo==='falta')faltas.push(l);else atraso+=-l.delta}}
  const vHE50=he50/60*vh*(1+p.he50/100),vHE100=he100/60*vh*(1+p.he100/100);
  add('010','Horas extras 50%',`${Math.floor(he50/60)}h${pad(he50%60)}`,vHE50,'p');add('011','Horas extras 100%',`${Math.floor(he100/60)}h${pad(he100%60)}`,vHE100,'p');
  let uteis=0,dsrDias=0;for(let d=1;d<=fimDia;d++){const dt=`${comp}-${pad(d)}`,w=new Date(y,m-1,d).getDay();if(w===0||feriados.has(dt))dsrDias++;else uteis++}
  if(vHE50+vHE100>0&&uteis)add('012','DSR sobre horas extras',`${dsrDias}/${uteis}`,(vHE50+vHE100)/uteis*dsrDias,'p');
  if(faltas.length){add('101','Faltas',`${faltas.length} dia(s)`,faltas.length*sal/30,'d');const semanas=new Set(faltas.map(l=>{const dt=new Date(l.data+'T12:00');dt.setDate(dt.getDate()-dt.getDay());return dt.toISOString().slice(0,10)}));add('102','DSR perdido (faltas)',`${semanas.size} dia(s)`,semanas.size*sal/30,'d')}
  add('103','Atrasos e saídas antecipadas',`${Math.floor(atraso/60)}h${pad(atraso%60)}`,atraso/60*vh,'d')}
 else if(c.vinculo==='clt'&&PT()?.resumo){const rs=PT().resumo(c,comp);if(rs.saldo)av.push(`Saldo de ${rs.saldo>0?'+':'−'}${pad(Math.floor(Math.abs(rs.saldo)/60))}:${pad(Math.abs(rs.saldo)%60)} no ponto vai para o banco de horas (política "banco").`)}
 for(const l of st.lanc.filter(l=>l.colaborador_id===c.id&&l.competencia===comp))add(l.tipo==='provento'?'050':'150',l.descricao,l.referencia||'',l.valor,l.tipo==='provento'?'p':'d',l.tributavel);
 const provTrib=it.filter(i=>i.tipo==='p'&&i.trib).reduce((a,i)=>a+i.valor,0),descTrib=it.filter(i=>i.tipo==='d'&&i.trib).reduce((a,i)=>a+i.valor,0),baseINSS=r2(Math.max(0,provTrib-descTrib)),teto=p.inss[p.inss.length-1][0];
 let inss=0;if(c.vinculo==='clt')inss=inssProgressivo(baseINSS,p.inss);else if(c.vinculo==='prolabore')inss=r2(Math.min(baseINSS,teto)*p.prolabore_inss/100);
 add('201',c.vinculo==='prolabore'?`INSS contribuinte individual ${p.prolabore_inss}%`:'INSS',baseINSS?`${(inss/baseINSS*100).toFixed(2).replace('.',',')}%`:'',inss,'d',false);
 const rend=c.vinculo==='estagio'?r2(Math.max(0,provTrib-descTrib)):baseINSS,legais=inss+(Number(c.dependentes_ir)||0)*p.irrf_dependente,ded=Math.max(legais,p.irrf_simplificado),baseIR=r2(Math.max(0,rend-ded));
 let irrf=irrfTabela(baseIR,p.irrf);if(rend<=p.redutor_isento_ate)irrf=0;else if(rend<=p.redutor_ate)irrf=r2(Math.max(0,irrf-Math.max(0,p.redutor_a-p.redutor_b*rend)));
 add('202','IRRF',ded===legais?'deduções legais':'desconto simplificado',irrf,'d',false);
 if(c.vinculo==='clt'&&Number(c.vale_transporte)>0)add('203','Vale-transporte',`${p.vt}%`,Math.min(base*p.vt/100,Number(c.vale_transporte)),'d',false);
 const bruto=r2(it.filter(i=>i.tipo==='p').reduce((a,i)=>a+i.valor,0)),descontos=r2(it.filter(i=>i.tipo==='d').reduce((a,i)=>a+i.valor,0)),fgts=c.vinculo==='clt'?r2(baseINSS*p.fgts/100):0;
 const encargos=c.vinculo==='clt'?r2(baseINSS*(p.inss_patronal+p.rat+p.terceiros)/100):c.vinculo==='prolabore'?r2(baseINSS*p.prolabore_patronal/100):0;
 const prov=c.vinculo==='clt'?{ferias:r2(sal/12*4/3),decimo:r2(sal/12)}:null;
 if(c.vinculo==='prolabore')av.push('Pró-labore: sem FGTS e sem horas extras; INSS de 11% até o teto e 20% da empresa.');
 return {comp,colaborador:{id:c.id,nome:c.nome,cargo:c.cargo,vinculo:c.vinculo,admissao:c.admissao,salario:sal,dependentes:c.dependentes_ir||0},itens:it,bruto,descontos,liquido:r2(bruto-descontos),bases:{inss:baseINSS,fgts:c.vinculo==='clt'?baseINSS:0,irrf:baseIR},inss,irrf,fgts,encargos,provisao:prov,avisos:av,calculado_em:new Date().toISOString()}}
const fechado=(cid,comp)=>st.fech.find(f=>f.colaborador_id===cid&&f.competencia===comp);
function holerite(c,comp){const f=fechado(c.id,comp);return f?{...f.holerite,fechado:true,lancado:f.lancado_pagar}:calcular(c,comp)}
function folhaDoMes(comp){return colabs().map(c=>({c,h:holerite(c,comp)})).filter(x=>x.h&&(x.c.ativo||fechado(x.c.id,comp)))}

// ── Telas ──
const k=(t,v,s,c='')=>`<div class="card kpi"><span class="kpil">${t}</span><span class="kpiv ${c}">${v}</span><span class="kpis">${s}</span></div>`;
function mesView(){const F=folhaDoMes(st.comp),T=F.reduce((a,{h})=>({b:a.b+h.bruto,d:a.d+h.descontos,l:a.l+h.liquido,f:a.f+h.fgts,e:a.e+h.encargos}),{b:0,d:0,l:0,f:0,e:0}),todos=F.length&&F.every(x=>x.h.fechado),lanc=F.length&&F.every(x=>x.h.lancado);
 if(!F.length)return `${seletor()}<div class="empty">Ninguém com contrato ativo nesta competência. Cadastre salário e vínculo em <a href="#" data-fl-aba="contratos">Contratos</a>.</div>`;
 return `${seletor()}<div class="grid kpis4">${k('Total bruto',R(T.b),`${F.length} pessoa(s)`)}${k('Descontos',R(T.d),'INSS, IRRF, faltas, VT e outros','red')}${k('Líquido a pagar',R(T.l),`até ${new Date(diaUtil5(st.comp)+'T12:00').toLocaleDateString('pt-BR')} (5º dia útil)`,'green')}${k('Custo da empresa',R(T.b+T.f+T.e),`FGTS ${R(T.f)} + encargos ${R(T.e)}`)}</div>
 <div class="row wrap" style="gap:8px;margin:-6px 0 14px"><span class="badge ${todos?'ok':'warn'}">${todos?'Folha fechada':'Folha aberta (prévia)'}</span>${todos?`<button class="small" data-fl="reabrir">Reabrir</button>${lanc?'<span class="badge ok">Lançada no contas a pagar</span>':'<button class="small primary" data-fl="pagar">Lançar no contas a pagar</button>'}`:'<button class="small primary" data-fl="fechar">Fechar folha</button>'}<span style="flex:1"></span><button class="small" data-fl="csv">${icon('download')} CSV</button><button class="small" data-fl="zip">${icon('download')} Holerites (ZIP)</button></div>
 <div class="tablebox" style="overflow-x:auto"><table><thead><tr><th>Pessoa</th><th>Vínculo</th><th class="num">Bruto</th><th class="num">INSS</th><th class="num">IRRF</th><th class="num">Outros desc.</th><th class="num">Líquido</th><th class="num">FGTS</th><th class="num">Encargos</th><th></th></tr></thead><tbody>
 ${F.map(({c,h})=>`<tr class="flrow" data-fl-ver="${c.id}"><td><b>${esc(PT().curto(c.nome))}</b>${h.avisos?.length?` <span class="badge warn" title="${esc(h.avisos.join(' '))}">!</span>`:''}</td><td>${VINC[h.colaborador.vinculo]||h.colaborador.vinculo}</td><td class="num">${R(h.bruto)}</td><td class="num">${R(h.inss)}</td><td class="num">${R(h.irrf)}</td><td class="num">${R(h.descontos-h.inss-h.irrf)}</td><td class="num"><b>${R(h.liquido)}</b></td><td class="num">${R(h.fgts)}</td><td class="num">${R(h.encargos)}</td><td>${h.fechado?'<span class="badge ok">fechado</span>':''}</td></tr>`).join('')}
 <tr class="fltotal"><td colspan="2"><b>Total</b></td><td class="num"><b>${R(T.b)}</b></td><td class="num">${R(F.reduce((a,x)=>a+x.h.inss,0))}</td><td class="num">${R(F.reduce((a,x)=>a+x.h.irrf,0))}</td><td class="num">${R(F.reduce((a,x)=>a+x.h.descontos-x.h.inss-x.h.irrf,0))}</td><td class="num"><b>${R(T.l)}</b></td><td class="num">${R(T.f)}</td><td class="num">${R(T.e)}</td><td></td></tr></tbody></table></div>
 <p class="caption" style="margin-top:8px">Clique numa pessoa para ver o holerite. Tabelas de INSS e IRRF de ${compLabel(P().vigencia)} em <a href="#" data-fl-aba="tabelas">Tabelas</a> — confira com a legislação vigente antes de fechar.</p>`}
function seletor(){return `<div class="row wrap" style="gap:8px;margin-bottom:14px"><label class="caption" for="flComp">Competência</label><input id="flComp" type="month" value="${st.comp}" data-fl-comp style="width:auto"></div>`}
function holeriteHtml(h){const P_=h.itens.filter(i=>i.tipo==='p'),D=h.itens.filter(i=>i.tipo==='d');
 return `<div class="flhol"><div class="flholtop"><div><b>${esc(h.colaborador.nome)}</b><small class="caption">${VINC[h.colaborador.vinculo]} · ${h.colaborador.cargo?esc(h.colaborador.cargo)+' · ':''}salário ${R(h.colaborador.salario)}</small></div><span class="badge ${h.fechado?'ok':'warn'}">${h.fechado?'fechado':'prévia'} · ${compLabel(h.comp)}</span></div>
 <div class="tablebox" style="overflow-x:auto"><table><thead><tr><th>Cód.</th><th>Descrição</th><th>Ref.</th><th class="num">Proventos</th><th class="num">Descontos</th></tr></thead><tbody>
 ${[...P_,...D].map(i=>`<tr><td>${i.cod}</td><td>${esc(i.desc)}</td><td>${esc(i.ref||'')}</td><td class="num">${i.tipo==='p'?R(i.valor):''}</td><td class="num">${i.tipo==='d'?R(i.valor):''}</td></tr>`).join('')}
 <tr class="fltotal"><td colspan="3"><b>Totais</b></td><td class="num"><b>${R(h.bruto)}</b></td><td class="num"><b>${R(h.descontos)}</b></td></tr></tbody></table></div>
 <div class="flliq"><span>Líquido a receber</span><b>${R(h.liquido)}</b></div>
 <p class="caption">Base INSS ${R(h.bases.inss)} · Base FGTS ${R(h.bases.fgts)} · FGTS do mês ${R(h.fgts)} · Base IRRF ${R(h.bases.irrf)}${h.provisao?` · provisão férias ${R(h.provisao.ferias)} e 13º ${R(h.provisao.decimo)}`:''}</p>
 ${(h.avisos||[]).map(a=>`<p class="notice" style="margin:6px 0">${esc(a)}</p>`).join('')}</div>`}
function lancView(){const L=st.lanc.filter(l=>l.competencia===st.comp),fechadoMes=folhaDoMes(st.comp).some(x=>x.h.fechado);
 return `${seletor()}<div class="grid two"><section class="card"><h3>Novo lançamento · ${compLabel(st.comp)}</h3><p class="caption">Comissões, bônus, adiantamentos, faltas manuais, pensão, reembolsos…</p>
  <div class="grid two" style="gap:8px"><div><label for="flP">Pessoa</label><select id="flP">${colabs().filter(c=>c.ativo).map(c=>`<option value="${c.id}">${esc(c.nome)}</option>`).join('')}</select></div><div><label for="flT">Tipo</label><select id="flT"><option value="provento">Provento (+)</option><option value="desconto">Desconto (−)</option></select></div>
  <div><label for="flD">Descrição</label><input id="flD" list="flSug" placeholder="Ex.: Comissão de vendas"><datalist id="flSug">${['Comissão','Bônus','Adicional noturno','Periculosidade 30%','Insalubridade','Adiantamento salarial','Pensão alimentícia','Faltas','Reembolso de despesas','Vale-refeição (desconto)','Plano de saúde (coparticipação)'].map(s=>`<option value="${s}">`).join('')}</datalist></div><div><label for="flV">Valor (R$)</label><input id="flV" inputmode="decimal" placeholder="0,00"></div>
  <div><label for="flR">Referência</label><input id="flR" placeholder="Ex.: 3% de R$ 20 mil"></div><div style="display:flex;align-items:flex-end"><label class="check-l"><input type="checkbox" class="check" id="flTr" checked> Entra na base de INSS, FGTS e IRRF</label></div></div>
  <button class="primary small" style="margin-top:10px" data-fl="lancar" ${fechadoMes?'disabled title="Reabra a folha para lançar"':''}>Registrar lançamento</button></section>
 <section class="card"><h3>Lançamentos do mês</h3>${L.length?L.map(l=>{const c=colabs().find(x=>x.id===l.colaborador_id);return `<div class="listline"><span><b class="${l.tipo==='provento'?'green':'red'}">${l.tipo==='provento'?'+':'−'} ${R(l.valor)}</b> · ${esc(l.descricao)}${l.tributavel?'':' <small class="caption">(não tributável)</small>'}<br><small class="caption">${esc(c?PT().curto(c.nome):'—')}${l.referencia?' · '+esc(l.referencia):''}</small></span>${fechadoMes?'':`<button class="small quiet" data-fl-rm="${l.id}">Excluir</button>`}</div>`}).join(''):'<p class="caption">Nenhum lançamento nesta competência.</p>'}</section></div>`}
function guiasView(){const F=folhaDoMes(st.comp),s=f=>F.reduce((a,x)=>a+f(x),0),p=P();
 const inssSeg=s(x=>x.h.inss),patr=s(x=>x.h.encargos),fgts=s(x=>x.h.fgts),irClt=s(x=>x.h.colaborador.vinculo!=='prolabore'?x.h.irrf:0),irPro=s(x=>x.h.colaborador.vinculo==='prolabore'?x.h.irrf:0),liq=s(x=>x.h.liquido);
 const G=[['Salários e pró-labore (líquido)',liq,diaUtil5(st.comp),'Pagamento às pessoas · até o 5º dia útil'],['INSS (DCTFWeb)',inssSeg+patr,dia20(st.comp),`Segurados ${R(inssSeg)} + empresa ${R(patr)} (patronal ${p.inss_patronal}% + RAT ${p.rat}% + terceiros ${p.terceiros}%)`],['FGTS (FGTS Digital)',fgts,dia20(st.comp),`${p.fgts}% sobre a base dos empregados CLT`],['IRRF sobre salários (DCTFWeb)',irClt,dia20(st.comp),'Retido dos empregados'],['IRRF sobre pró-labore (DCTFWeb)',irPro,dia20(st.comp),'Retido dos sócios']];
 return `${seletor()}<div class="tablebox"><table><thead><tr><th>Obrigação</th><th class="num">Valor</th><th>Vencimento</th><th>Composição</th></tr></thead><tbody>${G.filter(g=>g[1]>0).map(g=>`<tr><td><b>${g[0]}</b></td><td class="num">${R(g[1])}</td><td>${new Date(g[2]+'T12:00').toLocaleDateString('pt-BR')}</td><td><small class="caption">${esc(g[3])}</small></td></tr>`).join('')}</tbody></table></div>
 <p class="caption" style="margin-top:10px">Vencimentos: salário até o 5º dia útil do mês seguinte; DCTFWeb e FGTS Digital no dia 20 (antecipa se cair no fim de semana). Encargos da empresa conforme o regime (lucro presumido/real); no Simples Nacional a contribuição patronal pode não se aplicar — ajuste em Tabelas.</p>
 <section class="card" style="margin-top:14px"><h3>Provisões do mês (CLT)</h3><p>Férias + 1/3: <b>${R(s(x=>x.h.provisao?.ferias||0))}</b> · 13º salário: <b>${R(s(x=>x.h.provisao?.decimo||0))}</b></p><p class="caption">Valores de referência para a contabilidade; não geram contas a pagar.</p></section>`}
function contratosView(){return `<p class="caption" style="margin-top:-4px">As mesmas pessoas de Ponto e jornada. Aqui ficam os dados para a folha.</p><div class="tablebox" style="overflow-x:auto"><table><thead><tr><th>Pessoa</th><th>Vínculo</th><th class="num">Salário</th><th>Admissão</th><th class="num">Dependentes IR</th><th class="num">VT/mês</th><th>Horas</th><th>Mudança programada</th><th></th></tr></thead><tbody>
 ${colabs().map(c=>`<tr><td><b>${esc(c.nome)}</b>${c.ativo?'':' <small class="caption">(inativa)</small>'}</td><td>${VINC[c.vinculo]||'—'}</td><td class="num">${R(c.salario)}</td><td>${c.admissao?new Date(c.admissao+'T12:00').toLocaleDateString('pt-BR'):'—'}</td><td class="num">${c.dependentes_ir||0}</td><td class="num">${Number(c.vale_transporte)?R(c.vale_transporte):'—'}</td><td>${c.politica_horas==='pagar'?'pagar HE / descontar':'banco de horas'}</td><td>${c.proximo_em&&c.proximo_vinculo?`${VINC[c.proximo_vinculo]} ${R(c.proximo_salario??c.salario)} a partir de ${new Date(c.proximo_em+'T12:00').toLocaleDateString('pt-BR')}`:'—'}</td><td><button class="small" data-fl-contrato="${c.id}">Editar</button></td></tr>`).join('')}</tbody></table></div>`}
function contrato(id){const c=colabs().find(x=>x.id===id);if(!c)return;
 modal(`Contrato · ${esc(c.nome)}`,`<div class="grid two" style="gap:10px"><div><label for="ctV">Vínculo</label><select id="ctV">${Object.entries(VINC).map(([v,t])=>`<option value="${v}" ${c.vinculo===v?'selected':''}>${t}</option>`).join('')}</select></div><div><label for="ctS">${'Salário / pró-labore / bolsa (R$)'}</label><input id="ctS" inputmode="decimal" value="${Number(c.salario)?String(c.salario).replace('.',','):''}"></div>
 <div><label for="ctA">Admissão</label><input id="ctA" type="date" value="${c.admissao||''}"></div><div><label for="ctDm">Desligamento</label><input id="ctDm" type="date" value="${c.demissao||''}"></div>
 <div><label for="ctDep">Dependentes para o IR</label><input id="ctDep" type="number" min="0" max="20" value="${c.dependentes_ir||0}"></div><div><label for="ctVT">Vale-transporte (R$/mês)</label><input id="ctVT" inputmode="decimal" value="${Number(c.vale_transporte)?String(c.vale_transporte).replace('.',','):''}" placeholder="0 = não usa"></div>
 <div><label for="ctH">Horas do ponto</label><select id="ctH"><option value="banco" ${c.politica_horas!=='pagar'?'selected':''}>Banco de horas (compensa)</option><option value="pagar" ${c.politica_horas==='pagar'?'selected':''}>Pagar extras e descontar faltas/atrasos</option></select></div><div><label for="ctPix">Chave PIX (pagamento)</label><input id="ctPix" value="${esc(c.pix||'')}"></div></div>
 <h3 style="margin:14px 0 6px;font-size:15px">Mudança programada de contrato</h3><p class="caption" style="margin:0 0 8px">Ex.: pró-labore até 30/09 e CLT a partir de 01/10. A data vira a admissão no novo vínculo.</p><div class="grid three" style="gap:10px"><div><label for="ctPE">A partir de</label><input id="ctPE" type="date" value="${c.proximo_em||''}"></div><div><label for="ctPV">Novo vínculo</label><select id="ctPV"><option value="">— nenhuma —</option>${Object.entries(VINC).map(([v,t])=>`<option value="${v}" ${c.proximo_vinculo===v?'selected':''}>${t}</option>`).join('')}</select></div><div><label for="ctPS">Novo salário (R$)</label><input id="ctPS" inputmode="decimal" value="${c.proximo_salario!=null?String(c.proximo_salario).replace('.',','):''}"></div></div>
 <div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-fl-salvact="${c.id}">Salvar</button></div>`)}
function tabelasView(){const p=P(),f=v=>String(v??'').replace('.',',');
 return `<div class="notice">Valores de referência para ${compLabel(p.vigencia)}. <b>Confira com a legislação vigente</b> (portaria do INSS, tabela do IRRF e Lei 15.270/2025) antes de fechar a folha; tudo aqui é editável.</div>
 <div class="grid two"><section class="card"><h3>INSS · empregados (progressiva)</h3>${p.inss.map((x,i)=>`<div class="row" style="gap:8px"><label style="flex:1">Até R$<input data-tb="inss.${i}.0" value="${f(x[0])}"></label><label style="width:110px">Alíquota %<input data-tb="inss.${i}.1" value="${f(x[1])}"></label></div>`).join('')}
  <div class="row" style="gap:8px"><label style="flex:1">Salário mínimo R$<input data-tb="salario_minimo" value="${f(p.salario_minimo)}"></label><label style="flex:1">Pró-labore INSS %<input data-tb="prolabore_inss" value="${f(p.prolabore_inss)}"></label></div></section>
 <section class="card"><h3>IRRF (mensal)</h3>${p.irrf.map((x,i)=>`<div class="row" style="gap:8px"><label style="flex:1">Até R$<input data-tb="irrf.${i}.0" value="${x[0]==null?'':f(x[0])}" placeholder="acima"></label><label style="width:90px">%<input data-tb="irrf.${i}.1" value="${f(x[1])}"></label><label style="width:110px">Dedução<input data-tb="irrf.${i}.2" value="${f(x[2])}"></label></div>`).join('')}
  <div class="row" style="gap:8px"><label style="flex:1">Por dependente<input data-tb="irrf_dependente" value="${f(p.irrf_dependente)}"></label><label style="flex:1">Desconto simplificado<input data-tb="irrf_simplificado" value="${f(p.irrf_simplificado)}"></label></div>
  <div class="row" style="gap:8px"><label style="flex:1">Isento até (redutor)<input data-tb="redutor_isento_ate" value="${f(p.redutor_isento_ate)}"></label><label style="flex:1">Redutor até<input data-tb="redutor_ate" value="${f(p.redutor_ate)}"></label></div>
  <div class="row" style="gap:8px"><label style="flex:1">Redução = A −<input data-tb="redutor_a" value="${f(p.redutor_a)}"></label><label style="flex:1">B × rendimento<input data-tb="redutor_b" value="${f(p.redutor_b)}"></label></div></section>
 <section class="card"><h3>Encargos da empresa</h3><div class="grid two" style="gap:8px">${[['fgts','FGTS %'],['inss_patronal','INSS patronal %'],['rat','RAT × FAP %'],['terceiros','Terceiros (Sistema S) %'],['prolabore_patronal','INSS empresa sobre pró-labore %'],['vt','Desconto vale-transporte %'],['divisor','Divisor de horas'],['he50','Adicional hora extra dia útil %'],['he100','Adicional domingo/feriado %']].map(([c,t])=>`<label>${t}<input data-tb="${c}" value="${f(p[c])}"></label>`).join('')}</div></section>
 <section class="card"><h3>Vigência</h3><label>Competência de referência<input type="month" data-tb="vigencia" value="${p.vigencia}"></label><div class="row wrap" style="gap:8px;margin-top:12px"><button class="primary small" data-fl="salvartab">Salvar tabelas</button><button class="small quiet" data-fl="padraotab">Voltar ao padrão</button></div></section></div>`}
function view(){const a=PT()?.acesso;if(a===null||a===undefined){PT()?.garantir?.();return '<div class="empty">Verificando acesso…</div>'}
 if(!a)return '<div class="notice">Esta área é exclusiva de quem criou a empresa no Jarvis.</div>';
 if(!st.ok){carregar();return '<div class="empty">Carregando a folha…</div>'}
 const A=[['mes','Folha do mês'],['lanc','Lançamentos'],['guias','Encargos e guias'],['contratos','Contratos'],['tabelas','Tabelas']];
 return `<div class="segtabs">${A.map(([id,t])=>`<button class="${st.aba===id?'active':''}" data-fl-aba="${id}">${t}</button>`).join('')}</div>${({mes:mesView,lanc:lancView,guias:guiasView,contratos:contratosView,tabelas:tabelasView}[st.aba]||mesView)()}`}

// ── PDF do holerite ──
const carregaLib=(g,src)=>window[g]?Promise.resolve():new Promise((ok,er)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=()=>er(Error('Não foi possível carregar '+g));document.head.appendChild(s)});
async function pdf(h){await carregaLib('jspdf','https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js');const {jsPDF}=window.jspdf,d=new jsPDF({unit:'pt',format:'a4'}),W=595.28,M=36,t=s=>String(s??'').normalize('NFD').replace(/[̀-ͯ]/g,''),V=v=>r2(v).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
 d.setFillColor(11,22,34);d.rect(0,0,W,74,'F');d.setTextColor(95,224,204);d.setFont('helvetica','bold');d.setFontSize(10);d.text('RECIBO DE PAGAMENTO',M,26);d.setTextColor(255,255,255);d.setFontSize(15);d.text(t(window.Cloud?.wsName||'Empresa'),M,48);d.setFont('helvetica','normal');d.setFontSize(10);d.text(t(`Competencia: ${compLabel(h.comp)}`),W-M,48,{align:'right'});
 d.setTextColor(26,50,68);d.setFontSize(11);d.setFont('helvetica','bold');d.text(t(h.colaborador.nome),M,100);d.setFont('helvetica','normal');d.setFontSize(9);d.text(t(`${VINC[h.colaborador.vinculo]}${h.colaborador.cargo?' · '+h.colaborador.cargo:''}${h.colaborador.admissao?' · admissao '+new Date(h.colaborador.admissao+'T12:00').toLocaleDateString('pt-BR'):''} · salario R$ ${V(h.colaborador.salario)}`),M,114);
 let y=140;const X=[M+4,70,300,470,W-M-4];d.setFillColor(232,242,245);d.rect(M,y-12,W-2*M,20,'F');d.setFont('helvetica','bold');d.setFontSize(9);['Cod.','Descricao','Ref.'].forEach((s,i)=>d.text(s,X[i],y+2));d.text('Proventos',X[3],y+2,{align:'right'});d.text('Descontos',X[4],y+2,{align:'right'});y+=22;d.setFont('helvetica','normal');
 for(const i of [...h.itens.filter(i=>i.tipo==='p'),...h.itens.filter(i=>i.tipo==='d')]){d.text(i.cod,X[0],y);d.text(t(i.desc).slice(0,42),X[1],y);d.text(t(i.ref||'').slice(0,26),X[2],y);d.text(i.tipo==='p'?V(i.valor):'',X[3],y,{align:'right'});d.text(i.tipo==='d'?V(i.valor):'',X[4],y,{align:'right'});d.setDrawColor(230,235,238);d.line(M,y+5,W-M,y+5);y+=17}
 y+=6;d.setFont('helvetica','bold');d.text('Totais',X[1],y);d.text(V(h.bruto),X[3],y,{align:'right'});d.text(V(h.descontos),X[4],y,{align:'right'});y+=22;d.setFillColor(232,242,245);d.rect(M,y-14,W-2*M,28,'F');d.setFontSize(12);d.text('Liquido a receber',M+8,y+4);d.text(`R$ ${V(h.liquido)}`,W-M-8,y+4,{align:'right'});y+=34;
 d.setFont('helvetica','normal');d.setFontSize(8.5);d.setTextColor(80,98,110);d.text(t(`Base INSS R$ ${V(h.bases.inss)}   Base FGTS R$ ${V(h.bases.fgts)}   FGTS do mes R$ ${V(h.fgts)}   Base IRRF R$ ${V(h.bases.irrf)}`),M,y);y+=40;
 d.setTextColor(26,50,68);d.setFontSize(9);d.text(t('Declaro ter recebido a importancia liquida discriminada neste recibo.'),M,y);y+=34;d.line(M,y,M+230,y);d.line(W-M-150,y,W-M,y);d.setFontSize(8);d.text(t('Assinatura'),M,y+11);d.text('Data',W-M-150,y+11);
 return {bytes:d.output('arraybuffer'),nome:`holerite-${t(h.colaborador.nome).toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${h.comp}.pdf`}}
function baixar(blob,nome){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=nome;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1500)}
const num=v=>{const s=String(v??'').trim();if(!s)return null;const n=Number(s.includes(',')?s.replace(/\./g,'').replace(',','.'):s);return Number.isFinite(n)?n:null};

// ── Eventos ──
document.addEventListener('click',async e=>{const b=e.target.closest('[data-fl],[data-fl-aba],[data-fl-ver],[data-fl-rm],[data-fl-contrato],[data-fl-salvact],[data-fl-pdf]');if(!b)return;const d=b.dataset;
 if(d.flAba){e.preventDefault();st.aba=d.flAba;render();return}
 if(d.flVer){const c=colabs().find(x=>x.id===d.flVer),h=c&&holerite(c,st.comp);if(!h)return;modal(`Holerite · ${compLabel(st.comp)}`,`${holeriteHtml(h)}<div class="modalfoot"><button data-action="close">Fechar</button><button class="primary" data-fl-pdf="${c.id}">${icon('download')} PDF</button></div>`);return}
 if(d.flPdf){try{const c=colabs().find(x=>x.id===d.flPdf),r=await pdf(holerite(c,st.comp));baixar(new Blob([r.bytes],{type:'application/pdf'}),r.nome)}catch(x){toast(x.message)}return}
 if(d.flRm){const {error}=await Cloud.client.from('folha_lancamentos').delete().eq('workspace_id',Cloud.ws).eq('id',d.flRm);if(error)return toast(error.message);await carregar(true);return}
 if(d.flContrato){contrato(d.flContrato);return}
 if(d.flSalvact){const s=num($('#ctS').value),vt=num($('#ctVT').value)||0;if(s==null||s<0)return toast('Informe o salário.');
  const row={vinculo:$('#ctV').value,salario:s,admissao:$('#ctA').value||null,demissao:$('#ctDm').value||null,dependentes_ir:Number($('#ctDep').value)||0,vale_transporte:vt,politica_horas:$('#ctH').value,pix:$('#ctPix').value.trim()||null,proximo_em:$('#ctPV').value?($('#ctPE').value||null):null,proximo_vinculo:$('#ctPV').value&&$('#ctPE').value?$('#ctPV').value:null,proximo_salario:$('#ctPV').value&&$('#ctPE').value?num($('#ctPS').value):null,updated_at:new Date().toISOString()};
  const {error}=await Cloud.client.from('ponto_colaboradores').update(row).eq('workspace_id',Cloud.ws).eq('id',d.flSalvact);if(error)return toast(error.message);
  await Cloud.client.from('ponto_auditoria').insert({workspace_id:Cloud.ws,colaborador_id:d.flSalvact,acao:'Contrato alterado',depois:{vinculo:row.vinculo,salario:row.salario,horas:row.politica_horas},por:quem()});closeModal();toast('Contrato salvo.');await PT().recarregar();render();return}
 switch(d.fl){
  case 'lancar':{const v=num($('#flV').value),desc=$('#flD').value.trim();if(!(v>0))return toast('Informe o valor.');if(desc.length<3)return toast('Descreva o lançamento.');
   const {error}=await Cloud.client.from('folha_lancamentos').insert({workspace_id:Cloud.ws,colaborador_id:$('#flP').value,competencia:st.comp,tipo:$('#flT').value,descricao:desc,referencia:$('#flR').value.trim()||null,valor:v,tributavel:$('#flTr').checked,criado_por:quem()});if(error)return toast(error.message);toast('Lançado.');await carregar(true);break}
  case 'fechar':{const F=folhaDoMes(st.comp).filter(x=>!x.h.fechado);modal('Fechar a folha',`<p>Fecha ${compLabel(st.comp)} de <b>${F.length}</b> pessoa(s): o holerite fica congelado com os valores de agora (mesmo que o ponto ou as tabelas mudem depois). Líquido total <b>${R(F.reduce((a,x)=>a+x.h.liquido,0))}</b>.</p><div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-fl="fecharok">Fechar folha</button></div>`);break}
  case 'fecharok':{const F=folhaDoMes(st.comp).filter(x=>!x.h.fechado),rows=F.map(({c,h})=>({workspace_id:Cloud.ws,competencia:st.comp,colaborador_id:c.id,holerite:h,bruto:h.bruto,descontos:h.descontos,liquido:h.liquido,fgts:h.fgts,encargos:h.encargos,fechado_por:quem()}));
   const {error}=await Cloud.client.from('folha_fechamentos').insert(rows);if(error)return toast(error.message);await Cloud.client.from('ponto_auditoria').insert({workspace_id:Cloud.ws,acao:`Folha de ${st.comp} fechada`,depois:{pessoas:rows.length,liquido:r2(rows.reduce((a,r)=>a+r.liquido,0))},por:quem()});closeModal();toast('Folha fechada.');await carregar(true);break}
  case 'reabrir':{if(folhaDoMes(st.comp).some(x=>x.h.lancado))return toast('Já foi lançada no contas a pagar: exclua os títulos da folha antes de reabrir.');modal('Reabrir a folha',`<p>Os holerites de ${compLabel(st.comp)} voltam a ser recalculados. Use para corrigir e fechar de novo.</p><div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-fl="reabrirok">Reabrir</button></div>`);break}
  case 'reabrirok':{const {error}=await Cloud.client.from('folha_fechamentos').delete().eq('workspace_id',Cloud.ws).eq('competencia',st.comp);if(error)return toast(error.message);await Cloud.client.from('ponto_auditoria').insert({workspace_id:Cloud.ws,acao:`Folha de ${st.comp} reaberta`,por:quem()});closeModal();await carregar(true);break}
  case 'pagar':{const T=titulos();modal('Lançar no contas a pagar',`<p>Estes títulos entram no contas a pagar (origem "folha"), seguindo a aprovação configurada:</p><div class="tablebox"><table><tbody>${T.map(t=>`<tr><td>${esc(t.descricao)}</td><td>${new Date(t.vencimento+'T12:00').toLocaleDateString('pt-BR')}</td><td class="num">${R(t.valor)}</td></tr>`).join('')}</tbody></table></div><div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-fl="pagarok">Lançar ${T.length} título(s)</button></div>`);break}
  case 'pagarok':{const T=titulos();db.payables=db.payables||[];let n=0;for(const t of T){if(db.payables.some(p=>p.id===t.id))continue;db.payables.push((window.Pagamentos?.marcar||(x=>x))(t));n++}save();
   await Cloud.client.from('folha_fechamentos').update({lancado_pagar:true}).eq('workspace_id',Cloud.ws).eq('competencia',st.comp);await Cloud.client.from('ponto_auditoria').insert({workspace_id:Cloud.ws,acao:`Folha de ${st.comp} lançada no contas a pagar`,depois:{titulos:n},por:quem()});closeModal();toast(`${n} título(s) lançados no contas a pagar.`);await carregar(true);break}
  case 'csv':{const F=folhaDoMes(st.comp),L=[['pessoa','vinculo','codigo','descricao','referencia','provento','desconto']];for(const {c,h} of F){const vv=VINC[h.colaborador.vinculo];for(const i of h.itens)L.push([c.nome,vv,i.cod,i.desc,i.ref||'',i.tipo==='p'?i.valor:'',i.tipo==='d'?i.valor:'']);L.push([c.nome,vv,'','LÍQUIDO','',h.liquido,''],[c.nome,vv,'','FGTS (empresa)','',h.fgts,''],[c.nome,vv,'','Encargos (empresa)','',h.encargos,''])}
   const txt='﻿'+L.map(r=>r.map(v=>typeof v==='number'?String(v).replace('.',','):/[;"\n]/.test(String(v))?`"${String(v).replace(/"/g,'""')}"`:v).join(';')).join('\n');baixar(new Blob([txt],{type:'text/csv;charset=utf-8'}),`folha-${st.comp}.csv`);break}
  case 'zip':{try{await carregaLib('JSZip','https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js');const z=new JSZip();for(const {h} of folhaDoMes(st.comp)){const r=await pdf(h);z.file(r.nome,r.bytes)}baixar(await z.generateAsync({type:'blob'}),`holerites-${st.comp}.zip`)}catch(x){toast(x.message)}break}
  case 'salvartab':{const p=JSON.parse(JSON.stringify(P()));for(const i of document.querySelectorAll('[data-tb]')){const path=i.dataset.tb.split('.');if(path[0]==='vigencia'){p.vigencia=i.value;continue}const v=num(i.value);let o=p;for(let j=0;j<path.length-1;j++)o=o[path[j]];o[path[path.length-1]]=v}
   const {error}=await Cloud.client.from('folha_parametros').upsert({workspace_id:Cloud.ws,dados:p,updated_at:new Date().toISOString()});if(error)return toast(error.message);await Cloud.client.from('ponto_auditoria').insert({workspace_id:Cloud.ws,acao:'Tabelas da folha alteradas',depois:{vigencia:p.vigencia},por:quem()});toast('Tabelas salvas.');await carregar(true);break}
  case 'padraotab':{const {error}=await Cloud.client.from('folha_parametros').upsert({workspace_id:Cloud.ws,dados:PADRAO,updated_at:new Date().toISOString()});if(error)return toast(error.message);toast('Tabelas padrão restauradas.');await carregar(true);break}
 }});
function titulos(){const F=folhaDoMes(st.comp).filter(x=>x.h.fechado),s=f=>r2(F.reduce((a,x)=>a+f(x),0)),v5=diaUtil5(st.comp),v20=dia20(st.comp),hoje=new Date().toISOString().slice(0,10),T=[];
 const base={origem:'folha',emissao:hoje,status:'aberto',parcela:1,parcelas:1,lancadoPor:quem(),createdBy:quem()};
 for(const {c,h} of F)if(h.liquido>0)T.push({...base,id:`FOLHA-${st.comp}-SAL-${c.id.slice(0,8)}`,fornecedor:c.nome,descricao:`${h.colaborador.vinculo==='prolabore'?'Pró-labore':h.colaborador.vinculo==='estagio'?'Bolsa de estágio':'Salário'} ${compLabel(st.comp)} · ${PT().curto(c.nome)}${c.pix?' · PIX '+c.pix:''}`,vencimento:v5,valor:h.liquido,categoria:h.colaborador.vinculo==='prolabore'?'Pró-labore':'Salários e encargos'});
 const inss=s(x=>x.h.inss+x.h.encargos),fgts=s(x=>x.h.fgts),ir=s(x=>x.h.irrf);
 if(inss>0)T.push({...base,id:`FOLHA-${st.comp}-INSS`,fornecedor:'Receita Federal',descricao:`INSS da folha ${compLabel(st.comp)} (DCTFWeb)`,vencimento:v20,valor:inss,categoria:'Salários e encargos'});
 if(fgts>0)T.push({...base,id:`FOLHA-${st.comp}-FGTS`,fornecedor:'Caixa · FGTS Digital',descricao:`FGTS ${compLabel(st.comp)}`,vencimento:v20,valor:fgts,categoria:'Salários e encargos'});
 if(ir>0)T.push({...base,id:`FOLHA-${st.comp}-IRRF`,fornecedor:'Receita Federal',descricao:`IRRF sobre salários e pró-labore ${compLabel(st.comp)} (DCTFWeb)`,vencimento:v20,valor:ir,categoria:'Impostos e taxas'});
 return T}
document.addEventListener('change',e=>{if(e.target.matches('[data-fl-comp]')&&/^\d{4}-\d{2}$/.test(e.target.value)){st.comp=e.target.value;render()}});
// Usado por Pessoas (férias e rescisão): mesmas tabelas e o mesmo IRRF (simplificado e redutor) da folha.
function irrfCalc(rend,inss,dependentes){const p=P(),legais=inss+(Number(dependentes)||0)*p.irrf_dependente,ded=Math.max(legais,p.irrf_simplificado),base=r2(Math.max(0,rend-ded));let ir=irrfTabela(base,p.irrf);if(rend<=p.redutor_isento_ate)ir=0;else if(rend<=p.redutor_ate)ir=r2(Math.max(0,ir-Math.max(0,p.redutor_a-p.redutor_b*rend)));return {ir,base}}
window.Folha={acessoLiberado:()=>{if(page==='folha')render();window.Pessoas?.acessoLiberado?.()},calcular,vigente,tabelas:()=>P(),inss:b=>inssProgressivo(b,P().inss),irrf:irrfCalc,fechamentos:()=>st.fech,garantir:()=>carregar(),parametros:()=>st.P,salvarParametros:async d=>{const {error}=await Cloud.client.from('folha_parametros').upsert({workspace_id:Cloud.ws,dados:{...P(),...d},updated_at:new Date().toISOString()});if(error)throw error;await carregar(true)}};
addPage('folha','wallet','Folha de pagamento',view,'Holerites a partir do contrato, do ponto e dos lançamentos do mês: INSS, IRRF, FGTS, encargos, guias e lançamento no contas a pagar. Só quem criou a empresa acessa.','',()=>{});
})();
