'use strict';
// Fiscal › Notas de compra (SEFAZ): NF-e emitidas contra o CNPJ da empresa, lidas direto da SEFAZ pelo Focus NFe,
// com a manifestação do destinatário e a geração das contas a pagar pelas duplicatas — sem depender do Bling.
(()=>{
const ui={filtro:'todas',busca:''};let st={notas:null,carregando:false,erro:''};
window.Reiniciar?.registrar(ui,['filtro','busca']); // estado de tela: volta ao original ao clicar no menu
const MAN={ciencia:['Ciência','info'],confirmacao:['Confirmada','ok'],desconhecimento:['Desconhecida','bad'],nao_realizada:['Não realizada','bad']};
const dBR=d=>d?new Date(d).toLocaleDateString('pt-BR'):'—';
const fmtDoc=s=>{const d=String(s||'').replace(/\D/g,'');return d.length===14?d.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,'$1.$2.$3/$4-$5'):d};
const pode=()=>['owner','member','financeiro','contador'].includes(window.Cloud?.role||'owner');
async function fn(action,body){const r=await Cloud.client.functions.invoke('integrations',{body:{workspace_id:Cloud.ws,action,...body}});if(r.error){let msg=r.error.message;try{msg=(await r.error.context.json()).error||msg}catch{}throw Error(msg)}return r.data}
async function carregar(){if(st.carregando||!window.Cloud?.ws)return;st.carregando=true;try{const {data,error}=await Cloud.client.from('nfe_recebidas').select('*').eq('workspace_id',Cloud.ws).order('emissao',{ascending:false}).limit(1000);if(error)throw error;st.notas=data||[];st.erro=''}catch(e){st.erro=e.message;st.notas=st.notas||[]}st.carregando=false;if(page==='nfrecebidas'&&!document.querySelector('.modalback'))render()}
const noBling=n=>(db.purchases||[]).some(p=>String(p.chave||'').replace(/\D/g,'')===n.chave);
function view(){if(!st.notas){carregar();return '<div class="empty">Carregando…</div>'}const q=normalized(ui.busca);
 const l=st.notas.filter(n=>({todas:true,pendentes:!n.manifestacao,confirmadas:n.manifestacao==='confirmacao',semtitulo:!n.titulos_gerados&&!noBling(n)})[ui.filtro]&&(!q||normalized([n.emitente,n.emitente_doc,n.chave,n.dados?.numero].join(' ')).includes(q)));
 const mes=st.notas.filter(n=>String(n.emissao).slice(0,7)===new Date().toISOString().slice(0,7));
 return `<div class="notice">Notas emitidas contra o CNPJ da empresa, direto da SEFAZ (não passa pelo Bling). Manifeste <b>Ciência</b> para baixar a nota completa; depois <b>Confirme</b> as compras reais e <b>Desconheça</b> o que não reconhece (protege contra nota fria em seu CNPJ). A confirmação ou o desconhecimento têm prazo legal de até 180 dias após a autorização da nota.</div>
 ${st.erro?`<div class="notice warnbox">${esc(st.erro)}</div>`:''}
 <div class="grid kpis4"><div class="card kpi"><span class="kpil">Notas no mês</span><span class="kpiv">${mes.length}</span><span class="kpis">${money(mes.reduce((a,n)=>a+Number(n.valor||0),0))}</span></div><div class="card kpi"><span class="kpil">Sem manifestação</span><span class="kpiv ${st.notas.some(n=>!n.manifestacao)?'gold':''}">${st.notas.filter(n=>!n.manifestacao).length}</span><span class="kpis">dê ciência para ver os itens</span></div><div class="card kpi"><span class="kpil">Sem contas a pagar</span><span class="kpiv">${st.notas.filter(n=>!n.titulos_gerados&&!noBling(n)&&n.manifestacao!=='desconhecimento').length}</span><span class="kpis">nem pelo Bling nem pelo Jarvis</span></div><div class="card kpi"><span class="kpil">Desconhecidas</span><span class="kpiv ${st.notas.some(n=>n.manifestacao==='desconhecimento')?'red':''}">${st.notas.filter(n=>n.manifestacao==='desconhecimento').length}</span><span class="kpis">notas que a empresa não reconhece</span></div></div>
 <div class="crmbar"><div class="segtabs">${[['todas','Todas'],['pendentes','Sem manifestação'],['confirmadas','Confirmadas'],['semtitulo','Sem contas a pagar']].map(([k,t])=>`<button class="${ui.filtro===k?'active':''}" data-nfr-f="${k}">${t}</button>`).join('')}</div><input type="search" id="nfrBusca" placeholder="Fornecedor, CNPJ, chave…" value="${esc(ui.busca)}" style="min-width:230px">${pode()?`<button class="primary small" data-nfr="sync">${icon('refresh')} Buscar na SEFAZ</button>`:''}</div>
 <div class="tablebox"><div class="tablewrap"><table><thead><tr><th>Emissão</th><th>Fornecedor</th><th class="num">Valor</th><th>Situação</th><th>Manifestação</th><th>Contas a pagar</th><th></th></tr></thead><tbody>
 ${l.map(n=>{const m=MAN[n.manifestacao];return `<tr class="clickrow" data-nfr-ver="${esc(n.chave)}"><td>${dBR(n.emissao)}</td><td><strong>${esc(n.emitente||'—')}</strong><br><span class="caption">${fmtDoc(n.emitente_doc)}</span></td><td class="num">${money(Number(n.valor)||0)}</td><td class="caption">${esc(n.situacao||'')}</td><td>${m?`<span class="badge ${m[1]}">${m[0]}</span>`:'<span class="badge warn">Pendente</span>'}</td><td>${n.titulos_gerados?'<span class="badge ok">gerados</span>':noBling(n)?'<span class="badge">pelo Bling</span>':'<span class="caption">—</span>'}</td><td>${icon('arrow')}</td></tr>`}).join('')||`<tr><td colspan="7" class="empty">${st.notas.length?'Nada neste filtro.':'Nenhuma nota lida ainda. Clique em <b>Buscar na SEFAZ</b>.'}</td></tr>`}</tbody></table></div></div>`}
async function abrir(chave){const n=st.notas.find(x=>x.chave===chave);if(!n)return;const d=n.detalhe,m=MAN[n.manifestacao];
 modal(`${esc(n.emitente||'Nota de compra')}`,`<div class="row wrap" style="gap:8px;margin-bottom:10px">${m?`<span class="badge ${m[1]}">${m[0]}</span>`:'<span class="badge warn">Sem manifestação</span>'}<span class="caption">${dBR(n.emissao)} · ${money(Number(n.valor)||0)} · ${fmtDoc(n.emitente_doc)}</span></div><p class="caption mono">Chave ${esc(n.chave)}</p>
 ${d?`<div class="tablewrap" style="max-height:230px"><table><thead><tr><th>Item</th><th>NCM</th><th>CFOP</th><th class="num">Qtd</th><th class="num">Total</th></tr></thead><tbody>${d.itens.map(i=>`<tr><td>${esc(i.descricao)}<br><span class="caption mono">${esc(i.codigo||'')}</span></td><td>${esc(i.ncm||'')}</td><td>${esc(i.cfop||'')}</td><td class="num">${i.qtd}</td><td class="num">${money(i.total)}</td></tr>`).join('')}</tbody></table></div>
  <h4 style="margin:12px 0 6px">Duplicatas</h4>${d.duplicatas.length?d.duplicatas.map(x=>`<div class="listline"><span>${esc(x.numero||'')} · vence ${new Date(x.vencimento+'T12:00:00').toLocaleDateString('pt-BR')}</span><strong>${money(x.valor)}</strong></div>`).join(''):'<p class="caption">Sem duplicatas (pagamento à vista ou fora da nota).</p>'}`
 :`<p class="caption">${n.manifestacao?'Clique em "Baixar itens" para ver produtos e duplicatas.':'Dê ciência para a SEFAZ liberar a nota completa (itens e duplicatas).'}</p>`}
 ${pode()?`<div class="modalfoot" style="justify-content:space-between;flex-wrap:wrap"><div class="row wrap" style="gap:6px">${!n.manifestacao?`<button data-nfr-man="ciencia" data-chave="${esc(n.chave)}">Dar ciência</button>`:''}${n.manifestacao!=='confirmacao'?`<button data-nfr-man="confirmacao" data-chave="${esc(n.chave)}">Confirmar compra</button>`:''}${!['desconhecimento','confirmacao'].includes(n.manifestacao)?`<button class="quiet" data-nfr-man="desconhecimento" data-chave="${esc(n.chave)}">Desconheço</button><button class="quiet" data-nfr-man="nao_realizada" data-chave="${esc(n.chave)}">Não realizada</button>`:''}</div>
 <div class="row" style="gap:6px">${n.manifestacao&&!d?`<button data-nfr-det="${esc(n.chave)}">${icon('download')} Baixar itens</button>`:''}${d&&!n.titulos_gerados&&!noBling(n)?`<button class="primary" data-nfr-tit="${esc(n.chave)}">${icon('wallet')} Gerar contas a pagar</button>`:''}<button data-action="close">Fechar</button></div></div>`:'<div class="modalfoot"><button data-action="close">Fechar</button></div>'}`)}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-nfr],[data-nfr-f],[data-nfr-ver],[data-nfr-man],[data-nfr-det],[data-nfr-tit]');if(!b)return;const d=b.dataset;
 try{if(d.nfrF){ui.filtro=d.nfrF;render();return}if(d.nfrVer){abrir(d.nfrVer);return}
 if(d.nfr==='sync'){b.disabled=true;b.textContent='Consultando a SEFAZ…';const r=await fn('nfr_sync',{});toast(`${r.lidas} nota(s) lida(s), ${r.novas} nova(s).`);st.notas=null;await carregar();return}
 if(d.nfrMan){let just;if(d.nfrMan==='nao_realizada'){just=prompt('Justificativa (mínimo 15 caracteres):');if(!just)return}
  if(['desconhecimento','nao_realizada'].includes(d.nfrMan)&&b.dataset.conf!=='1'){b.dataset.conf='1';b.textContent='Confirmar?';b.classList.add('danger');return}
  b.disabled=true;await fn('nfr_manifestar',{chave:d.chave,tipo:d.nfrMan,justificativa:just});toast('Manifestação enviada à SEFAZ.');audit('Manifestação do destinatário',`${d.nfrMan} · ${d.chave}`);closeModal();st.notas=null;await carregar();abrir(d.chave);return}
 if(d.nfrDet){b.disabled=true;b.textContent='Baixando…';await fn('nfr_detalhe',{chave:d.nfrDet});closeModal();st.notas=null;await carregar();abrir(d.nfrDet);return}
 if(d.nfrTit){const n=st.notas.find(x=>x.chave===d.nfrTit),det=n.detalhe,dup=det.duplicatas.length?det.duplicatas:[{numero:'1',vencimento:new Date().toLocaleDateString('sv-SE'),valor:Number(n.valor)}],g=uid();
  db.payables=db.payables||[];dup.forEach((x,i)=>db.payables.push((window.Pagamentos?.marcar||(y=>y))({id:`SEFAZ-${g}-${i+1}`,origem:'sefaz',fornecedor:n.emitente,fornecedorDoc:fmtDoc(n.emitente_doc),descricao:`NF ${det.numero||''} · ${n.emitente}`,documento:String(det.numero||''),parcela:i+1,parcelas:dup.length,emissao:String(n.emissao).slice(0,10),vencimento:x.vencimento,valor:round(x.valor),juros:0,desconto:0,valorPago:0,status:'aberto',categoria:'Compra de mercadorias',observacao:`Chave ${n.chave}`,createdBy:window.Cloud?.session?.user?.email||'local'})));
  await Cloud.client.from('nfe_recebidas').update({titulos_gerados:true}).eq('workspace_id',Cloud.ws).eq('chave',n.chave).then(()=>null,()=>null);n.titulos_gerados=true;audit('Contas a pagar geradas da nota da SEFAZ',`${n.emitente} · ${dup.length} parcela(s) · ${money(Number(n.valor))}`);save();closeModal();render();toast(`${dup.length} conta(s) a pagar criada(s).`)}}
 catch(x){toast(x.message);b.disabled=false}});
document.addEventListener('input',e=>{if(e.target.id!=='nfrBusca')return;ui.busca=e.target.value;const p=e.target.selectionStart;render();const n=$('#nfrBusca');n.focus();n.setSelectionRange(p,p)});
addPage('nfrecebidas','receipt','Notas de compra (SEFAZ)',view,'NF-e emitidas contra o CNPJ da empresa, direto da SEFAZ: manifestação do destinatário e contas a pagar pelas duplicatas.','',()=>{});
window.NfRecebidas={avisos:()=>{const n=(st.notas||[]).filter(x=>!x.manifestacao).length;return n?[['warn','receipt',`${n} nota(s) de compra sem manifestação`,'Dê ciência para baixar itens e duplicatas','nfrecebidas']]:[]}};
})();
