'use strict';
// Pessoas (só o criador, como a Folha): admissão com os dados do eSocial, férias (períodos, programação, cálculo, aviso e
// recibo), rescisão (verbas, TRCT, multa do FGTS) e eventos do eSocial gerados e guardados PRONTOS — sem transmissão
// (conectar exige certificado e cadastro no eSocial; a transmissão fica para quando o dono ligar).
// Regras trabalhistas de referência: CLT arts. 130–146 (férias), 477 (prazo 10 dias), 479 (experiência), 484-A (acordo),
// Lei 12.506/2011 (aviso proporcional), Súmulas TST 261 (férias proporcionais no pedido de demissão) e 305 (FGTS no aviso).
(()=>{
Object.assign(paths,{pessoas:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8z M22 21v-2a4 4 0 0 0-3-3.87 M16 3.13a4 4 0 0 1 0 7.75'});
const st={aba:'pessoas',ok:false,carregando:false,ferias:[],resc:[],eventos:[]};
const pad=n=>String(n).padStart(2,'0'),r2=v=>Math.round((Number(v)||0)*100)/100,R=v=>money(r2(v)),dig=s=>String(s||'').replace(/\D/g,'');
const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,dt=s=>new Date(s+'T12:00:00'),br=s=>s?dt(s).toLocaleDateString('pt-BR'):'—';
const addDias=(s,n)=>{const d=dt(s);d.setDate(d.getDate()+n);return iso(d)},addMeses=(s,n)=>{const d=dt(s),dia=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n);d.setDate(Math.min(dia,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return iso(d)};
const hoje=()=>iso(new Date()),quem=()=>window.Cloud?.session?.user?.email||'criador';
const PT=()=>window.Ponto,FL=()=>window.Folha,colabs=()=>PT()?.estado?.().colabs||[],C=id=>colabs().find(c=>c.id===id);
const contrato=(c,data)=>FL()?.vigente?FL().vigente(c,(data||hoje()).slice(0,7)):c;
const VINC={clt:'CLT',prolabore:'Pró-labore',estagio:'Estágio'};
const cpfOk=v=>{const s=dig(v);if(s.length!==11||/^(\d)\1+$/.test(s))return false;for(const t of [9,10]){let n=0;for(let i=0;i<t;i++)n+=Number(s[i])*(t+1-i);if(((n*10)%11)%10!==Number(s[t]))return false}return true};
const empregador=()=>{const p=FL()?.parametros?.()?.empregador||{},f=db.gerencial?.fiscal||{};return {razao:'',cnpj:f.cnpj||'65193225000157',endereco:'',municipio:f.municipio||'Timbó',ibge:'',uf:f.uf||'SC',cep:'',...p}};

async function carregar(forca){if(st.carregando||(!forca&&st.ok)||!window.Cloud?.ws)return;st.carregando=true;const c=Cloud.client,ws=Cloud.ws;
 try{await PT()?.garantir?.();await FL()?.garantir?.();const [a,b,d]=await Promise.all([c.from('folha_ferias').select('*').eq('workspace_id',ws).order('gozo_ini'),c.from('folha_rescisoes').select('*').eq('workspace_id',ws).order('data_desligamento'),c.from('esocial_eventos').select('workspace_id,id,colaborador_id,evento,referencia,descricao,status,recibo,created_at').eq('workspace_id',ws).order('created_at',{ascending:false})]);
  for(const x of [a,b,d])if(x.error)throw x.error;Object.assign(st,{ferias:a.data,resc:b.data,eventos:d.data,ok:true})}catch(x){toast('Pessoas: '+(x.message||x))}st.carregando=false;if(page==='pessoas'&&!document.querySelector('.modalback'))render()}
async function auditar(colab,acao,depois){await Cloud.client.from('ponto_auditoria').insert({workspace_id:Cloud.ws,colaborador_id:colab,acao,depois,por:quem()})}

// ── Férias ──
function admissaoClt(c){return c.proximo_vinculo==='clt'&&c.proximo_em?c.proximo_em:c.vinculo==='clt'?c.admissao:null}
function periodos(c){const adm=admissaoClt(c);if(!adm)return [];const out=[];let ini=adm;const lim=hoje();
 while(ini<=lim||out.length===0){const fim=addDias(addMeses(ini,12),-1),conc=addDias(addMeses(fim,12),0),goz=st.ferias.filter(f=>f.colaborador_id===c.id&&f.aquisitivo_ini===ini&&f.status!=='cancelada');
  const usados=goz.reduce((a,f)=>a+f.dias+f.abono_dias,0),saldo=Math.max(0,30-usados),estado=fim>=lim?'em aquisição':saldo===0?'concluído':conc<lim?'vencido (pagar em dobro)':addMeses(lim,2)>=conc?'vence em breve':'a gozar';
  out.push({ini,fim,conc,usados,saldo,estado,goz});ini=addDias(fim,1);if(out.length>40)break}
 return out}
function mediaVariaveis(c){const F=(FL()?.fechamentos?.()||[]).filter(f=>f.colaborador_id===c.id).sort((a,b)=>b.competencia.localeCompare(a.competencia)).slice(0,12);if(!F.length)return 0;
 return r2(F.reduce((a,f)=>a+(f.holerite?.itens||[]).filter(i=>['010','011','012'].includes(i.cod)).reduce((b,i)=>b+i.valor,0),0)/12)}
function calcFerias(c,{gozo_ini,dias,abono_dias,adiantar_13}){const k=contrato(c,gozo_ini),sal=Number(k.salario)||0,med=mediaVariaveis(c),base=sal+med;
 const ferias=r2(base/30*dias),terco=r2(ferias/3),abono=r2(base/30*abono_dias),tercoAbono=r2(abono/3),adi13=adiantar_13?r2(sal/2):0;
 const inss=FL().inss(ferias+terco),{ir}=FL().irrf(ferias+terco,inss,c.dependentes_ir||0),liquido=r2(ferias+terco+abono+tercoAbono+adi13-inss-ir),fgts=r2((ferias+terco)*(FL().tabelas().fgts||8)/100);
 const av=[];const w=dt(gozo_ini).getDay();if(w===5||w===6)av.push('Início na sexta ou no sábado: a CLT (art. 134, §3º) proíbe começar nos 2 dias antes do descanso semanal ou de feriado.');
 if(dias<14&&!st.ferias.some(f=>f.colaborador_id===c.id&&f.dias>=14&&f.status!=='cancelada'))av.push('Se as férias forem fracionadas, um dos períodos precisa ter pelo menos 14 dias (art. 134, §1º).');
 if(med)av.push(`Inclui média de horas extras dos últimos 12 meses (${R(med)}).`);
 return {base,salario:sal,media:med,itens:[['Férias',`${dias} dias`,ferias,'p'],['1/3 constitucional','',terco,'p'],...(abono?[['Abono pecuniário',`${abono_dias} dias`,abono,'p'],['1/3 sobre abono','',tercoAbono,'p']]:[]),...(adi13?[['Adiantamento 13º salário','50%',adi13,'p']]:[]),['INSS sobre férias','',inss,'d'],['IRRF sobre férias','',ir,'d']].filter(i=>i[2]>0||i[3]==='d'),bruto:r2(ferias+terco+abono+tercoAbono+adi13),inss,irrf:ir,liquido,fgts,avisos:av}}

// ── Rescisão ──
const TIPOS={sem_justa_causa:'Dispensa sem justa causa',justa_causa:'Dispensa por justa causa',pedido_demissao:'Pedido de demissão',acordo:'Acordo (art. 484-A)',termino_experiencia:'Término do contrato de experiência',antecipada_experiencia_empregador:'Término antecipado da experiência pelo empregador (art. 479)',termino_contrato:'Término de contrato por prazo determinado'};
const MOTIVO_ESOCIAL={sem_justa_causa:'02',justa_causa:'01',pedido_demissao:'07',acordo:'33',termino_experiencia:'06',antecipada_experiencia_empregador:'03',termino_contrato:'06'};
function mesesAvos(ini,fim){// avos: cada mês do ano com 15 dias ou mais trabalhados
 // dias em calendário puro (UTC), sem horário: um mês com 14 dias não pode virar 15.
 const U=x=>{const [y,m,d]=x.split('-').map(Number);return Date.UTC(y,m-1,d)},a=U(ini),b=U(fim);let n=0;const ya=Number(ini.slice(0,4)),ma=Number(ini.slice(5,7))-1;
 for(let k=0;;k++){const m0=Date.UTC(ya,ma+k,1);if(m0>b)break;const m1=Date.UTC(ya,ma+k+1,0),x0=Math.max(m0,a),x1=Math.min(m1,b);if(x1>=x0&&(x1-x0)/864e5+1>=15)n++}return n}
function calcRescisao(c,{data_desligamento:d,tipo,aviso,saldo_fgts}){const adm=admissaoClt(c)||c.admissao;if(!adm)return {erro:'Cadastre a data de admissão (CLT) no contrato.'};const k=contrato(c,d),sal=Number(k.salario)||0,it=[],av=[];
 const add=(cod,desc,ref,valor,tipo_,inc)=>{valor=r2(valor);if(valor>0)it.push({cod,desc,ref,valor,tipo:tipo_,inc})};
 const anos=Math.floor(mesesAvos(adm,d)/12),empregador=['sem_justa_causa','acordo'].includes(tipo),justa=tipo==='justa_causa';
 const avisoDias=empregador?Math.min(90,30+3*anos):30,indeniza=empregador&&aviso==='indenizado',diasAviso=indeniza?(tipo==='acordo'?Math.floor(avisoDias/2):avisoDias):0,projetada=indeniza?addDias(d,avisoDias):d;
 const diaMes=Number(d.slice(8)),saldoSal=sal/30*Math.min(30,diaMes);add('50','Saldo de salário',`${Math.min(30,diaMes)} dias`,saldoSal,'p','inss_ir_fgts');
 if(indeniza)add('69','Aviso prévio indenizado',`${diasAviso} dias${tipo==='acordo'?' (50% no acordo)':''}`,sal/30*diasAviso,'p','fgts');
 if(tipo==='antecipada_experiencia_empregador'){const fimExp=addDias(addDias(adm,(c.experiencia_dias||45)+(c.experiencia_prorrogacao||0)),-1),rest=Math.max(0,Math.round((dt(fimExp)-dt(d))/864e5));add('51','Indenização art. 479 (50% dos dias restantes)',`${rest} dias`,sal/30*rest/2,'p','')}
 if(!justa){const ano=d.slice(0,4),ini13=adm>`${ano}-01-01`?adm:`${ano}-01-01`,av13=Math.min(12,mesesAvos(ini13,projetada));add('63','13º salário proporcional',`${av13}/12`,sal/12*av13,'p','13')}
 // Férias: vencidas (períodos completos com saldo) e proporcionais (período em curso)
 const P=periodos({...c,admissao:adm}).filter(p=>p.ini<=d);let ferV=0,ferP=0,avosP=0;
 for(const p of P){if(p.fim<=d&&p.saldo>0){const dobro=p.conc<d;ferV+=sal/30*p.saldo*(dobro?2:1);if(dobro)av.push(`Férias do período ${br(p.ini)}–${br(p.fim)} vencidas: pagas em dobro (art. 137).`)}else if(p.fim>d&&!justa){avosP=Math.min(12,mesesAvos(p.ini,projetada));ferP=sal/12*avosP}}
 add('66','Férias vencidas','',ferV,'p','');add('65','Férias proporcionais',`${avosP}/12`,ferP,'p','');add('68','1/3 constitucional de férias','',(ferV+ferP)/3,'p','');
 if(tipo==='pedido_demissao'&&aviso==='nao_cumprido')add('103','Aviso prévio não cumprido (desconto)','30 dias',sal,'d','');
 const baseInss=it.filter(i=>i.inc==='inss_ir_fgts').reduce((a,i)=>a+i.valor,0)-it.filter(i=>i.tipo==='d'&&i.cod==='103').reduce((a,i)=>a+i.valor,0),b13=it.filter(i=>i.inc==='13').reduce((a,i)=>a+i.valor,0);
 const inss=FL().inss(Math.max(0,baseInss)),inss13=FL().inss(b13),ir=FL().irrf(Math.max(0,baseInss),inss,c.dependentes_ir||0).ir,ir13=FL().irrf(b13,inss13,c.dependentes_ir||0).ir;
 add('112.1','INSS sobre salário','',inss,'d','');add('112.2','INSS sobre 13º salário','',inss13,'d','');add('114.1','IRRF','',ir,'d','');add('114.2','IRRF sobre 13º salário','',ir13,'d','');
 const bruto=r2(it.filter(i=>i.tipo==='p').reduce((a,i)=>a+i.valor,0)),desc=r2(it.filter(i=>i.tipo==='d').reduce((a,i)=>a+i.valor,0));
 const baseFgts=it.filter(i=>['inss_ir_fgts','fgts','13'].includes(i.inc)).reduce((a,i)=>a+i.valor,0),fgtsMes=r2(baseFgts*(FL().tabelas().fgts||8)/100),pctMulta=tipo==='sem_justa_causa'||tipo==='antecipada_experiencia_empregador'?40:tipo==='acordo'?20:0,multa=r2(((Number(saldo_fgts)||0)+fgtsMes)*pctMulta/100);
 if(tipo==='acordo')av.push('Acordo: saque de 80% do FGTS e sem direito ao seguro-desemprego.');if(pctMulta===40)av.push('Direito a seguro-desemprego (se cumprir os requisitos) e saque do FGTS.');
 if(!Number(saldo_fgts)&&pctMulta)av.push('Informe o saldo do FGTS (extrato da conta vinculada) para calcular a multa corretamente.');
 av.push('Aviso prévio indenizado e férias indenizadas tratados como isentos de INSS e IRRF; confira com a contabilidade antes de pagar.');
 return {itens:it,bruto,descontos:desc,liquido:r2(bruto-desc),fgts_mes:fgtsMes,multa_fgts:multa,pct_multa:pctMulta,aviso_dias:avisoDias,projetada,pagamento_ate:addDias(d,10),anos,avisos:av,salario:sal,admissao:adm}}

// ── eSocial (só gera e guarda) ──
const xe=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[ch]));
const tag=(n,v)=>v==null||v===''?'':`<${n}>${xe(v)}</${n}>`;
function idEvento(seq){const e=empregador(),d=new Date();return `ID1${dig(e.cnpj).padEnd(14,'0')}${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}${String(seq).padStart(5,'0')}`}
const NS=ev=>`http://www.esocial.gov.br/schema/evt/${ev}/v_S_01_02_00`;
function ideEvento(){return `<ideEvento><indRetif>1</indRetif><tpAmb>2</tpAmb><procEmi>1</procEmi><verProc>Jarvis-1.0</verProc></ideEvento><ideEmpregador><tpInsc>1</tpInsc><nrInsc>${dig(empregador().cnpj).slice(0,8)}</nrInsc></ideEmpregador>`}
function s2200(c){const k=contrato(c,admissaoClt(c)||c.admissao),e=c.endereco||{},exp=c.tipo_contrato==='experiencia',adm=admissaoClt(c)||c.admissao;
 return `<eSocial xmlns="${NS('evtAdmissao')}"><evtAdmissao Id="${idEvento(1)}">${ideEvento()}<trabalhador>${tag('cpfTrab',dig(c.cpf))}${tag('nmTrab',c.nome)}${tag('sexo',c.sexo)}${tag('racaCor',c.raca_cor||6)}${tag('estCiv',c.estado_civil)}${tag('grauInstr',c.grau_instrucao||'07')}<nascimento>${tag('dtNascto',c.nascimento)}<paisNascto>105</paisNascto><paisNac>105</paisNac></nascimento><endereco><brasil>${tag('dscLograd',e.logradouro)}${tag('nrLograd',e.numero||'S/N')}${tag('complemento',e.complemento)}${tag('bairro',e.bairro)}${tag('cep',dig(e.cep))}${tag('codMunic',e.ibge)}${tag('uf',e.uf)}</brasil></endereco>${c.telefone||c.email?`<contato>${tag('fonePrinc',dig(c.telefone))}${tag('emailPrinc',c.email)}</contato>`:''}</trabalhador>`+
 `<vinculo>${tag('matricula',c.matricula||dig(c.cpf))}<tpRegTrab>1</tpRegTrab><tpRegPrev>1</tpRegPrev><cadIni>N</cadIni><infoRegimeTrab><infoCeletista>${tag('dtAdm',adm)}<tpAdmissao>1</tpAdmissao><indAdmissao>1</indAdmissao><tpRegJor>1</tpRegJor><natAtividade>1</natAtividade></infoCeletista></infoRegimeTrab>`+
 `<infoContrato>${tag('nmCargo',c.cargo||'Auxiliar')}${tag('CBOCargo',dig(c.cbo))}<codCateg>101</codCateg><remuneracao>${tag('vrSalFx',r2(k.salario).toFixed(2))}<undSalFixo>5</undSalFixo></remuneracao><duracao><tpContr>${exp?2:1}</tpContr>${exp?tag('dtTerm',addDias(adm,(c.experiencia_dias||45)-1)):''}${exp?'<clauAssec>N</clauAssec>':''}</duracao><localTrabalho><localTrabGeral><tpInsc>1</tpInsc>${tag('nrInsc',dig(empregador().cnpj))}</localTrabGeral></localTrabalho><horContratual>${tag('qtdHrsSem',Number(c.horas_semanais||44).toFixed(2))}<tpJornada>2</tpJornada><tmpParc>0</tmpParc><horNoturno>N</horNoturno>${tag('dscJorn',`${String(c.entrada).slice(0,5)} às ${String(c.saida).slice(0,5)}, intervalo de ${c.intervalo_min} min`)}</horContratual></infoContrato></vinculo></evtAdmissao></eSocial>`}
function s2299(c,r,calc){return `<eSocial xmlns="${NS('evtDeslig')}"><evtDeslig Id="${idEvento(1)}">${ideEvento()}<ideVinculo>${tag('cpfTrab',dig(c.cpf))}${tag('matricula',c.matricula||dig(c.cpf))}</ideVinculo><infoDeslig>${tag('mtvDeslig',MOTIVO_ESOCIAL[r.tipo])}${tag('dtDeslig',r.data_desligamento)}<indPagtoAPI>${r.aviso==='indenizado'?'S':'N'}</indPagtoAPI>${r.aviso==='indenizado'?tag('dtProjFimAPI',calc.projetada):''}<pensAlim>0</pensAlim><verbasResc><dmDev><ideDmDev>RESC${r.data_desligamento.replace(/-/g,'')}</ideDmDev><infoPerApur><ideEstabLot><tpInsc>1</tpInsc>${tag('nrInsc',dig(empregador().cnpj))}<codLotacao>01</codLotacao>${calc.itens.map(i=>`<detVerbas>${tag('codRubr','R'+i.cod.replace('.','_'))}<ideTabRubr>JARVIS</ideTabRubr>${tag('vrRubr',i.valor.toFixed(2))}</detVerbas>`).join('')}</ideEstabLot></infoPerApur></dmDev></verbasResc></infoDeslig></evtDeslig></eSocial>`}
function s1200(c,f){const h=f.holerite,cat=h.colaborador.vinculo==='prolabore'?723:101;return `<eSocial xmlns="${NS('evtRemun')}"><evtRemun Id="${idEvento(1)}"><ideEvento><indRetif>1</indRetif><indApuracao>1</indApuracao>${tag('perApur',f.competencia)}<indGuia>1</indGuia><tpAmb>2</tpAmb><procEmi>1</procEmi><verProc>Jarvis-1.0</verProc></ideEvento><ideEmpregador><tpInsc>1</tpInsc><nrInsc>${dig(empregador().cnpj).slice(0,8)}</nrInsc></ideEmpregador><ideTrabalhador>${tag('cpfTrab',dig(c.cpf))}</ideTrabalhador><dmDev><ideDmDev>FOLHA${f.competencia.replace('-','')}</ideDmDev>${tag('codCateg',cat)}<infoPerApur><ideEstabLot><tpInsc>1</tpInsc>${tag('nrInsc',dig(empregador().cnpj))}<codLotacao>01</codLotacao><remunPerApur>${cat===101?tag('matricula',c.matricula||dig(c.cpf)):''}${h.itens.map(i=>`<itensRemun>${tag('codRubr','R'+i.cod)}<ideTabRubr>JARVIS</ideTabRubr>${tag('vrRubr',i.valor.toFixed(2))}<indApurIR>0</indApurIR></itensRemun>`).join('')}</remunPerApur></ideEstabLot></infoPerApur></dmDev></evtRemun></eSocial>`}
function s1210(c,f,dtPgto){return `<eSocial xmlns="${NS('evtPgtos')}"><evtPgtos Id="${idEvento(1)}"><ideEvento><indRetif>1</indRetif>${tag('perApur',f.competencia)}<indGuia>1</indGuia><tpAmb>2</tpAmb><procEmi>1</procEmi><verProc>Jarvis-1.0</verProc></ideEvento><ideEmpregador><tpInsc>1</tpInsc><nrInsc>${dig(empregador().cnpj).slice(0,8)}</nrInsc></ideEmpregador><ideBenef>${tag('cpfBenef',dig(c.cpf))}<infoPgto>${tag('dtPgto',dtPgto)}<tpPgto>1</tpPgto>${tag('perRef',f.competencia)}<ideDmDev>FOLHA${f.competencia.replace('-','')}</ideDmDev>${tag('vrLiq',Number(f.liquido).toFixed(2))}</infoPgto></ideBenef></evtPgtos></eSocial>`}
function s1299(comp){return `<eSocial xmlns="${NS('evtFechaEvPer')}"><evtFechaEvPer Id="${idEvento(1)}"><ideEvento><indApuracao>1</indApuracao>${tag('perApur',comp)}<indGuia>1</indGuia><tpAmb>2</tpAmb><procEmi>1</procEmi><verProc>Jarvis-1.0</verProc></ideEvento><ideEmpregador><tpInsc>1</tpInsc><nrInsc>${dig(empregador().cnpj).slice(0,8)}</nrInsc></ideEmpregador><infoFech><evtRemun>S</evtRemun><evtComProd>N</evtComProd><evtContratAvNP>N</evtContratAvNP><evtInfoComplPer>N</evtInfoComplPer></infoFech></evtFechaEvPer></eSocial>`}
async function guardarEvento(evento,colab,ref,descricao,xml){const id=(xml.match(/Id="([^"]+)"/)||[])[1]||('ID'+Date.now());const {error}=await Cloud.client.from('esocial_eventos').insert({workspace_id:Cloud.ws,id,colaborador_id:colab,evento,referencia:ref,descricao,xml});if(error)throw error;return id}
function pendenciasEsocial(c){const f=[];if(!cpfOk(c.cpf))f.push('CPF');if(!c.nascimento)f.push('nascimento');if(!c.sexo)f.push('sexo');if(!c.endereco?.cep||!c.endereco?.ibge)f.push('endereço com CEP');if(!dig(c.cbo))f.push('CBO');if(!(admissaoClt(c)||c.admissao))f.push('admissão');return f}

// ── Telas ──
const k=(t,v,s,c='')=>`<div class="card kpi"><span class="kpil">${t}</span><span class="kpiv ${c}">${v}</span><span class="kpis">${s}</span></div>`;
function pessoasView(){const L=colabs();const alertas=[];for(const c of L.filter(x=>x.ativo)){const exp=c.tipo_contrato==='experiencia'&&admissaoClt(c)?addDias(admissaoClt(c),(c.experiencia_dias||45)-1):null;if(exp&&exp>=hoje()&&exp<=addDias(hoje(),15))alertas.push(`${PT().curto(c.nome)}: experiência termina em ${br(exp)} — prorrogar ou efetivar.`);for(const p of periodos(c))if(/vencido|vence em breve/.test(p.estado))alertas.push(`${PT().curto(c.nome)}: férias do período ${br(p.ini)}–${br(p.fim)} ${p.estado} (limite ${br(p.conc)}).`)}
 return `<div class="row wrap" style="gap:8px;margin-bottom:14px"><button class="primary small" data-ps="admitir">${icon('plus')} Nova admissão</button><button class="small" data-ps="empregador">Dados do empregador</button><span class="caption">Quem entra aqui aparece também no Ponto e na Folha.</span></div>
 ${alertas.map(a=>`<div class="notice" style="margin-bottom:8px">${esc(a)}</div>`).join('')}
 <div class="tablebox" style="overflow-x:auto"><table><thead><tr><th>Pessoa</th><th>Vínculo</th><th>Admissão</th><th>Cargo / CBO</th><th class="num">Salário</th><th>Contrato</th><th>eSocial</th><th></th></tr></thead><tbody>
 ${L.map(c=>{const k2=contrato(c),pend=pendenciasEsocial(c);return `<tr><td><b>${esc(c.nome)}</b>${c.ativo?'':' <span class="badge">inativa</span>'}${c.demissao?`<br><small class="caption">desligada em ${br(c.demissao)}</small>`:''}</td><td>${VINC[k2.vinculo]}${c.proximo_em?`<br><small class="caption">→ ${VINC[c.proximo_vinculo]} em ${br(c.proximo_em)}</small>`:''}</td><td>${br(admissaoClt(c)||c.admissao)}</td><td>${esc(c.cargo||'—')}${c.cbo?`<br><small class="caption">CBO ${esc(c.cbo)}</small>`:''}</td><td class="num">${R(k2.salario)}</td><td>${c.tipo_contrato==='experiencia'?`Experiência ${c.experiencia_dias||45}${c.experiencia_prorrogacao?'+'+c.experiencia_prorrogacao:''} dias`:c.tipo_contrato==='determinado'?'Prazo determinado':'Indeterminado'}</td><td>${pend.length?`<span class="badge warn" title="Falta: ${esc(pend.join(', '))}">faltam ${pend.length} dado(s)</span>`:'<span class="badge ok">completo</span>'}</td><td class="row" style="gap:6px"><button class="small" data-ps-ficha="${c.id}">Ficha</button><button class="small quiet" data-ps-docs="${c.id}">PDFs</button></td></tr>`}).join('')}</tbody></table></div>`}
function feriasView(){const L=colabs().filter(c=>admissaoClt(c));if(!L.length)return '<div class="empty">Férias valem para empregados CLT. Cadastre a admissão CLT (ou a mudança programada para CLT) em Colaboradores.</div>';
 return `${L.map(c=>{const P=periodos(c);return `<section class="card" style="margin-bottom:12px"><div class="row" style="justify-content:space-between;flex-wrap:wrap;gap:8px"><h3 style="margin:0">${esc(c.nome)}</h3><button class="small primary" data-ps-ferias="${c.id}">Programar férias</button></div>
  <div class="tablebox" style="margin-top:10px;overflow-x:auto"><table><thead><tr><th>Período aquisitivo</th><th>Conceder até</th><th class="num">Saldo</th><th>Situação</th><th>Programadas</th></tr></thead><tbody>${P.map(p=>`<tr><td>${br(p.ini)} a ${br(p.fim)}</td><td>${br(p.conc)}</td><td class="num">${p.saldo} dias</td><td><span class="badge ${/vencido/.test(p.estado)?'bad':/breve/.test(p.estado)?'warn':p.estado==='concluído'?'ok':''}">${p.estado}</span></td><td>${p.goz.map(f=>`<button class="small quiet" data-ps-verf="${f.id}">${br(f.gozo_ini)} · ${f.dias}d${f.abono_dias?' + '+f.abono_dias+' abono':''} · ${f.status}</button>`).join(' ')||'—'}</td></tr>`).join('')}</tbody></table></div></section>`}).join('')}`}
function rescView(){return `<div class="row wrap" style="gap:8px;margin-bottom:14px"><button class="primary small" data-ps="rescindir">Calcular rescisão</button><span class="caption">Cálculo das verbas, prazo de pagamento (10 dias), multa do FGTS e evento S-2299 do eSocial.</span></div>
 ${st.resc.length?`<div class="tablebox"><table><thead><tr><th>Pessoa</th><th>Desligamento</th><th>Tipo</th><th class="num">Líquido</th><th>Pagar até</th><th>Situação</th><th></th></tr></thead><tbody>${st.resc.map(r=>`<tr><td>${esc(C(r.colaborador_id)?.nome||'—')}</td><td>${br(r.data_desligamento)}</td><td>${TIPOS[r.tipo]}</td><td class="num">${R(r.calculo?.liquido)}</td><td>${br(r.pagamento_ate)}</td><td><span class="badge ${r.status==='paga'?'ok':'warn'}">${r.status}</span></td><td><button class="small" data-ps-verr="${r.id}">Ver / TRCT</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="caption">Nenhuma rescisão calculada.</p>'}`}
function esocialView(){const F=(FL()?.fechamentos?.()||[]),comps=[...new Set(F.map(f=>f.competencia))].sort().reverse();
 return `<div class="notice"><b>Pronto para conectar, ainda desligado.</b> O Jarvis gera e guarda os eventos (admissão S-2200, desligamento S-2299, remuneração S-1200, pagamentos S-1210 e fechamento S-1299). Para transmitir falta: certificado digital da empresa no servidor, cadastro no eSocial/procuração e os eventos de tabela (S-1000, S-1005, S-1010 com as rubricas). Os XMLs seguem o leiaute S-1.2; valide no validador do eSocial antes de ligar.</div>
 <div class="row wrap" style="gap:8px;margin:12px 0">${comps.length?`<select id="psComp">${comps.map(c=>`<option>${c}</option>`).join('')}</select><button class="small" data-ps="gerar1200">Gerar S-1200, S-1210 e S-1299 da competência</button>`:'<span class="caption">Feche uma folha para gerar os eventos de remuneração.</span>'}</div>
 ${st.eventos.length?`<div class="tablebox" style="overflow-x:auto"><table><thead><tr><th>Evento</th><th>Pessoa</th><th>Referência</th><th>Descrição</th><th>Situação</th><th></th></tr></thead><tbody>${st.eventos.map(e=>`<tr><td><b>${esc(e.evento)}</b></td><td>${esc(C(e.colaborador_id)?.nome||'—')}</td><td>${esc(e.referencia||'')}</td><td><small>${esc(e.descricao||'')}</small></td><td><span class="badge ${e.status==='pronto'?'info':e.status==='processado'?'ok':e.status==='erro'?'bad':''}">${e.status}</span></td><td><button class="small quiet" data-ps-xml="${esc(e.id)}">XML</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="caption">Nenhum evento gerado ainda.</p>'}`}
function view(){const a=PT()?.acesso;if(a===null||a===undefined){PT()?.garantir?.();return '<div class="empty">Verificando acesso…</div>'}if(!a)return '<div class="notice">Esta área é exclusiva de quem criou a empresa no Jarvis.</div>';
 if(!st.ok){carregar();return '<div class="empty">Carregando…</div>'}const A=[['pessoas','Colaboradores'],['ferias','Férias'],['resc','Rescisões'],['esocial','eSocial']];
 return `<div class="segtabs">${A.map(([id,t])=>`<button class="${st.aba===id?'active':''}" data-ps-aba="${id}">${t}</button>`).join('')}</div>${({pessoas:pessoasView,ferias:feriasView,resc:rescView,esocial:esocialView}[st.aba])()}`}

// ── Admissão (ficha completa) ──
const OPT=(l,v)=>l.map(([k,t])=>`<option value="${k}" ${String(v)===String(k)?'selected':''}>${t}</option>`).join('');
const INSTR=[['01','Analfabeto'],['05','Fundamental completo'],['06','Médio incompleto'],['07','Médio completo'],['08','Superior incompleto'],['09','Superior completo'],['10','Pós-graduação'],['11','Mestrado'],['12','Doutorado']];
function ficha(id){const c=id?C(id):{nome:'',vinculo:'clt',salario:0,entrada:'07:30',saida:'17:18',intervalo_min:60,dias_semana:[1,2,3,4,5],tipo_contrato:'experiencia',experiencia_dias:45,experiencia_prorrogacao:45,horas_semanais:44,endereco:{},banco:{},admissao:hoje(),ativo:true,politica_horas:'banco',dependentes_ir:0,vale_transporte:0};const e=c.endereco||{},b=c.banco||{};
 const f=(idc,rot,val,extra='')=>`<div><label for="${idc}">${rot}</label><input id="${idc}" value="${esc(val??'')}" ${extra}></div>`;
 modal(id?`Ficha · ${esc(c.nome)}`:'Nova admissão',`<div class="psficha"><h4>Dados pessoais</h4><div class="grid three" style="gap:8px">${f('fN','Nome completo *',c.nome)}${f('fCpf','CPF *',c.cpf,'inputmode="numeric"')}${f('fPis','PIS/NIS',c.pis,'inputmode="numeric"')}${f('fNasc','Nascimento *',c.nascimento,'type="date"')}
  <div><label for="fSexo">Sexo *</label><select id="fSexo"><option value=""></option>${OPT([['F','Feminino'],['M','Masculino']],c.sexo)}</select></div><div><label for="fEC">Estado civil</label><select id="fEC">${OPT([[1,'Solteiro(a)'],[2,'Casado(a)'],[3,'Divorciado(a)'],[4,'Separado(a)'],[5,'Viúvo(a)']],c.estado_civil||1)}</select></div>
  <div><label for="fRaca">Raça/cor</label><select id="fRaca">${OPT([[1,'Branca'],[2,'Preta'],[3,'Parda'],[4,'Amarela'],[5,'Indígena'],[6,'Não informado']],c.raca_cor||6)}</select></div><div><label for="fInstr">Escolaridade</label><select id="fInstr">${OPT(INSTR,c.grau_instrucao||'07')}</select></div>${f('fRg','RG',c.rg)}</div>
  <h4>Endereço e contato</h4><div class="grid three" style="gap:8px">${f('fCep','CEP',e.cep,'inputmode="numeric"')}${f('fLog','Logradouro',e.logradouro)}${f('fNum','Número',e.numero)}${f('fCompl','Complemento',e.complemento)}${f('fBairro','Bairro',e.bairro)}${f('fCid','Cidade',e.cidade)}${f('fUf','UF',e.uf,'maxlength="2"')}${f('fIbge','Código IBGE do município',e.ibge,'inputmode="numeric"')}${f('fTel','Telefone',c.telefone)}${f('fEmail','E-mail',c.email,'type="email"')}</div>
  <h4>Contrato</h4><div class="grid three" style="gap:8px"><div><label for="fVinc">Vínculo</label><select id="fVinc">${OPT(Object.entries(VINC),c.vinculo)}</select></div>${f('fAdm','Admissão *',admissaoClt(c)||c.admissao,'type="date"')}${f('fMat','Matrícula',c.matricula)}${f('fCargo','Cargo',c.cargo)}${f('fCbo','CBO',c.cbo,'inputmode="numeric" placeholder="ex.: 411005"')}${f('fDep','Departamento',c.departamento)}
  ${f('fSal','Salário (R$) *',Number(c.salario)?String(c.salario).replace('.',','):'','inputmode="decimal"')}<div><label for="fTipo">Tipo de contrato</label><select id="fTipo">${OPT([['experiencia','Experiência'],['indeterminado','Prazo indeterminado'],['determinado','Prazo determinado']],c.tipo_contrato)}</select></div><div class="row" style="gap:6px">${f('fExp','Experiência (dias)',c.experiencia_dias||45,'type="number" min="1" max="90"')}${f('fProrr','Prorrogação (dias)',c.experiencia_prorrogacao||0,'type="number" min="0" max="89"')}</div>
  ${f('fEnt','Entrada',String(c.entrada).slice(0,5),'type="time"')}${f('fSai','Saída',String(c.saida).slice(0,5),'type="time"')}${f('fInt','Intervalo (min)',c.intervalo_min,'type="number"')}${f('fHs','Horas semanais',c.horas_semanais||44,'type="number" step="0.5"')}${f('fDepIr','Dependentes para IR',c.dependentes_ir||0,'type="number" min="0"')}${f('fVt','Vale-transporte (R$/mês)',Number(c.vale_transporte)?String(c.vale_transporte).replace('.',','):'','inputmode="decimal"')}</div>
  <h4>Pagamento</h4><div class="grid three" style="gap:8px">${f('fBco','Banco',b.banco)}${f('fAg','Agência',b.agencia)}${f('fCc','Conta',b.conta)}${f('fPix','Chave PIX',c.pix)}</div>
  <p class="caption" style="margin-top:8px">Campos com * são exigidos pelo eSocial. Ao salvar a admissão CLT, o evento S-2200 fica pronto na aba eSocial.</p></div>
  <div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-ps-salvar="${id||''}">${id?'Salvar ficha':'Admitir'}</button></div>`);
 const cep=$('#fCep');cep.onchange=async()=>{const v=dig(cep.value);if(v.length!==8)return;try{const r=await fetch(`https://viacep.com.br/ws/${v}/json/`),j=await r.json();if(j.erro)return;$('#fLog').value=j.logradouro||'';$('#fBairro').value=j.bairro||'';$('#fCid').value=j.localidade||'';$('#fUf').value=j.uf||'';$('#fIbge').value=j.ibge||''}catch{}}}
async function salvarFicha(id){const v=s=>$(s)?.value?.trim()||'',n=s=>{const x=v(s);if(!x)return null;const y=Number(x.includes(',')?x.replace(/\./g,'').replace(',','.'):x);return Number.isFinite(y)?y:null};
 const nome=v('#fN');if(nome.length<3)return toast('Informe o nome.');if(v('#fCpf')&&!cpfOk(v('#fCpf')))return toast('CPF inválido.');const sal=n('#fSal');if(sal==null)return toast('Informe o salário.');
 const e=v('#fEnt'),s=v('#fSai'),i=Number(v('#fInt'))||0,jm=Math.max(0,(Number(s.slice(0,2))*60+Number(s.slice(3)))-(Number(e.slice(0,2))*60+Number(e.slice(3)))-i),vinc=v('#fVinc'),adm=v('#fAdm')||null;
 const row={nome,cpf:dig(v('#fCpf'))||null,pis:dig(v('#fPis'))||null,nascimento:v('#fNasc')||null,sexo:v('#fSexo')||null,estado_civil:Number(v('#fEC'))||null,raca_cor:Number(v('#fRaca'))||6,grau_instrucao:v('#fInstr'),rg:v('#fRg')||null,
  endereco:{cep:dig(v('#fCep')),logradouro:v('#fLog'),numero:v('#fNum'),complemento:v('#fCompl'),bairro:v('#fBairro'),cidade:v('#fCid'),uf:v('#fUf').toUpperCase(),ibge:dig(v('#fIbge'))},telefone:v('#fTel')||null,email:v('#fEmail')||null,
  matricula:v('#fMat')||null,cargo:v('#fCargo')||null,cbo:dig(v('#fCbo'))||null,departamento:v('#fDep')||null,tipo_contrato:v('#fTipo'),experiencia_dias:Number(v('#fExp'))||null,experiencia_prorrogacao:Number(v('#fProrr'))||0,
  entrada:e,saida:s,intervalo_min:i,jornada_min:jm||528,horas_semanais:Number(v('#fHs'))||44,dependentes_ir:Number(v('#fDepIr'))||0,vale_transporte:n('#fVt')||0,banco:{banco:v('#fBco'),agencia:v('#fAg'),conta:v('#fCc')},pix:v('#fPix')||null,updated_at:new Date().toISOString()};
 const atual=id?C(id):null;
 // Mudança programada para CLT (ex.: pró-labore até 30/09): a admissão CLT é a data da mudança; senão, a admissão do vínculo atual.
 if(atual?.proximo_em&&atual.proximo_vinculo==='clt'&&vinc==='clt'){row.proximo_em=adm;row.proximo_salario=sal}else{row.vinculo=vinc;row.salario=sal;row.admissao=adm}
 if(!id)Object.assign(row,{workspace_id:Cloud.ws,ativo:true,inicio:adm,dias_semana:[1,2,3,4,5],politica_horas:'banco'});
 const q=id?Cloud.client.from('ponto_colaboradores').update(row).eq('workspace_id',Cloud.ws).eq('id',id).select().single():Cloud.client.from('ponto_colaboradores').insert(row).select().single();const {data,error}=await q;if(error)return toast(error.message);
 await auditar(data.id,id?'Ficha alterada':'Admissão',{nome,vinculo:vinc,salario:sal,admissao:adm});closeModal();await PT().recarregar();await FL()?.garantir?.();
 const c=C(data.id);if(c&&admissaoClt(c)&&!pendenciasEsocial(c).length&&!st.eventos.some(x=>x.colaborador_id===c.id&&x.evento==='S-2200')){try{await guardarEvento('S-2200',c.id,admissaoClt(c),`Admissão de ${c.nome}`,s2200(c));toast('Ficha salva. Evento S-2200 pronto na aba eSocial.')}catch(x){toast('Ficha salva; S-2200 não gerado: '+x.message)}}else toast(pendenciasEsocial(c||{}).length?`Ficha salva. Para o eSocial ainda falta: ${pendenciasEsocial(c).join(', ')}.`:'Ficha salva.');
 await carregar(true)}

// ── PDFs ──
const carregaLib=(g,src)=>window[g]?Promise.resolve():new Promise((ok,er)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=()=>er(Error('Não foi possível carregar '+g));document.head.appendChild(s)});
const tt=s=>String(s??'').normalize('NFD').replace(/[̀-ͯ]/g,'');
async function doc(titulo,blocos,nome){await carregaLib('jspdf','https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js');const {jsPDF}=window.jspdf,d=new jsPDF({unit:'pt',format:'a4'}),W=595.28,M=40;let y=0;const emp=empregador();
 d.setFillColor(11,22,34);d.rect(0,0,W,70,'F');d.setTextColor(95,224,204);d.setFont('helvetica','bold');d.setFontSize(10);d.text(tt(titulo.toUpperCase()),M,28);d.setTextColor(255,255,255);d.setFontSize(13);d.text(tt(emp.razao||window.Cloud?.wsName||'Empresa'),M,48);d.setFont('helvetica','normal');d.setFontSize(9);d.text(tt(`CNPJ ${dig(emp.cnpj).replace(/(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/,'$1.$2.$3/$4-$5')}`),W-M,48,{align:'right'});y=96;d.setTextColor(26,50,68);
 for(const b of blocos){if(y>770){d.addPage();y=50}if(b.h){d.setFont('helvetica','bold');d.setFontSize(11);d.text(tt(b.h),M,y);y+=16;continue}if(b.p){d.setFont('helvetica','normal');d.setFontSize(9.5);const l=d.splitTextToSize(tt(b.p),W-2*M);d.text(l,M,y);y+=l.length*12+6;continue}
  if(b.kv){d.setFontSize(9.5);for(const [k2,v] of b.kv){d.setFont('helvetica','bold');d.text(tt(k2),M,y);d.setFont('helvetica','normal');d.text(tt(v),M+170,y);y+=14}y+=4;continue}
  if(b.tab){d.setFillColor(232,242,245);d.rect(M,y-11,W-2*M,18,'F');d.setFont('helvetica','bold');d.setFontSize(9);d.text('Descricao',M+4,y+1);d.text('Ref.',330,y+1);d.text('Proventos',470,y+1,{align:'right'});d.text('Descontos',W-M-4,y+1,{align:'right'});y+=20;d.setFont('helvetica','normal');
   for(const [desc,ref,val,tp] of b.tab){d.text(tt(desc).slice(0,52),M+4,y);d.text(tt(ref||''),330,y);d.text(tp==='p'?val.toLocaleString('pt-BR',{minimumFractionDigits:2}):'',470,y,{align:'right'});d.text(tp==='d'?val.toLocaleString('pt-BR',{minimumFractionDigits:2}):'',W-M-4,y,{align:'right'});y+=14}y+=6;continue}
  if(b.ass){y=Math.max(y+30,y);d.line(M,y,M+220,y);d.line(W-M-220,y,W-M,y);d.setFontSize(8.5);d.text(tt(b.ass[0]),M,y+11);d.text(tt(b.ass[1]),W-M-220,y+11);y+=30}}
 const blob=d.output('blob'),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=nome;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1500)}
function pdfFicha(c){const e=c.endereco||{},adm=admissaoClt(c)||c.admissao,k2=contrato(c,adm);return doc('Ficha de registro de empregado',[{h:'Identificacao'},{kv:[['Nome',c.nome],['CPF',c.cpf||'—'],['PIS/NIS',c.pis||'—'],['Nascimento',br(c.nascimento)],['RG',c.rg||'—']]},{h:'Endereco'},{kv:[['Logradouro',`${e.logradouro||''}, ${e.numero||''} ${e.complemento||''}`],['Bairro / cidade',`${e.bairro||''} · ${e.cidade||''}/${e.uf||''}`],['CEP',e.cep||'—']]},{h:'Contrato'},{kv:[['Admissao',br(adm)],['Cargo / CBO',`${c.cargo||'—'} · ${c.cbo||'—'}`],['Salario',R(k2.salario)],['Jornada',`${String(c.entrada).slice(0,5)} as ${String(c.saida).slice(0,5)}, intervalo ${c.intervalo_min} min · ${c.horas_semanais||44}h/semana`],['Tipo',c.tipo_contrato==='experiencia'?`Experiencia de ${c.experiencia_dias||45} dias${c.experiencia_prorrogacao?' + '+c.experiencia_prorrogacao:''}`:c.tipo_contrato]]},{ass:['Empregado','Empregador']}],`ficha-registro-${tt(c.nome).toLowerCase().replace(/[^a-z0-9]+/g,'-')}.pdf`)}
function pdfContrato(c){const adm=admissaoClt(c)||c.admissao,k2=contrato(c,adm),emp=empregador(),exp=c.tipo_contrato==='experiencia';return doc(exp?'Contrato de trabalho por prazo de experiencia':'Contrato individual de trabalho',[
 {p:`Pelo presente instrumento, ${emp.razao||'a EMPREGADORA'}, inscrita no CNPJ ${emp.cnpj}, com sede em ${emp.endereco||''} ${emp.municipio||''}/${emp.uf||''}, e ${c.nome}, CPF ${c.cpf||'—'}, residente em ${(c.endereco||{}).logradouro||''}, ${(c.endereco||{}).numero||''}, ${(c.endereco||{}).cidade||''}/${(c.endereco||{}).uf||''}, ajustam o presente contrato de trabalho, regido pela CLT e pelas clausulas abaixo.`},
 {p:`1. O EMPREGADO exercera a funcao de ${c.cargo||'—'} (CBO ${c.cbo||'—'}), obrigando-se a executar as atividades compativeis com a funcao, no estabelecimento da EMPREGADORA.`},
 {p:`2. A remuneracao mensal sera de ${R(k2.salario)}, paga ate o 5o dia util do mes seguinte ao vencido.`},
 {p:`3. A jornada sera de ${c.horas_semanais||44} horas semanais, das ${String(c.entrada).slice(0,5)} as ${String(c.saida).slice(0,5)}, com ${c.intervalo_min} minutos de intervalo, registrada no ponto eletronico (Jarvis Ponto). Horas excedentes serao compensadas em banco de horas ou pagas conforme a lei.`},
 ...(exp?[{p:`4. Este contrato e de experiencia, com inicio em ${br(adm)} e prazo de ${c.experiencia_dias||45} dias${c.experiencia_prorrogacao?`, prorrogavel por mais ${c.experiencia_prorrogacao} dias`:''}, nao podendo ultrapassar 90 dias (art. 445, paragrafo unico, CLT). Vencido o prazo sem manifestacao das partes, passa a vigorar por prazo indeterminado.`}]:[{p:`4. O contrato vigora por prazo indeterminado a partir de ${br(adm)}.`}]),
 {p:'5. O EMPREGADO autoriza os descontos previstos em lei (INSS, IRRF, vale-transporte) e os decorrentes de danos causados por dolo, e se compromete a cumprir o regulamento interno e a guardar sigilo das informacoes da EMPREGADORA.'},
 {p:`E, por estarem de acordo, assinam em duas vias. ${emp.municipio||''}, ${br(adm)}.`},{ass:['Empregado','Empregador']}],`contrato-${tt(c.nome).toLowerCase().replace(/[^a-z0-9]+/g,'-')}.pdf`)}
function pdfFerias(c,f){const k2=f.calculo;return doc('Aviso e recibo de ferias',[{kv:[['Empregado',c.nome],['Periodo aquisitivo',`${br(f.aquisitivo_ini)} a ${br(f.aquisitivo_fim)}`],['Gozo',`${br(f.gozo_ini)} a ${br(f.gozo_fim)} (${f.dias} dias)`],['Retorno',br(addDias(f.gozo_fim,1))],['Pagamento ate',br(f.pagamento_ate)]]},{p:'Comunicamos que as ferias serao concedidas no periodo acima (aviso com antecedencia minima de 30 dias, art. 135 da CLT).'},{tab:k2.itens},{kv:[['Liquido a receber',R(k2.liquido)]]},{ass:['Empregado','Empregador']}],`ferias-${tt(c.nome).toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${f.gozo_ini}.pdf`)}
function pdfTrct(c,r){const k2=r.calculo;return doc('Termo de rescisao do contrato de trabalho',[{kv:[['Empregado',c.nome],['CPF',c.cpf||'—'],['Admissao',br(k2.admissao)],['Desligamento',br(r.data_desligamento)],['Causa',TIPOS[r.tipo]],['Aviso previo',`${r.aviso} (${k2.aviso_dias} dias)`],['Pagamento ate',br(r.pagamento_ate)]]},{tab:k2.itens.map(i=>[i.desc,i.ref,i.valor,i.tipo])},{kv:[['Total bruto',R(k2.bruto)],['Total descontos',R(k2.descontos)],['Liquido',R(k2.liquido)],['FGTS do mes rescisorio',R(k2.fgts_mes)],[`Multa FGTS (${k2.pct_multa}%)`,R(k2.multa_fgts)]]},{p:'Recibo: declaro ter recebido as verbas rescisorias discriminadas acima.'},{ass:['Empregado','Empregador']}],`trct-${tt(c.nome).toLowerCase().replace(/[^a-z0-9]+/g,'-')}.pdf`)}

// ── Eventos ──
document.addEventListener('click',async e=>{const b=e.target.closest('[data-ps],[data-ps-aba],[data-ps-ficha],[data-ps-docs],[data-ps-salvar],[data-ps-ferias],[data-ps-verf],[data-ps-verr],[data-ps-xml],[data-ps-pdf]');if(!b)return;const d=b.dataset;
 if(d.psAba){st.aba=d.psAba;render();return}if(d.psFicha){ficha(d.psFicha);return}if(d.psSalvar!==undefined){salvarFicha(d.psSalvar||null);return}
 if(d.psDocs){const c=C(d.psDocs);modal(`Documentos · ${esc(c.nome)}`,`<div class="row wrap" style="gap:8px"><button class="small" data-ps-pdf="ficha:${c.id}">Ficha de registro</button><button class="small" data-ps-pdf="contrato:${c.id}">Contrato de trabalho</button></div>
  <h4 style="margin-top:14px">Checklist da admissão</h4>${[['aso','Exame admissional (ASO)'],['ctps','CTPS digital conferida'],['contrato','Contrato assinado'],['vt','Termo de opção de vale-transporte'],['dependentes','Declaração de dependentes (IR/salário-família)'],['lgpd','Termo de ciência LGPD']].map(([k2,t])=>`<label class="check-l"><input type="checkbox" class="check" data-ps-chk="${k2}" ${(c.documentos||{})[k2]?'checked':''}> ${t}</label>`).join('')}
  <div class="modalfoot"><button data-action="close">Fechar</button><button class="primary" data-ps="salvarchk" data-id="${c.id}">Salvar checklist</button></div>`);return}
 if(d.psPdf){const [tipo,id]=d.psPdf.split(':'),c=C(id);try{if(tipo==='ficha')await pdfFicha(c);if(tipo==='contrato')await pdfContrato(c);if(tipo==='ferias'){const f=st.ferias.find(x=>x.id===id);await pdfFerias(C(f.colaborador_id),f)}if(tipo==='trct'){const r=st.resc.find(x=>x.id===id);await pdfTrct(C(r.colaborador_id),r)}}catch(x){toast(x.message)}return}
 if(d.psFerias){const c=C(d.psFerias),P=periodos(c).filter(p=>p.saldo>0&&p.fim<hoje()||p.estado==='em aquisição');
  modal(`Programar férias · ${esc(c.nome)}`,`<div class="grid two" style="gap:10px"><div><label for="frP">Período aquisitivo</label><select id="frP">${periodos(c).filter(p=>p.saldo>0).map(p=>`<option value="${p.ini}|${p.fim}">${br(p.ini)} a ${br(p.fim)} · saldo ${p.saldo} dias${p.estado==='em aquisição'?' (antecipação)':''}</option>`).join('')}</select></div><div><label for="frI">Início do gozo</label><input id="frI" type="date"></div>
   <div><label for="frD">Dias de gozo</label><input id="frD" type="number" min="5" max="30" value="30"></div><div><label for="frA">Abono pecuniário (vender dias)</label><input id="frA" type="number" min="0" max="10" value="0"></div></div>
   <label class="check-l" style="margin-top:8px"><input type="checkbox" class="check" id="fr13"> Adiantar 50% do 13º salário junto</label><div id="frCalc" style="margin-top:12px"></div>
   <div class="modalfoot"><button data-action="close">Cancelar</button><button class="small" data-ps="frcalc" data-id="${c.id}">Calcular</button><button class="primary" data-ps="frsalvar" data-id="${c.id}">Programar</button></div>`);return}
 if(d.psVerf){const f=st.ferias.find(x=>x.id===d.psVerf),c=C(f.colaborador_id);modal(`Férias · ${esc(c.nome)}`,`<p>Gozo de ${br(f.gozo_ini)} a ${br(f.gozo_fim)} · pagar até <b>${br(f.pagamento_ate)}</b></p>${tabela(f.calculo.itens)}<p><b>Líquido: ${R(f.calculo.liquido)}</b> · FGTS ${R(f.calculo.fgts)}</p>${(f.calculo.avisos||[]).map(a=>`<p class="notice">${esc(a)}</p>`).join('')}<div class="modalfoot"><button data-action="close">Fechar</button><button class="small" data-ps-pdf="ferias:${f.id}">Aviso e recibo (PDF)</button>${f.status==='programada'?`<button class="small" data-ps="frpagar" data-id="${f.id}">Lançar no contas a pagar</button><button class="small quiet" data-ps="frcancelar" data-id="${f.id}">Cancelar</button>`:''}</div>`);return}
 if(d.psVerr){const r=st.resc.find(x=>x.id===d.psVerr),c=C(r.colaborador_id);modal(`Rescisão · ${esc(c.nome)}`,`<p>${TIPOS[r.tipo]} em ${br(r.data_desligamento)} · pagar até <b>${br(r.pagamento_ate)}</b></p>${tabela(r.calculo.itens.map(i=>[i.desc,i.ref,i.valor,i.tipo]))}<p><b>Líquido: ${R(r.calculo.liquido)}</b> · FGTS do mês ${R(r.calculo.fgts_mes)} · multa ${r.calculo.pct_multa}% ${R(r.calculo.multa_fgts)}</p>${(r.calculo.avisos||[]).map(a=>`<p class="notice">${esc(a)}</p>`).join('')}<div class="modalfoot"><button data-action="close">Fechar</button><button class="small" data-ps-pdf="trct:${r.id}">TRCT (PDF)</button>${r.status==='calculada'?`<button class="small" data-ps="rspagar" data-id="${r.id}">Lançar no contas a pagar</button>`:''}</div>`);return}
 if(d.psXml){const {data,error}=await Cloud.client.from('esocial_eventos').select('xml,evento').eq('workspace_id',Cloud.ws).eq('id',d.psXml).single();if(error)return toast(error.message);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data.xml],{type:'application/xml'}));a.download=`${data.evento}-${d.psXml}.xml`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1500);return}
 switch(d.ps){
  case 'admitir':ficha(null);break;
  case 'salvarchk':{const docs={};document.querySelectorAll('[data-ps-chk]').forEach(x=>docs[x.dataset.psChk]=x.checked);const {error}=await Cloud.client.from('ponto_colaboradores').update({documentos:docs}).eq('workspace_id',Cloud.ws).eq('id',d.id);if(error)return toast(error.message);closeModal();toast('Checklist salvo.');await PT().recarregar();break}
  case 'empregador':{const em=empregador();modal('Dados do empregador',`<div class="grid two" style="gap:8px">${[['razao','Razão social'],['cnpj','CNPJ'],['endereco','Endereço'],['municipio','Município'],['uf','UF'],['ibge','Código IBGE do município'],['cep','CEP']].map(([k2,t])=>`<div><label>${t}<input data-emp="${k2}" value="${esc(em[k2]||'')}"></label></div>`).join('')}</div><p class="caption">Aparece nos contratos, recibos, TRCT e nos eventos do eSocial.</p><div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-ps="salvaremp">Salvar</button></div>`);break}
  case 'salvaremp':{const o={};document.querySelectorAll('[data-emp]').forEach(x=>o[x.dataset.emp]=x.value.trim());try{await FL().salvarParametros({empregador:o});closeModal();toast('Dados do empregador salvos.')}catch(x){toast(x.message)}break}
  case 'frcalc':case 'frsalvar':{const c=C(d.id),[ai,af]=($('#frP')?.value||'|').split('|'),ini=$('#frI').value,dias=Number($('#frD').value),ab=Number($('#frA').value)||0;if(!ai)return toast('Sem período com saldo.');if(!ini)return toast('Informe o início do gozo.');if(dias<5||dias+ab>30)return toast('Dias entre 5 e 30 (gozo + abono até 30).');
   const calc=calcFerias(c,{gozo_ini:ini,dias,abono_dias:ab,adiantar_13:$('#fr13').checked});$('#frCalc').innerHTML=`${tabela(calc.itens)}<p><b>Líquido: ${R(calc.liquido)}</b> · pagar até ${br(addDias(ini,-2))} · FGTS ${R(calc.fgts)}</p>${calc.avisos.map(a=>`<p class="notice">${esc(a)}</p>`).join('')}`;
   if(d.ps==='frcalc')break;const row={workspace_id:Cloud.ws,colaborador_id:c.id,aquisitivo_ini:ai,aquisitivo_fim:af,gozo_ini:ini,gozo_fim:addDias(ini,dias-1),dias,abono_dias:ab,adiantar_13:$('#fr13').checked,calculo:calc,pagamento_ate:addDias(ini,-2)};
   const {error}=await Cloud.client.from('folha_ferias').insert(row);if(error)return toast(error.message);await auditar(c.id,'Férias programadas',{gozo:`${ini} (${dias} dias)`,liquido:calc.liquido});closeModal();toast('Férias programadas. Gere o aviso e o recibo em PDF.');await carregar(true);break}
  case 'frcancelar':{const {error}=await Cloud.client.from('folha_ferias').update({status:'cancelada'}).eq('workspace_id',Cloud.ws).eq('id',d.id);if(error)return toast(error.message);closeModal();await carregar(true);break}
  case 'frpagar':{const f=st.ferias.find(x=>x.id===d.id),c=C(f.colaborador_id);lancarPagar(`FERIAS-${f.id.slice(0,8)}`,c,`Férias ${br(f.gozo_ini)} a ${br(f.gozo_fim)} · ${PT().curto(c.nome)}`,f.pagamento_ate,f.calculo.liquido);await Cloud.client.from('folha_ferias').update({status:'paga'}).eq('workspace_id',Cloud.ws).eq('id',f.id);closeModal();await carregar(true);break}
  case 'rescindir':{const L=colabs().filter(c=>c.ativo&&admissaoClt(c));if(!L.length)return toast('Nenhum empregado CLT ativo.');modal('Calcular rescisão',`<div class="grid two" style="gap:10px"><div><label for="rsP">Pessoa</label><select id="rsP">${L.map(c=>`<option value="${c.id}">${esc(c.nome)}</option>`).join('')}</select></div><div><label for="rsD">Data do desligamento</label><input id="rsD" type="date" value="${hoje()}"></div>
   <div><label for="rsT">Causa</label><select id="rsT">${OPT(Object.entries(TIPOS),'sem_justa_causa')}</select></div><div><label for="rsA">Aviso prévio</label><select id="rsA">${OPT([['indenizado','Indenizado'],['trabalhado','Trabalhado'],['dispensado','Dispensado'],['nao_cumprido','Não cumprido (pedido de demissão)']],'indenizado')}</select></div>
   <div><label for="rsF">Saldo do FGTS para fins rescisórios (R$)</label><input id="rsF" inputmode="decimal" placeholder="extrato da conta vinculada"></div></div><div id="rsCalc" style="margin-top:12px"></div>
   <div class="modalfoot"><button data-action="close">Cancelar</button><button class="small" data-ps="rscalc">Calcular</button><button class="primary" data-ps="rssalvar">Salvar rescisão</button></div>`);break}
  case 'rscalc':case 'rssalvar':{const c=C($('#rsP').value),fg=Number(String($('#rsF').value||'0').replace(/\./g,'').replace(',','.'))||0,r={data_desligamento:$('#rsD').value,tipo:$('#rsT').value,aviso:$('#rsA').value,saldo_fgts:fg};if(!r.data_desligamento)return toast('Informe a data.');
   const calc=calcRescisao(c,r);if(calc.erro)return toast(calc.erro);$('#rsCalc').innerHTML=`${tabela(calc.itens.map(i=>[i.desc,i.ref,i.valor,i.tipo]))}<p><b>Líquido: ${R(calc.liquido)}</b> · pagar até ${br(calc.pagamento_ate)} · FGTS do mês ${R(calc.fgts_mes)} · multa ${calc.pct_multa}% ${R(calc.multa_fgts)}</p>${calc.avisos.map(a=>`<p class="notice">${esc(a)}</p>`).join('')}`;
   if(d.ps==='rscalc')break;const {data,error}=await Cloud.client.from('folha_rescisoes').insert({workspace_id:Cloud.ws,colaborador_id:c.id,...r,calculo:calc,pagamento_ate:calc.pagamento_ate}).select().single();if(error)return toast(error.message);
   await Cloud.client.from('ponto_colaboradores').update({demissao:r.data_desligamento}).eq('workspace_id',Cloud.ws).eq('id',c.id);await auditar(c.id,'Rescisão calculada',{tipo:r.tipo,data:r.data_desligamento,liquido:calc.liquido});
   if(!pendenciasEsocial(c).length){try{await guardarEvento('S-2299',c.id,r.data_desligamento,`Desligamento de ${c.nome} (${TIPOS[r.tipo]})`,s2299(c,data,calc))}catch{}}
   closeModal();toast('Rescisão salva. Gere o TRCT e lance no contas a pagar quando for pagar.');await PT().recarregar();await carregar(true);break}
  case 'rspagar':{const r=st.resc.find(x=>x.id===d.id),c=C(r.colaborador_id);lancarPagar(`RESC-${r.id.slice(0,8)}`,c,`Rescisão ${PT().curto(c.nome)} (${TIPOS[r.tipo]})`,r.pagamento_ate,r.calculo.liquido);if(r.calculo.multa_fgts+r.calculo.fgts_mes>0)lancarPagar(`RESC-${r.id.slice(0,8)}-FGTS`,{nome:'Caixa · FGTS Digital',vinculo:'clt'},`FGTS rescisório + multa ${r.calculo.pct_multa}% · ${PT().curto(c.nome)}`,r.pagamento_ate,r.calculo.fgts_mes+r.calculo.multa_fgts);
   await Cloud.client.from('folha_rescisoes').update({status:'paga'}).eq('workspace_id',Cloud.ws).eq('id',r.id);closeModal();await carregar(true);break}
  case 'gerar1200':{const comp=$('#psComp').value,F=(FL().fechamentos()||[]).filter(f=>f.competencia===comp);let n=0,falta=[];for(const f of F){const c=C(f.colaborador_id);if(!c||!cpfOk(c.cpf)){falta.push(c?.nome||'?');continue}await guardarEvento('S-1200',c.id,comp,`Remuneração ${comp} · ${c.nome}`,s1200(c,f));
    const [y,m]=comp.split('-').map(Number);let dd=0,nn=0;while(nn<5){dd++;if(new Date(y,m,dd).getDay()!==0)nn++}await guardarEvento('S-1210',c.id,comp,`Pagamento ${comp} · ${c.nome}`,s1210(c,f,iso(new Date(y,m,dd))));n+=2}
   if(n)await guardarEvento('S-1299',null,comp,`Fechamento dos eventos periódicos ${comp}`,s1299(comp));toast(`${n+(n?1:0)} evento(s) gerados.${falta.length?' Sem CPF válido: '+falta.join(', '):''}`);await carregar(true);break}
 }});
function tabela(itens){return `<div class="tablebox"><table><tbody>${itens.map(([desc,ref,val,tp])=>`<tr><td>${esc(desc)}</td><td><small class="caption">${esc(ref||'')}</small></td><td class="num ${tp==='d'?'red':''}">${tp==='d'?'−':''}${R(val)}</td></tr>`).join('')}</tbody></table></div>`}
function lancarPagar(id,c,descricao,venc,valor){db.payables=db.payables||[];if(db.payables.some(p=>p.id===id))return toast('Já lançado no contas a pagar.');db.payables.push((window.Pagamentos?.marcar||(x=>x))({id,origem:'folha',fornecedor:c.nome,descricao:descricao+(c.pix?' · PIX '+c.pix:''),vencimento:venc,valor:r2(valor),emissao:hoje(),status:'aberto',parcela:1,parcelas:1,categoria:c.vinculo==='prolabore'?'Pró-labore':'Salários e encargos',lancadoPor:quem(),createdBy:quem()}));save();toast('Lançado no contas a pagar.')}
window.Pessoas={acessoLiberado:()=>{if(page==='pessoas')render()},periodos,calcFerias,calcRescisao};
addPage('pessoas','pessoas','Pessoas',view,'Admissão com os dados do eSocial, férias, rescisões e eventos do eSocial prontos para transmitir. Só quem criou a empresa acessa.','',()=>{});
})();
