'use strict';
// Jornada (controle de ponto). Só o CRIADOR do workspace vê e altera (RLS: public.e_criador). Os colaboradores
// registram pelo app "Jarvis Ponto" (ponto.html) — hora do servidor, NSR e hash em cada marcação (função "ponto").
// Regra do banco de horas: igual a supabase/functions/_shared/ponto_calc.ts (mantenha as duas iguais).
(()=>{
Object.assign(paths,{clock:'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18z M12 7v5l3 2'});
const st={acesso:null,carregando:false,ok:false,colabs:[],dias:[],aj:[],sol:[],aud:[],anexos:[],disp:[],aba:'agora',colab:null,mes:null,timer:null};
const TIPOS=[['trabalho','Trabalho'],['feriado','Feriado'],['folga','Folga'],['falta','Falta'],['compensacao','Compensação'],['atestado','Atestado'],['ferias','Férias'],['desconsiderado','Desconsiderado']];
const TIPO=Object.fromEntries(TIPOS),PASSOS=['Entrada','Saída p/ intervalo','Volta do intervalo','Saída','Entrada extra','Saída extra'];
const SEM=['dom','seg','ter','qua','qui','sex','sáb'];
const pad=n=>String(n).padStart(2,'0'),dur=m=>`${pad(Math.floor(Math.abs(m)/60))}:${pad(Math.abs(m)%60)}`,sin=m=>`${m<0?'−':'+'}${dur(m)}`;
const hojeISO=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const mesAtual=()=>hojeISO().slice(0,7),mesAnt=()=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-1);return `${d.getFullYear()}-${pad(d.getMonth()+1)}`},mesLabel=v=>{const [y,m]=v.split('-').map(Number);return new Date(y,m-1,15).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})};
const mMin=h=>Number(h.slice(0,2))*60+Number(h.slice(3,5)),hm=v=>String(v||'').slice(0,5);
const quem=()=>window.Cloud?.session?.user?.email||'criador';
const C=id=>st.colabs.find(c=>c.id===id),curto=n=>{const p=String(n||'').trim().split(/\s+/);return p.length>2?p[0]+' '+p[p.length-1]:n};

// ── Cálculo (igual ao servidor) ──
function trabalhado(m){let t=0;for(let i=0;i<6;i+=2){const a=m[i]||'',b=m[i+1]||'';if(!!a!==!!b)return null;if(a){const n=mMin(b)-mMin(a);if(n<=0)return null;t+=n}}return t||null}
function linhasMes(c,mes){const [y,m]=mes.split('-').map(Number),n=new Date(y,m,0).getDate(),hoje=hojeISO(),por=new Map(st.dias.filter(d=>d.colaborador_id===c.id&&d.data.startsWith(mes)).map(d=>[d.data,d]));const out=[];
 for(let d=1;d<=n;d++){const data=`${mes}-${pad(d)}`,wd=new Date(y,m-1,d).getDay(),previsto=(c.dias_semana||[]).includes(wd),r=por.get(data),futuro=data>hoje,antes=c.inicio&&data<c.inicio;let delta=null,trab=null,sit='';
  if(futuro||antes){out.push({data,d,wd,previsto,r,delta:null,trab:null,sit:futuro?'futuro':'antes',conta:false});continue}
  if(!r){if(data===hoje){out.push({data,d,wd,previsto,r,delta:null,trab:null,sit:'hoje',conta:false});continue}delta=previsto?-c.jornada_min:0;sit=previsto?'sem':'livre'}
  else if(['folga','feriado','desconsiderado','atestado','ferias'].includes(r.tipo)){delta=0;sit='classif'}
  else if(['falta','compensacao'].includes(r.tipo)){delta=previsto?-c.jornada_min:0;sit='classif'}
  else{trab=trabalhado(r.marcacoes||[]);if(trab===null&&data===hoje){out.push({data,d,wd,previsto,r,delta:null,trab:null,sit:'hoje',conta:false});continue}delta=trab===null?null:trab-(previsto?c.jornada_min:0);sit=trab===null?'incompleto':(r.conferido?'ok':'conferir')}
  out.push({data,d,wd,previsto,r,delta,trab,sit,conta:true})}
 return out}
function resumo(c,mes){let cr=0,db=0,pend=0;for(const l of linhasMes(c,mes)){if(!l.conta)continue;if(l.sit==='sem'||(l.r&&!l.r.conferido))pend++;if(l.delta==null)continue;if(l.delta>0)cr+=l.delta;else db+=l.delta}
 for(const a of st.aj.filter(a=>a.colaborador_id===c.id&&a.competencia===mes)){if(a.minutos>0)cr+=a.minutos;else db+=a.minutos}return {cr,db,saldo:cr+db,pend}}
function mesesDe(c,ate){const prim=[c.inicio?.slice(0,7),...st.dias.filter(d=>d.colaborador_id===c.id).map(d=>d.data.slice(0,7))].filter(Boolean).sort()[0]||ate;const out=[];let [y,m]=prim.split('-').map(Number);for(;;){const v=`${y}-${pad(m)}`;if(v>ate)break;out.push(v);if(++m>12){m=1;y++}}return out}
function evolucao(c,ate){let ac=c.saldo_inicial||0;return mesesDe(c,ate).map(mes=>{const r=resumo(c,mes);ac+=r.saldo;return {mes,...r,ac}})}
const banco=(c,ate=mesAtual())=>{const e=evolucao(c,ate);return e.length?e[e.length-1].ac:(c.saldo_inicial||0)};

// ── Dados ──
async function checarAcesso(){if(st.acesso!==null||!window.Cloud?.ws||!Cloud.session)return;st.acesso=false;
 try{const {data}=await Cloud.client.from('workspaces').select('criador').eq('id',Cloud.ws).maybeSingle();st.acesso=!!data?.criador&&data.criador===Cloud.session.user.id}catch{}
 window.Ponto.acesso=st.acesso;if(st.acesso){render();window.Folha?.acessoLiberado?.()}}
async function carregar(forca){if(st.carregando||(!forca&&st.ok)||!window.Cloud?.ws)return;st.carregando=true;const c=Cloud.client,ws=Cloud.ws,q=t=>c.from(t).select('*').eq('workspace_id',ws);
 try{const [a,b,d,e,f,g,h]=await Promise.all([q('ponto_colaboradores').order('nome'),q('ponto_dias').order('data'),q('ponto_ajustes').order('created_at'),q('ponto_solicitacoes').order('created_at',{ascending:false}),q('ponto_auditoria').order('em',{ascending:false}).limit(300),q('ponto_anexos').order('competencia'),q('ponto_dispositivos').order('created_at')]);
  for(const r of [a,b,d,e,f,g,h])if(r.error)throw r.error;
  Object.assign(st,{colabs:a.data,dias:b.data,aj:d.data,sol:e.data,aud:f.data,anexos:g.data,disp:h.data,ok:true});if(!st.colab||!C(st.colab))st.colab=st.colabs.find(x=>x.ativo)?.id||st.colabs[0]?.id||null;if(!st.mes)st.mes=mesAtual()}
 catch(x){toast('Jornada: '+(x.message||x))}st.carregando=false;if(page==='ponto'&&!document.querySelector('.modalback'))render()}
async function auditar(colab,data,acao,antes,depois,motivo){await Cloud.client.from('ponto_auditoria').insert({workspace_id:Cloud.ws,colaborador_id:colab,data,acao,antes,depois,motivo:motivo||null,por:quem()})}

// ── Telas ──
const k=(t,v,s,c='')=>`<div class="card kpi"><span class="kpil">${t}</span><span class="kpiv ${c}">${v}</span><span class="kpis">${s}</span></div>`;
const cor=m=>m>0?'green':m<0?'red':'';
function status(c){const hoje=hojeISO(),r=st.dias.find(d=>d.colaborador_id===c.id&&d.data===hoje),m=(r?.marcacoes||[]).filter(Boolean),wd=new Date().getDay(),prev=(c.dias_semana||[]).includes(wd);
 if(r&&r.tipo!=='trabalho')return {t:TIPO[r.tipo]||r.tipo,cls:'info',m};
 if(!m.length){const atraso=prev&&new Date().getHours()*60+new Date().getMinutes()>mMin(hm(c.entrada))+10;return {t:prev?(atraso?'Ainda não registrou':'Aguardando entrada'):'Dia livre',cls:atraso?'bad':'',m}}
 const ult=m[m.length-1],n=m.length;return {t:n%2?(n===1?`Trabalhando desde ${m[0]}`:`Trabalhando · voltou ${ult}`):(n===2?`Em intervalo desde ${ult}`:`Encerrou às ${ult}`),cls:n%2?'ok':(n===2?'warn':'purple'),m}}
function trabalhadoAgora(m){let t=0;const agora=new Date().getHours()*60+new Date().getMinutes();for(let i=0;i<m.length;i+=2){if(!m[i])continue;t+=Math.max(0,(m[i+1]?mMin(m[i+1]):agora)-mMin(m[i]))}return t}
function agoraView(){const pend=st.sol.filter(s=>s.status==='pendente').length,ativos=st.colabs.filter(c=>c.ativo);
 if(!ativos.length)return `<div class="empty">Nenhuma pessoa cadastrada. <button class="small primary" data-pt="nova">Cadastrar a primeira</button></div>`;
 return `${pend?`<div class="notice">${pend} pedido(s) de ajuste aguardando você. <button class="small" data-pt-aba="solic">Ver pedidos</button></div>`:''}<div class="ptcards">${ativos.map(c=>{const s=status(c),hoje=hojeISO(),r=st.dias.find(d=>d.colaborador_id===c.id&&d.data===hoje),reg=r?.registros||[],t=trabalhadoAgora(s.m),rm=resumo(c,mesAtual()),ac=banco(c),ant=mesAnt(),acAnt=banco(c,ant),disp=st.disp.filter(d=>d.colaborador_id===c.id&&d.token_hash&&!d.revogado).length;
  return `<section class="card ptcard"><div class="pthead"><div class="ptav">${esc(c.nome.trim()[0]||'?')}</div><div><b title="${esc(c.nome)}">${esc(curto(c.nome))}</b><small class="caption">${esc(c.cargo||'')}${c.cargo?' · ':''}${hm(c.entrada)}–${hm(c.saida)}</small></div><span class="badge ${s.cls}">${esc(s.t)}</span></div>
   <div class="ptline">${PASSOS.slice(0,Math.max(4,s.m.length)).map((p,i)=>{const g=reg.find(x=>x.i===i+1);return `<div class="${s.m[i]?'on':''}"><i></i><b>${s.m[i]||'--:--'}</b><small>${p}${g?.lat!=null?` · <a href="https://maps.google.com/?q=${g.lat},${g.lng}" target="_blank" rel="noopener" title="Local da marcação">local</a>`:''}${g?.nsr?` · NSR ${g.nsr}`:''}</small></div>`}).join('')}</div>
   <div class="ptsaldo"><div><small>Saldo acumulado</small><b class="${cor(ac)}">${sin(ac)}</b><small>até hoje · saldo inicial + todos os meses</small></div><div class="ptmini"><span>${esc(mesLabel(ant).replace(/ de \d{4}$/,''))} fechou em <b class="${cor(acAnt)}">${sin(acAnt)}</b></span><span>Mês atual <b class="${cor(rm.saldo)}">${sin(rm.saldo)}</b></span><span>Hoje <b>${dur(t)}</b></span></div></div>
   <div class="ptnums"><span class="caption">${disp?`${disp} aparelho(s) ativo(s)`:'<a href="#" data-pt-link="'+c.id+'">gerar acesso ao app</a>'}</span></div></section>`}).join('')}</div>`}
function seletores(mes=true){return `<div class="row wrap ptsel"><select data-pt-sel="colab">${st.colabs.map(c=>`<option value="${c.id}" ${c.id===st.colab?'selected':''}>${esc(c.nome)}${c.ativo?'':' (inativo)'}</option>`).join('')}</select>${mes?`<input type="month" value="${st.mes}" data-pt-sel="mes">`:''}</div>`}
function espelhoView(){const c=C(st.colab);if(!c)return '<div class="empty">Cadastre uma pessoa em Equipe.</div>';const L=linhasMes(c,st.mes),r=resumo(c,st.mes),ev=evolucao(c,st.mes),ac=ev.length?ev[ev.length-1].ac:(c.saldo_inicial||0),anx=st.anexos.filter(a=>a.colaborador_id===c.id&&a.competencia===st.mes).length;let acum=ac-r.saldo;
 const SIT={ok:['Conferido','ok'],conferir:['A conferir','warn'],incompleto:['Incompleto','bad'],sem:['Sem registro','bad'],classif:['Classificado','info'],livre:['',''],hoje:['Hoje','info'],futuro:['',''],antes:['','']};
 return `${seletores()}<div class="grid kpis4 ptk">${k('Créditos no mês',sin(r.cr),'horas a mais e ajustes','green')}${k('Débitos no mês',sin(r.db),'faltas, dias sem registro e ajustes','red')}${k('Saldo do mês',sin(r.saldo),`${mesLabel(st.mes)}`,cor(r.saldo))}${k('Banco acumulado',sin(ac),`saldo inicial ${sin(c.saldo_inicial||0)} + meses`,cor(ac))}</div>
 <div class="row wrap" style="margin:-6px 0 14px;gap:8px"><span class="badge ${r.pend?'warn':'ok'}">${r.pend} dia(s) a conferir</span><button class="small" data-pt="conferirmes">Conferir dias completos</button><button class="small quiet" data-pt-aba="arquivos">${anx} arquivo(s) do mês</button><span style="flex:1"></span><button class="small" data-pt="csv">${icon('download')} CSV do mês</button><button class="small" data-pt="pdf">${icon('download')} PDF</button></div>
 <div class="tablebox" style="overflow-x:auto"><table class="pttab"><thead><tr><th>Dia</th><th>Marcações</th><th class="num">Trabalhadas</th><th class="num">Previstas</th><th class="num">Diferença</th><th class="num">Acumulado</th><th>Situação</th></tr></thead><tbody>
 ${L.map(l=>{if(l.delta!=null)acum+=l.delta;const s=SIT[l.sit]||['',''],m=(l.r?.marcacoes||[]).filter(Boolean),tipo=l.r&&l.r.tipo!=='trabalho'?`<span class="badge info">${TIPO[l.r.tipo]}</span>`:'';
  return `<tr class="${l.previsto?'':'ptfds'} ${l.sit==='futuro'||l.sit==='antes'?'ptoff':''}" data-pt-dia="${l.data}"><td><b>${pad(l.d)}</b> <small class="caption">${SEM[l.wd]}</small></td><td>${tipo}${m.map(x=>`<span class="ptchip">${x}</span>`).join('')}${l.r?.origem==='colaborador'?' <small class="caption" title="Registrado pelo app">app</small>':''}${l.r?.observacao?` <small class="caption">· ${esc(l.r.observacao)}</small>`:''}</td>
   <td class="num">${l.trab!=null?dur(l.trab):'—'}</td><td class="num">${l.previsto&&l.conta?dur(c.jornada_min):'—'}</td><td class="num ${cor(l.delta||0)}">${l.delta!=null?sin(l.delta):'—'}</td><td class="num">${l.conta&&l.delta!=null?sin(acum):''}</td><td>${s[0]?`<span class="badge ${s[1]}">${s[0]}</span>`:''}</td></tr>`}).join('')}
 </tbody></table></div><p class="caption" style="margin-top:8px">Clique num dia para corrigir marcações, classificar (feriado, folga, atestado…) ou conferir. Correções em marcações feitas pelo app pedem motivo e ficam na auditoria.</p>`}
function bancoView(){const c=C(st.colab);if(!c)return '<div class="empty">Cadastre uma pessoa em Equipe.</div>';const ev=evolucao(c,st.mes),max=Math.max(60,...ev.map(e=>Math.abs(e.saldo))),aj=st.aj.filter(a=>a.colaborador_id===c.id&&a.competencia===st.mes);
 return `${seletores()}<div class="grid two"><section class="card"><h3>Evolução do banco de horas</h3><div class="ptbars">${ev.slice(-12).map(e=>`<div title="${mesLabel(e.mes)}: ${sin(e.saldo)} · acumulado ${sin(e.ac)}"><i class="${e.saldo<0?'neg':''}" style="height:${(Math.abs(e.saldo)/max*100).toFixed(0)}%"></i><small>${new Date(e.mes+'-15T12:00').toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</small></div>`).join('')}</div>
  <div class="tablebox" style="margin-top:12px"><table><thead><tr><th>Competência</th><th class="num">Créditos</th><th class="num">Débitos</th><th class="num">Saldo</th><th class="num">Acumulado</th><th class="num">A conferir</th></tr></thead><tbody>${ev.slice().reverse().map(e=>`<tr class="${e.mes===st.mes?'sel':''}"><td>${mesLabel(e.mes)}</td><td class="num green">${sin(e.cr)}</td><td class="num red">${sin(e.db)}</td><td class="num ${cor(e.saldo)}">${sin(e.saldo)}</td><td class="num ${cor(e.ac)}"><b>${sin(e.ac)}</b></td><td class="num">${e.pend||''}</td></tr>`).join('')}</tbody></table></div>
  <div class="row wrap" style="margin-top:12px;gap:8px"><button class="small" data-pt="pdf">${icon('download')} PDF de ${esc(c.nome.split(' ')[0])}</button><button class="small" data-pt="zip">${icon('download')} PDFs de todos (ZIP)</button></div></section>
 <section class="card"><h3>Ajustes e compensações · ${mesLabel(st.mes)}</h3><p class="caption">Horas pagas, abonos, compensações combinadas. Entram no saldo do mês.</p>
  <div class="grid three" style="gap:8px"><div><label for="ptAjT">Tipo</label><select id="ptAjT"><option value="ajuste">Ajuste</option><option value="compensacao">Compensação</option><option value="abono">Abono</option><option value="pagamento">Horas pagas</option></select></div><div><label for="ptAjM">Horas (+/−)</label><input id="ptAjM" placeholder="-02:30 ou 01:15"></div><div><label for="ptAjS">Sinal</label><select id="ptAjS"><option value="1">Crédito (+)</option><option value="-1">Débito (−)</option></select></div></div>
  <label for="ptAjMot" style="margin-top:8px">Motivo / combinado</label><textarea id="ptAjMot" rows="2" placeholder="Ex.: pagamento de 10h extras na folha de setembro"></textarea><button class="primary small" style="margin-top:8px" data-pt="ajuste">Registrar lançamento</button>
  <div style="margin-top:14px">${aj.length?aj.map(a=>`<div class="listline"><span><b class="${cor(a.minutos)}">${sin(a.minutos)}</b> · ${esc({ajuste:'Ajuste',compensacao:'Compensação',abono:'Abono',pagamento:'Horas pagas'}[a.tipo]||a.tipo)}<br><small class="caption">${esc(a.motivo)} · ${new Date(a.created_at).toLocaleDateString('pt-BR')}</small></span><button class="small quiet" data-pt-rmaj="${a.id}">Excluir</button></div>`).join(''):'<p class="caption">Nenhum ajuste neste mês.</p>'}</div></section></div>`}
function solicView(){const L=st.sol;if(!L.length)return '<div class="empty">Nenhum pedido de ajuste ainda. Os colaboradores pedem pelo app.</div>';
 return `<div class="ptsol">${L.map(s=>{const c=C(s.colaborador_id);return `<section class="card"><div class="row" style="justify-content:space-between;gap:8px;flex-wrap:wrap"><b>${esc(c?.nome||'—')}${s.data?` · ${new Date(s.data+'T12:00').toLocaleDateString('pt-BR')}`:''}</b><span class="badge ${s.status==='pendente'?'warn':s.status==='aprovada'?'ok':'bad'}">${s.status}</span></div><p>${esc(s.texto)}</p><small class="caption">Pedido em ${new Date(s.created_at).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}${s.resposta?` · resposta: ${esc(s.resposta)}`:''}</small>
  ${s.status==='pendente'?`<div class="row wrap" style="gap:8px;margin-top:10px">${s.data?`<button class="small primary" data-pt-soldia="${s.id}">Abrir o dia e corrigir</button>`:''}<button class="small" data-pt-solok="${s.id}">Aprovar</button><button class="small quiet" data-pt-solno="${s.id}">Recusar</button></div>`:''}</section>`}).join('')}</div>`}
function equipeView(){return `<div class="row wrap" style="gap:8px;margin-bottom:14px"><button class="primary small" data-pt="nova">${icon('plus')} Nova pessoa</button><span class="caption">Cada pessoa usa o app Jarvis Ponto no próprio celular. Gere o link de acesso e envie por WhatsApp.</span></div>
 <div class="ptcards">${st.colabs.map(c=>{const ds=st.disp.filter(d=>d.colaborador_id===c.id);return `<section class="card ptcard"><div class="pthead"><div class="ptav">${esc(c.nome.trim()[0]||'?')}</div><div><b title="${esc(c.nome)}">${esc(curto(c.nome))}</b><small class="caption">${esc(c.cargo||'—')}</small></div><span class="badge ${c.ativo?'ok':''}">${c.ativo?'ativa':'inativa'}</span></div>
  <p class="caption">Jornada ${hm(c.entrada)}–${hm(c.saida)} · intervalo ${c.intervalo_min} min · <b>${dur(c.jornada_min)}</b>/dia · ${(c.dias_semana||[]).map(d=>SEM[d]).join(', ')}${c.exigir_local?' · exige localização':''}<br>Banco atual <b class="${cor(banco(c))}">${sin(banco(c))}</b>${c.inicio?` · desde ${new Date(c.inicio+'T12:00').toLocaleDateString('pt-BR')}`:''}</p>
  <div class="ptdisp">${ds.length?ds.map(d=>`<div class="listline"><span>${d.token_hash?`<b>${esc(d.aparelho||'Aparelho')}</b><br><small class="caption">ativado ${new Date(d.ativado_em).toLocaleDateString('pt-BR')}${d.ultimo_uso?` · último uso ${new Date(d.ultimo_uso).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}`:''}</small>`:`<b>Link aguardando ativação</b><br><small class="caption">vence ${new Date(d.codigo_expira).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}</small>`}</span>${d.revogado?'<span class="badge bad">revogado</span>':`<button class="small quiet" data-pt-revoga="${d.id}">Revogar</button>`}</div>`).join(''):'<p class="caption">Nenhum aparelho ainda.</p>'}</div>
  <div class="row wrap" style="gap:8px;margin-top:10px"><button class="small primary" data-pt-link="${c.id}">Gerar link do app</button><button class="small" data-pt-edita="${c.id}">Editar</button></div></section>`}).join('')}</div>`}
function arquivosView(){const c=C(st.colab),L=st.anexos.filter(a=>!c||a.colaborador_id===c.id);
 return `${seletores()}<label class="ptdrop" for="ptArq"><input id="ptArq" type="file" multiple accept="image/*,application/pdf" hidden><b>Arraste as folhas de ponto, atestados ou PDFs aqui</b><small class="caption">ou clique para escolher. Arquivos com nome "2026-04-nome.jpeg" vão sozinhos para a pessoa e o mês certos; os demais, para a pessoa e o mês selecionados acima.</small></label>
 <div class="ptanexos">${L.length?L.slice().reverse().map(a=>`<div class="card ptanx"><div class="ptthumb" data-pt-ver="${a.id}">${/^image/.test(a.tipo||'')?`<img alt="" data-pt-img="${esc(a.caminho)}">`:'<span>PDF</span>'}</div><b>${esc(a.nome)}</b><small class="caption">${esc(C(a.colaborador_id)?.nome.split(' ')[0]||'')} · ${mesLabel(a.competencia)}</small><div class="row" style="gap:6px"><button class="small" data-pt-ver="${a.id}">Abrir</button><button class="small quiet" data-pt-rmanx="${a.id}">Excluir</button></div></div>`).join(''):'<p class="caption">Nenhum arquivo ainda.</p>'}</div>`}
function auditView(){return st.aud.length?`<div class="tablebox" style="overflow-x:auto"><table><thead><tr><th>Quando</th><th>Pessoa</th><th>Dia</th><th>Ação</th><th>Antes → depois</th><th>Motivo</th><th>Por</th></tr></thead><tbody>${st.aud.map(a=>{const f=v=>v?.marcacoes?v.marcacoes.filter(Boolean).join(' · ')+(v.tipo&&v.tipo!=='trabalho'?` (${TIPO[v.tipo]||v.tipo})`:''):v?JSON.stringify(v).slice(0,80):'';return `<tr><td>${new Date(a.em).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}</td><td>${esc(C(a.colaborador_id)?.nome||'—')}</td><td>${a.data?new Date(a.data+'T12:00').toLocaleDateString('pt-BR'):''}</td><td>${esc(a.acao)}</td><td><small>${esc(f(a.antes))} → ${esc(f(a.depois))}</small></td><td><small>${esc(a.motivo||'')}</small></td><td><small>${esc(a.por||'')}</small></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">Nenhuma alteração registrada ainda.</div>'}
function view(){if(st.acesso===null){checarAcesso();return '<div class="empty">Verificando acesso…</div>'}
 if(!st.acesso)return '<div class="notice">Esta área é exclusiva de quem criou a empresa no Jarvis.</div>';
 if(!st.ok){carregar();return '<div class="empty">Carregando jornadas…</div>'}
 const pend=st.sol.filter(s=>s.status==='pendente').length,A=[['agora','Agora'],['espelho','Espelho de ponto'],['banco','Banco de horas'],['solic',`Pedidos${pend?` (${pend})`:''}`],['equipe','Equipe e aparelhos'],['arquivos','Arquivos'],['audit','Auditoria']];
 const corpo={agora:agoraView,espelho:espelhoView,banco:bancoView,solic:solicView,equipe:equipeView,arquivos:arquivosView,audit:auditView}[st.aba]||agoraView;
 return `<div class="segtabs">${A.map(([id,t])=>`<button class="${st.aba===id?'active':''}" data-pt-aba="${id}">${t}</button>`).join('')}</div>${corpo()}`}

// ── Edição de dia ──
function editarDia(data,solId){const c=C(st.colab);if(!c)return;const r=st.dias.find(d=>d.colaborador_id===c.id&&d.data===data),m=[...(r?.marcacoes||['','','','','','']),'','','','','',''].slice(0,6),dt=new Date(data+'T12:00');
 modal(`${esc(c.nome.split(' ')[0])} · ${dt.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}`,`<div class="ptedit">
  <div class="ptmarc">${PASSOS.map((p,i)=>`<label>${p}<input type="time" data-pt-m="${i}" value="${m[i]}"></label>`).join('')}</div>
  <div class="grid two" style="gap:10px;margin-top:10px"><div><label for="ptTipo">Classificação do dia</label><select id="ptTipo">${TIPOS.map(([v,t])=>`<option value="${v}" ${(r?.tipo||'trabalho')===v?'selected':''}>${t}</option>`).join('')}</select></div><div><label for="ptObs">Observação</label><input id="ptObs" value="${esc(r?.observacao||'')}" placeholder="Ex.: consulta médica com atestado"></div></div>
  ${r?.origem==='colaborador'?`<label for="ptMot" style="margin-top:10px">Motivo da correção <span class="red">*</span> <small class="caption">(obrigatório se mudar marcações feitas pelo app)</small></label><input id="ptMot" placeholder="Ex.: esqueceu de registrar a volta do intervalo">`:''}
  ${(r?.registros||[]).length?`<p class="caption" style="margin-top:8px">Pelo app: ${(r.registros||[]).map(g=>`${g.hora} (NSR ${g.nsr}${g.lat!=null?', com local':''})`).join(' · ')}</p>`:''}
  <label class="check-l" style="margin-top:10px"><input type="checkbox" class="check" id="ptConf" ${r?.conferido?'checked':''}> Conferi este dia com a pessoa ou com a folha</label>
  <div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-pt-salvadia="${data}" data-sol="${solId||''}">Salvar dia</button></div></div>`)}
async function salvarDia(data,solId){const c=C(st.colab),r=st.dias.find(d=>d.colaborador_id===c.id&&d.data===data);const m=[...document.querySelectorAll('[data-pt-m]')].map(i=>i.value||'');
 const cheios=m.map(Boolean);for(let i=0;i<6;i+=2)if(cheios[i]!==cheios[i+1])return toast(`Complete o par ${PASSOS[i]} / ${PASSOS[i+1]} (ou deixe os dois vazios).`);
 for(let i=1;i<6;i++)if(m[i]&&m[i-1]&&m[i]<=m[i-1])return toast('As marcações precisam estar em ordem crescente.');
 const novo={marcacoes:m,tipo:$('#ptTipo').value,observacao:$('#ptObs').value.trim()||null,conferido:$('#ptConf').checked},mudou=r&&JSON.stringify(r.marcacoes)!==JSON.stringify(m),mot=$('#ptMot')?.value.trim()||'';
 if(r?.origem==='colaborador'&&mudou&&mot.length<5)return toast('Informe o motivo da correção das marcações do app.');
 const row={workspace_id:Cloud.ws,colaborador_id:c.id,data,...novo,origem:r?.origem||'gestor',updated_at:new Date().toISOString()};
 const {error}=await Cloud.client.from('ponto_dias').upsert(row,{onConflict:'workspace_id,colaborador_id,data'});if(error)return toast(error.message);
 if(!r||mudou||r.tipo!==novo.tipo)await auditar(c.id,data,r?(mudou?'Marcações corrigidas':'Classificação alterada'):'Dia lançado',r?{marcacoes:r.marcacoes,tipo:r.tipo}:null,{marcacoes:m,tipo:novo.tipo},mot||novo.observacao);
 if(solId){await Cloud.client.from('ponto_solicitacoes').update({status:'aprovada',resposta:'Ajustado conforme o pedido.',resolvido_em:new Date().toISOString(),resolvido_por:quem()}).eq('workspace_id',Cloud.ws).eq('id',solId)}
 closeModal();toast('Dia salvo.');await carregar(true)}

// ── Pessoa ──
function editarPessoa(id){const c=id?C(id):{nome:'',cargo:'',email:'',entrada:'07:30',saida:'17:18',intervalo_min:60,dias_semana:[1,2,3,4,5],saldo_inicial:0,inicio:hojeISO(),exigir_local:false,ativo:true};
 modal(id?'Editar pessoa':'Nova pessoa',`<div class="grid two" style="gap:10px"><div><label for="pfN">Nome completo *</label><input id="pfN" value="${esc(c.nome)}"></div><div><label for="pfC">Cargo</label><input id="pfC" value="${esc(c.cargo||'')}"></div>
  <div><label for="pfE">Entrada</label><input id="pfE" type="time" value="${hm(c.entrada)}"></div><div><label for="pfS">Saída</label><input id="pfS" type="time" value="${hm(c.saida)}"></div>
  <div><label for="pfI">Intervalo (minutos)</label><input id="pfI" type="number" min="0" max="240" value="${c.intervalo_min}"></div><div><label>Jornada por dia</label><input id="pfJ" disabled value=""></div>
  <div><label for="pfSI">Saldo inicial do banco (±HH:MM)</label><input id="pfSI" value="${c.saldo_inicial?sin(c.saldo_inicial).replace('−','-'):'00:00'}"></div><div><label for="pfD">Início do controle</label><input id="pfD" type="date" value="${c.inicio||''}"></div></div>
  <label style="margin-top:10px">Dias de trabalho</label><div class="row wrap" style="gap:10px">${[1,2,3,4,5,6,0].map(d=>`<label class="check-l"><input type="checkbox" class="check" data-pf-d="${d}" ${(c.dias_semana||[]).includes(d)?'checked':''}> ${SEM[d]}</label>`).join('')}</div>
  <label class="check-l" style="margin-top:10px"><input type="checkbox" class="check" id="pfL" ${c.exigir_local?'checked':''}> Exigir localização do celular na marcação</label>
  <label class="check-l"><input type="checkbox" class="check" id="pfA" ${c.ativo?'checked':''}> Ativa (pode registrar ponto)</label>
  <div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-pt-salvapessoa="${id||''}">Salvar</button></div>`);
 const j=()=>{const e=$('#pfE').value,s=$('#pfS').value,i=Number($('#pfI').value)||0;$('#pfJ').value=e&&s?dur(Math.max(0,mMin(s)-mMin(e)-i)):''};['#pfE','#pfS','#pfI'].forEach(s=>$(s).oninput=j);j()}
async function salvarPessoa(id){const nome=$('#pfN').value.trim();if(nome.length<3)return toast('Informe o nome.');const e=$('#pfE').value,s=$('#pfS').value,i=Number($('#pfI').value)||0,jm=mMin(s)-mMin(e)-i;if(!(jm>0))return toast('Confira entrada, saída e intervalo.');
 const si=($('#pfSI').value||'0').trim(),sm=/^[-+−]?\d{1,3}:\d{2}$/.test(si)?(si.startsWith('-')||si.startsWith('−')?-1:1)*mMin(si.replace(/^[-+−]/,'').padStart(5,'0')):0;
 const row={nome,cargo:$('#pfC').value.trim()||null,entrada:e,saida:s,intervalo_min:i,jornada_min:jm,dias_semana:[...document.querySelectorAll('[data-pf-d]')].filter(x=>x.checked).map(x=>+x.dataset.pfD),saldo_inicial:sm,inicio:$('#pfD').value||null,exigir_local:$('#pfL').checked,ativo:$('#pfA').checked,updated_at:new Date().toISOString()};
 const q=id?Cloud.client.from('ponto_colaboradores').update(row).eq('workspace_id',Cloud.ws).eq('id',id):Cloud.client.from('ponto_colaboradores').insert({workspace_id:Cloud.ws,...row});const {error}=await q;if(error)return toast(error.message);
 await auditar(id||null,null,id?'Cadastro alterado':'Pessoa cadastrada',null,{nome,jornada:dur(jm),dias:row.dias_semana},null);closeModal();toast('Salvo.');await carregar(true)}

// ── Link do app (código de uso único, 72 h) ──
const sha=async s=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(b=>b.toString(16).padStart(2,'0')).join('');
async function gerarLink(colab){const A='ABCDEFGHJKMNPQRSTUVWXYZ23456789',r=crypto.getRandomValues(new Uint8Array(10)),cod=[...r].map(b=>A[b%A.length]).join('');
 const {error}=await Cloud.client.from('ponto_dispositivos').insert({workspace_id:Cloud.ws,colaborador_id:colab,codigo_hash:await sha(cod),codigo_expira:new Date(Date.now()+72*3600e3).toISOString()});if(error)return toast(error.message);
 await auditar(colab,null,'Link do app gerado',null,null,null);const c=C(colab),link=location.origin+location.pathname.replace(/[^/]*$/,'')+'ponto.html#ativar='+cod,msg=`Olá, ${c.nome.split(' ')[0]}! Este é o seu acesso ao Jarvis Ponto, para registrar o ponto pelo celular: ${link}\nAbra no celular e toque em "Adicionar à tela inicial". O link vale por 72 horas.`;
 modal('Acesso ao Jarvis Ponto',`<p>Envie este link para <b>${esc(c.nome)}</b> abrir <b>no celular dela</b>. Vale por 72 horas; se for ativado em outro aparelho, o anterior para de registrar.</p><div class="ptqr" id="ptQr"></div><code class="cialinha" style="display:block;word-break:break-all;margin:10px 0">${esc(link)}</code>
  <div class="row wrap" style="gap:8px"><button class="small primary" data-pt-copia="${esc(link)}">Copiar link</button><a class="btnlink small" href="https://wa.me/?text=${encodeURIComponent(msg)}" target="_blank" rel="noopener">Enviar por WhatsApp</a></div><p class="caption" style="margin-top:10px">Código de ativação: <b style="letter-spacing:2px">${cod}</b> (se preferir digitar no app).</p><div class="modalfoot"><button class="primary" data-action="close">Concluir</button></div>`);
 const go=()=>{try{new QRCode($('#ptQr'),{text:link,width:180,height:180})}catch{}};if(window.QRCode)go();else{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js';s.onload=go;document.head.appendChild(s)}
 carregar(true)}

// ── Arquivos ──
async function enviar(files){const ws=Cloud.ws;let ok=0;for(const f of files){const nm=f.name.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,''),m=nm.match(/(\d{4})-(\d{2})[-_ ]+([a-z]+)/);let colab=st.colab,comp=st.mes;
  if(m){comp=`${m[1]}-${m[2]}`;const p=st.colabs.find(c=>c.nome.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').split(/\s+/).includes(m[3]));if(p)colab=p.id}
  if(!colab)continue;const caminho=`${ws}/${colab}/${comp}/${Date.now()}-${nm.replace(/[^a-z0-9.\-]+/g,'-')}`;
  const up=await Cloud.client.storage.from('ponto').upload(caminho,f,{contentType:f.type||undefined});if(up.error){toast(f.name+': '+up.error.message);continue}
  const {error}=await Cloud.client.from('ponto_anexos').insert({workspace_id:ws,colaborador_id:colab,competencia:comp,caminho,nome:f.name,tipo:f.type,tamanho:f.size});if(!error)ok++}
 toast(`${ok} arquivo(s) enviado(s).`);await carregar(true)}
async function url(caminho){const {data}=await Cloud.client.storage.from('ponto').createSignedUrl(caminho,3600);return data?.signedUrl}
async function miniaturas(){for(const i of document.querySelectorAll('[data-pt-img]')){if(i.src)continue;const u=await url(i.dataset.ptImg);if(u)i.src=u}}

// ── Relatórios ──
function csv(){const linhas=[['colaborador','data','dia_semana','classificacao','m1','m2','m3','m4','m5','m6','trabalhadas','previstas','diferenca_min','conferido','observacao']];
 for(const c of st.colabs)for(const l of linhasMes(c,st.mes)){if(!l.conta)continue;const m=[...(l.r?.marcacoes||[]),'','','','','',''].slice(0,6);linhas.push([c.nome,l.data,SEM[l.wd],l.r?TIPO[l.r.tipo]:'sem registro',...m,l.trab!=null?dur(l.trab):'',l.previsto?dur(c.jornada_min):'',l.delta??'',l.r?.conferido?'sim':'não',l.r?.observacao||''])}
 const txt='﻿'+linhas.map(r=>r.map(v=>{const s=String(v??'');return /[;"\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}).join(';')).join('\n');baixar(new Blob([txt],{type:'text/csv;charset=utf-8'}),`ponto-${st.mes}.csv`)}
function baixar(blob,nome){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=nome;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1500)}
const carregaLib=(g,src)=>window[g]?Promise.resolve():new Promise((ok,er)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=()=>er(Error('Não foi possível carregar '+g));document.head.appendChild(s)});
async function pdfDe(c){await carregaLib('jspdf','https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js');const {jsPDF}=window.jspdf,pdf=new jsPDF({unit:'pt',format:'a4',compress:true}),W=595.28,H=841.89,M=36,ev=evolucao(c,st.mes),sel=ev.find(e=>e.mes===st.mes)||{...resumo(c,st.mes),ac:banco(c,st.mes)},ant=sel.ac-sel.saldo;
 const t=s=>String(s).normalize('NFD').replace(/[̀-ͯ]/g,''),S=m=>`${m<0?'-':'+'}${dur(m)}`;
 pdf.setFillColor(11,22,34);pdf.rect(0,0,W,80,'F');pdf.setTextColor(95,224,204);pdf.setFont('helvetica','bold');pdf.setFontSize(10);pdf.text('JARVIS · BANCO DE HORAS',M,28);pdf.setTextColor(255,255,255);pdf.setFontSize(16);pdf.text(t(c.nome),M,52);pdf.setFont('helvetica','normal');pdf.setFontSize(10);pdf.text(t(`${window.Cloud?.wsName||''} · Fechamento: ${mesLabel(st.mes)}`),W-M,52,{align:'right'});
 pdf.setTextColor(26,50,68);pdf.setFontSize(9.5);pdf.text(t(`Jornada: ${hm(c.entrada)}-${hm(c.saida)}, intervalo ${c.intervalo_min} min = ${dur(c.jornada_min)}/dia (${(c.dias_semana||[]).map(d=>SEM[d]).join(', ')}). Dia previsto sem registro: -${dur(c.jornada_min)}. Fora dos dias previstos: credito simples.`),M,102,{maxWidth:W-2*M});
 let y=132;pdf.setFont('helvetica','bold');pdf.setFontSize(12);pdf.text(t('Evolucao dos ultimos 6 meses'),M,y);y+=16;const X=[M,245,314,383,454,559];pdf.setFillColor(232,242,245);pdf.rect(M,y-10,W-2*M,20,'F');pdf.setFontSize(9);pdf.text('Competencia',X[0]+5,y+4);['Creditos','Debitos','Saldo','Acumulado'].forEach((h,i)=>pdf.text(h,X[i+1],y+4,{align:'right'}));y+=24;
 for(const e of ev.slice(-6)){pdf.setFont('helvetica',e.mes===st.mes?'bold':'normal');pdf.setTextColor(30,60,78);pdf.text(t(mesLabel(e.mes)),X[0]+5,y);[S(e.cr),S(e.db),S(e.saldo),S(e.ac)].forEach((v,i)=>pdf.text(v,X[i+1],y,{align:'right'}));pdf.setDrawColor(224,231,235);pdf.line(M,y+6,W-M,y+6);y+=22}
 y+=12;pdf.setFont('helvetica','bold');pdf.setFontSize(12);pdf.text(t(`Composicao de ${mesLabel(st.mes)}`),M,y);y+=16;pdf.setFillColor(232,242,245);pdf.rect(M,y-10,W-2*M,20,'F');pdf.setFontSize(9);pdf.text('Dia',M+4,y+4);pdf.text('Marcacoes / origem',70,y+4);pdf.text('Trabalhadas',360,y+4,{align:'right'});pdf.text('Previstas',440,y+4,{align:'right'});pdf.text('Variacao',W-M-4,y+4,{align:'right'});y+=22;
 const L=linhasMes(c,st.mes).filter(l=>l.conta&&l.delta);for(const a of st.aj.filter(a=>a.colaborador_id===c.id&&a.competencia===st.mes))L.push({ajuste:a});const max=Math.floor((H-140-y)/13);
 for(const l of L.slice(0,max)){pdf.setFont('helvetica','normal');pdf.setFontSize(8.5);pdf.setTextColor(43,66,81);let o,dl;if(l.ajuste){pdf.text('-',M+4,y);o=`Ajuste: ${l.ajuste.motivo}`;dl=l.ajuste.minutos;pdf.text('-',360,y,{align:'right'});pdf.text('-',440,y,{align:'right'})}else{pdf.text(`${pad(l.d)} ${SEM[l.wd]}`,M+4,y);o=l.r?(l.r.tipo!=='trabalho'?TIPO[l.r.tipo]:(l.r.marcacoes||[]).filter(Boolean).join(' ')):'Sem registro';if(l.r?.observacao)o+=' - '+l.r.observacao;dl=l.delta;pdf.text(l.trab!=null?dur(l.trab):'-',360,y,{align:'right'});pdf.text(l.previsto?dur(c.jornada_min):'00:00',440,y,{align:'right'})}
  o=t(o);pdf.text(o.length>52?o.slice(0,49)+'...':o,70,y);pdf.setTextColor(dl<0?170:14,dl<0?60:119,dl<0?50:105);pdf.text(S(dl),W-M-4,y,{align:'right'});y+=13}
 pdf.setDrawColor(195,213,222);pdf.line(M,H-108,W-M,H-108);pdf.setFont('helvetica','bold');pdf.setFontSize(10);pdf.setTextColor(21,48,68);pdf.text(t(`Creditos ${S(sel.cr)}  +  debitos ${S(sel.db)}  =  saldo do mes ${S(sel.saldo)}`),M,H-90);
 pdf.setFillColor(232,242,245);pdf.rect(M,H-80,W-2*M,34,'F');pdf.setFontSize(10);pdf.text(`Saldo anterior: ${S(ant)}`,M+9,H-59);pdf.setFontSize(12);pdf.text(`Saldo acumulado do banco: ${S(sel.ac)}`,W-M-9,H-59,{align:'right'});
 pdf.setFont('helvetica','normal');pdf.setFontSize(8);pdf.setTextColor(94,111,123);pdf.text(t(`${sel.pend||0} dia(s) a conferir. Gerado pelo Jarvis em ${new Date().toLocaleString('pt-BR')}.${L.length>max?` ${L.length-max} lancamento(s) a mais no portal.`:''}`),M,H-26);
 pdf.text(t('Assinatura do colaborador: ______________________________        Assinatura da empresa: ______________________________'),M,H-12);
 return {bytes:pdf.output('arraybuffer'),nome:`banco-de-horas-${t(c.nome).toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${st.mes}.pdf`}}

// ── Eventos ──
document.addEventListener('click',async e=>{const b=e.target.closest('[data-pt],[data-pt-aba],[data-pt-dia],[data-pt-link],[data-pt-edita],[data-pt-salvapessoa],[data-pt-salvadia],[data-pt-revoga],[data-pt-copia],[data-pt-rmaj],[data-pt-soldia],[data-pt-solok],[data-pt-solno],[data-pt-solresp],[data-pt-ver],[data-pt-rmanx]');if(!b)return;const d=b.dataset;
 if(d.ptAba){e.preventDefault();st.aba=d.ptAba;render();return}
 if(d.ptDia){if(b.classList.contains('ptoff'))return;editarDia(d.ptDia);return}
 if(d.ptLink){e.preventDefault();gerarLink(d.ptLink);return}
 if(d.ptEdita){editarPessoa(d.ptEdita);return}
 if(d.ptSalvapessoa!==undefined){salvarPessoa(d.ptSalvapessoa||null);return}
 if(d.ptSalvadia){salvarDia(d.ptSalvadia,d.sol||null);return}
 if(d.ptCopia){navigator.clipboard?.writeText(d.ptCopia).then(()=>toast('Link copiado.'),()=>toast('Selecione e copie o link.'));return}
 if(d.ptRevoga){modal('Revogar aparelho',`<p>Este celular deixa de registrar ponto na hora. Para voltar, gere um novo link.</p><div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-pt="revogar" data-id="${d.ptRevoga}">Revogar</button></div>`);return}
 if(d.ptRmaj){modal('Excluir ajuste',`<p>O lançamento sai do saldo e fica registrado na auditoria.</p><div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-pt="rmaj" data-id="${d.ptRmaj}">Excluir</button></div>`);return}
 if(d.ptRmanx){modal('Excluir arquivo',`<p>O arquivo é apagado do armazenamento.</p><div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-pt="rmanx" data-id="${d.ptRmanx}">Excluir</button></div>`);return}
 if(d.ptVer){const a=st.anexos.find(x=>x.id===d.ptVer);const u=a&&await url(a.caminho);if(u)window.open(u,'_blank','noopener');return}
 if(d.ptSoldia){const s=st.sol.find(x=>x.id===d.ptSoldia);if(!s)return;st.colab=s.colaborador_id;st.mes=s.data.slice(0,7);editarDia(s.data,s.id);return}
 if(d.ptSolok||d.ptSolno){const id=d.ptSolok||d.ptSolno,ok=!!d.ptSolok;modal(ok?'Aprovar pedido':'Recusar pedido',`<label for="ptResp">Resposta para a pessoa (aparece no app)</label><textarea id="ptResp" rows="3">${ok?'Pedido aprovado.':''}</textarea><div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-pt-solresp="${id}" data-ok="${ok?1:0}">${ok?'Aprovar':'Recusar'}</button></div>`);return}
 if(d.ptSolresp){const ok=d.ok==='1',resp=$('#ptResp').value.trim();if(!ok&&resp.length<3)return toast('Explique o motivo da recusa.');const {error}=await Cloud.client.from('ponto_solicitacoes').update({status:ok?'aprovada':'recusada',resposta:resp||null,resolvido_em:new Date().toISOString(),resolvido_por:quem()}).eq('workspace_id',Cloud.ws).eq('id',d.ptSolresp);if(error)return toast(error.message);closeModal();await carregar(true);return}
 switch(d.pt){
  case 'nova':editarPessoa(null);break;
  case 'revogar':{const {error}=await Cloud.client.from('ponto_dispositivos').update({revogado:true}).eq('workspace_id',Cloud.ws).eq('id',d.id);if(error)return toast(error.message);const x=st.disp.find(y=>y.id===d.id);await auditar(x?.colaborador_id,null,'Aparelho revogado',{aparelho:x?.aparelho},null,null);closeModal();toast('Aparelho revogado.');await carregar(true);break}
  case 'rmaj':{const a=st.aj.find(x=>x.id===d.id);const {error}=await Cloud.client.from('ponto_ajustes').delete().eq('workspace_id',Cloud.ws).eq('id',d.id);if(error)return toast(error.message);await auditar(a?.colaborador_id,null,'Ajuste excluído',{minutos:a?.minutos,motivo:a?.motivo},null,null);closeModal();await carregar(true);break}
  case 'rmanx':{const a=st.anexos.find(x=>x.id===d.id);if(!a)return;await Cloud.client.storage.from('ponto').remove([a.caminho]);await Cloud.client.from('ponto_anexos').delete().eq('workspace_id',Cloud.ws).eq('id',a.id);closeModal();await carregar(true);break}
  case 'ajuste':{const c=C(st.colab),v=$('#ptAjM').value.trim().replace(/^[-+−]/,''),mot=$('#ptAjMot').value.trim();if(!/^\d{1,3}:\d{2}$/.test(v))return toast('Informe as horas como HH:MM.');if(mot.length<5)return toast('Descreva o motivo.');
   const sinal=/^[-−]/.test($('#ptAjM').value.trim())?-1:Number($('#ptAjS').value),minutos=sinal*mMin(v.padStart(5,'0'));const {error}=await Cloud.client.from('ponto_ajustes').insert({workspace_id:Cloud.ws,colaborador_id:c.id,competencia:st.mes,tipo:$('#ptAjT').value,minutos,motivo:mot,criado_por:quem()});if(error)return toast(error.message);
   await auditar(c.id,null,'Ajuste lançado',null,{minutos,tipo:$('#ptAjT').value},mot);toast('Lançamento registrado.');await carregar(true);break}
  case 'conferirmes':{const c=C(st.colab),alvo=linhasMes(c,st.mes).filter(l=>l.r&&!l.r.conferido&&(l.sit==='conferir'||l.sit==='classif'));if(!alvo.length)return toast('Nenhum dia completo aguardando conferência.');
   for(const l of alvo)await Cloud.client.from('ponto_dias').update({conferido:true,updated_at:new Date().toISOString()}).eq('workspace_id',Cloud.ws).eq('colaborador_id',c.id).eq('data',l.data);
   await auditar(c.id,null,`${alvo.length} dia(s) conferidos`,null,{competencia:st.mes},null);toast(`${alvo.length} dia(s) conferidos. Incompletos e sem registro continuam para revisão.`);await carregar(true);break}
  case 'csv':csv();break;
  case 'pdf':{try{const c=C(st.colab),r=await pdfDe(c);baixar(new Blob([r.bytes],{type:'application/pdf'}),r.nome)}catch(x){toast(x.message)}break}
  case 'zip':{try{await carregaLib('JSZip','https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js');const z=new JSZip();for(const c of st.colabs.filter(x=>x.ativo)){const r=await pdfDe(c);z.file(r.nome,r.bytes)}baixar(await z.generateAsync({type:'blob'}),`banco-de-horas-${st.mes}.zip`)}catch(x){toast(x.message)}break}
 }});
document.addEventListener('change',e=>{const s=e.target.closest('[data-pt-sel]');if(s){if(s.dataset.ptSel==='colab')st.colab=s.value;else if(/^\d{4}-\d{2}$/.test(s.value))st.mes=s.value;render();return}
 if(e.target.id==='ptArq'&&e.target.files.length)enviar([...e.target.files])});
function bind(){const z=$('.ptdrop');if(z){z.ondragover=e=>{e.preventDefault();z.classList.add('on')};z.ondragleave=()=>z.classList.remove('on');z.ondrop=e=>{e.preventDefault();z.classList.remove('on');if(e.dataTransfer.files.length)enviar([...e.dataTransfer.files])}}
 miniaturas();clearInterval(st.timer);st.timer=setInterval(()=>{if(page!=='ponto'){clearInterval(st.timer);return}if(st.aba==='agora'&&!document.querySelector('.modalback'))carregar(true)},60e3)}
window.Ponto={acesso:null,garantir:()=>{checarAcesso();return carregar()},recarregar:()=>carregar(true),estado:()=>st,linhasMes,resumo,evolucao,trabalhado,curto,SEM,avisos:()=>{if(!st.acesso||!st.ok)return [];const n=st.sol.filter(s=>s.status==='pendente').length;return n?[['warn','clock',`${n} pedido(s) de ajuste de ponto`,'Colaboradores pediram correção pelo app','ponto']]:[]}};
addPage('ponto','clock','Ponto e jornada',view,'Ponto dos colaboradores pelo app Jarvis Ponto: marcações, espelho, banco de horas, pedidos de ajuste e relatórios. Só quem criou a empresa acessa.','',bind);
const tenta=()=>{if(window.Cloud?.ws&&Cloud.session)checarAcesso();else setTimeout(tenta,1500)};setTimeout(tenta,1200);
})();
