'use strict';
// Rentabilidade por item até o lucro líquido. Pedido a pedido (receita, tarifas, frete e custo de cada item) e, do mês,
// a DRE gerencial (Gestao.dreMes): tributos e devoluções, demais despesas comerciais, pessoal, administrativas, outras,
// depreciação, resultado financeiro e IRPJ/CSLL, rateados entre os itens. Assim a soma dos itens fecha com a DRE.
(()=>{
Object.assign(paths,{piramide:'M3 20h18 M6 16h12 M9 12h6 M11 8h2 M12 4v4'});
const ui={mes:null,grupo:'produto',base:'receita',fonte:'dre',canal:'',busca:'',ordem:'ll',dir:-1};
const r2=v=>Math.round((Number(v)||0)*100)/100,pct=(v,b)=>b?`${(v/b*100).toFixed(1).replace('.',',')}%`:'—',R=v=>money(r2(v));
const mesesComVenda=()=>[...new Set(db.orders.map(o=>o.date.slice(0,7)))].sort().reverse();
const mesPadrao=()=>{const ms=mesesComVenda(),atual=new Date().toISOString().slice(0,7);return ms.find(m=>m<atual)||ms[0]||atual};
const mesLabel=m=>new Date(m+'-15T12:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'});
const BASES={receita:'Receita bruta',unidades:'Unidades vendidas',mc:'Margem de contribuição'};
function dreDoMes(m){const G=window.Gestao;if(!G?.dreMes)return null;const d=G.dreMes(m,'gerencial');if(d?.fonte)return {d,ref:m,estimada:false};
 // Sem balancete do mês: usa o último mês fechado pela contabilidade (despesas fixas costumam se repetir).
 for(const x of [...new Set((db.accLines||[]).map(l=>l.month))].sort().reverse()){if(x>=m)continue;const e=G.dreMes(x,'gerencial');if(e?.fonte)return {d:e,ref:x,estimada:true}}
 return null}
function custos(){const c=new Map((db.products||[]).map(p=>[String(p.id).trim(),{c:Number(p.custo)||0,e:Number(p.embalagem)||0}]));for(const p of window.Estoque?.lista?.()||[])if(Number(p.custo))c.set(String(p.id).trim(),{c:Number(p.custo),e:c.get(String(p.id).trim())?.e||0});return c}
function calcular(){const m=ui.mes,C=custos(),linhas=new Map(),dre=dreDoMes(m);let receitaTot=0,unTot=0,semCusto=0;
 for(const o of db.orders){if(!o.date.startsWith(m)||(ui.canal&&o.platform!==ui.canal))continue;if(o.gross>0&&o.fee>=o.gross*0.95)continue;
  const its=o.items||[],tot=its.reduce((a,i)=>a+(Number(i.qty)||0)*(Number(i.price)||0),0)||1,frete=o.shipping&&/API/.test(o.source||'')&&!/Bling/.test(o.source||'')&&o.feeSource!=='Shopee'?Number(o.shipping):0; // taxa da Shopee (venda − repasse) já inclui o frete do vendedor
  for(const i of its){const q=Number(i.qty)||0,share=(q*(Number(i.price)||0))/tot,sku=String(i.sku||i.title||'?').trim(),k=ui.grupo==='canal'?o.platform:sku,c=C.get(sku);
   const x=linhas.get(k)||{k,nome:ui.grupo==='canal'?o.platform:(i.title||sku),sku:ui.grupo==='canal'?'':sku,un:0,rb:0,cmv:0,tar:0,fre:0,semCusto:false,pedidos:new Set()};
   x.un+=q;x.rb+=o.gross*share;x.tar+=(Number(o.fee)||0)*share;x.fre+=frete*share;if(c)x.cmv+=q*(c.c+c.e);else{x.semCusto=true;semCusto++}x.pedidos.add(o.id);linhas.set(k,x)}
  receitaTot+=o.gross}
 const L=[...linhas.values()];for(const x of L)unTot+=x.un;
 // Totais do mês na DRE (despesas vêm negativas). As tarifas e o frete já estão por pedido; o resto das comerciais é rateado.
 const v=dre?.d.v||{},rbDre=v.receita||0,esc=dre&&rbDre?Math.min(1,receitaTot/rbDre):1;
 // Comerciais da DRE já contêm as tarifas e o frete dos marketplaces: só o que sobra (marketing, embalagem avulsa etc.) é rateado.
 const porPedido=L.reduce((a,x)=>a+x.tar+x.fre,0);
 // Base 'contabilidade': CMV e comerciais de cada item ajustados na proporção dos totais da DRE, para a soma fechar com o lucro contábil.
 const fCMV=ui.fonte==='dre'&&dre&&L.reduce((a,x)=>a+x.cmv,0)?Math.abs(v.cmv||0)*esc/L.reduce((a,x)=>a+x.cmv,0):1,fCom=ui.fonte==='dre'&&dre&&porPedido?Math.abs(v.comerciais||0)*esc/porPedido:1;
 if(ui.fonte==='dre'&&dre)for(const x of L){x.cmv*=fCMV;x.tar*=fCom;x.fre*=fCom}
 const T={deducoes:-((v.devolucoes||0)+(v.impostos||0))*esc,outrasCom:ui.fonte==='dre'&&porPedido?0:Math.max(0,-(v.comerciais||0)*esc-porPedido),
  fixas:-((v.trabalhistas||0)+(v.administrativas||0)+(v.outras||0)+(v.depreciacao||0))*esc,fin:((v.rec_fin||0)+(v.desp_fin||0))*esc,ir:-(v.ir||0)*esc};
 const aliqDed=rbDre?-((v.devolucoes||0)+(v.impostos||0))/rbDre:0;
 for(const x of L){x.ded=dre?x.rb*aliqDed:0;x.rl=x.rb-x.ded;x.lb=x.rl-x.cmv;x.outrasCom=receitaTot?T.outrasCom*x.rb/receitaTot:0;x.var=x.tar+x.fre+x.outrasCom;x.mc=x.lb-x.var}
 const baseTot=ui.base==='unidades'?unTot:ui.base==='mc'?L.reduce((a,x)=>a+Math.max(0,x.mc),0):receitaTot;
 for(const x of L){const b=ui.base==='unidades'?x.un:ui.base==='mc'?Math.max(0,x.mc):x.rb,p=baseTot?b/baseTot:0;x.fixas=T.fixas*p;x.op=x.mc-x.fixas;x.fin=receitaTot?T.fin*x.rb/receitaTot:0;x.ir=receitaTot?T.ir*x.rb/receitaTot:0;x.ll=x.op+x.fin-x.ir;x.np=x.pedidos.size}
 const S=k=>L.reduce((a,x)=>a+x[k],0);
 return {fCMV,fCom,L,dre,T,tot:{un:unTot,rb:S('rb'),ded:S('ded'),rl:S('rl'),cmv:S('cmv'),lb:S('lb'),tar:S('tar'),fre:S('fre'),outrasCom:S('outrasCom'),var:S('var'),mc:S('mc'),fixas:S('fixas'),op:S('op'),fin:S('fin'),ir:S('ir'),ll:S('ll')},semCusto}}
const cor=v=>v>0?'green':v<0?'red':'';
function cascata(x){const passos=[['Receita bruta',x.rb,'t'],['(−) Tributos e devoluções',-x.ded],['Receita líquida',x.rl,'t'],['(−) Custo do produto (CMV)',-x.cmv],['Lucro bruto',x.lb,'t'],['(−) Tarifas do marketplace',-x.tar],['(−) Frete',-x.fre],['(−) Marketing e demais comerciais',-x.outrasCom],['Margem de contribuição',x.mc,'t'],['(−) Despesas fixas rateadas',-x.fixas],['Resultado operacional',x.op,'t'],['(±) Resultado financeiro',x.fin],['(−) IRPJ e CSLL',-x.ir],['Lucro líquido',x.ll,'t']];
 const max=Math.max(1,...passos.map(p=>Math.abs(p[1])));
 return `<div class="rtcasc">${passos.map(([t,v,tot])=>`<div class="rtpasso ${tot?'tot':''}"><span>${t}</span><i><b class="${v<0?'neg':''}" style="width:${(Math.abs(v)/max*100).toFixed(1)}%"></b></i><em class="${tot?cor(v):''}">${R(v)}</em><small>${pct(v,x.rb)}</small></div>`).join('')}</div>`}
function view(){if(!ui.mes)ui.mes=mesPadrao();const {L,dre,tot,semCusto,fCMV,fCom}=calcular(),q=ui.busca.toLowerCase();
 const lista=L.filter(x=>!q||x.nome.toLowerCase().includes(q)||x.sku.toLowerCase().includes(q)).sort((a,b)=>ui.ordem==='nome'?a.nome.localeCompare(b.nome)*ui.dir:(a[ui.ordem]-b[ui.ordem])*ui.dir);
 const prej=L.filter(x=>x.ll<0&&!x.semCusto),k=(t,v,s,c='')=>`<div class="card kpi"><span class="kpil">${t}</span><span class="kpiv ${c}">${v}</span><span class="kpis">${s}</span></div>`;
 const th=(c,t,num=true)=>`<th class="${num?'num':''} rtsort ${ui.ordem===c?'on':''}" data-rt-ord="${c}">${t}${ui.ordem===c?(ui.dir<0?' ↓':' ↑'):''}</th>`;
 const canais=[...new Set(db.orders.map(o=>o.platform))].sort();
 return `<div class="row wrap rtfiltros"><label class="caption">Mês <input type="month" value="${ui.mes}" data-rt="mes"></label><label class="caption">Ver por <select data-rt="grupo"><option value="produto" ${ui.grupo==='produto'?'selected':''}>Produto</option><option value="canal" ${ui.grupo==='canal'?'selected':''}>Canal</option></select></label>
  <label class="caption">Canal <select data-rt="canal"><option value="">Todos</option>${canais.map(c=>`<option ${ui.canal===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label class="caption">Custos e tarifas <select data-rt="fonte"><option value="dre" ${ui.fonte==='dre'?'selected':''}>Contabilidade (fecha com a DRE)</option><option value="op" ${ui.fonte==='op'?'selected':''}>Operação (valores dos pedidos)</option></select></label><label class="caption">Rateio das fixas <select data-rt="base">${Object.entries(BASES).map(([v,t])=>`<option value="${v}" ${ui.base===v?'selected':''}>${t}</option>`).join('')}</select></label>${ui.grupo==='produto'?`<input type="search" placeholder="Buscar produto ou SKU" value="${esc(ui.busca)}" data-rt="busca" style="max-width:240px">`:''}</div>
 ${dre?(dre.estimada?`<div class="notice">Sem balancete de ${mesLabel(ui.mes)}: tributos e despesas vêm da DRE de <b>${mesLabel(dre.ref)}</b> (último mês fechado pela contabilidade), na proporção da receita. Quando o balancete do mês chegar, os números se ajustam sozinhos.</div>`:''):`<div class="notice">Sem DRE contábil disponível: mostrando até a margem de contribuição. Importe o balancete em Resultado › Contábil para ratear as despesas.</div>`}
 <div class="grid kpis4">${k('Receita bruta',R(tot.rb),`${Math.round(tot.un).toLocaleString('pt-BR')} unidades · ${mesLabel(ui.mes)}`)}${k('Margem de contribuição',R(tot.mc),pct(tot.mc,tot.rb)+' da receita',cor(tot.mc))}${k('Despesas fixas rateadas',R(tot.fixas),`por ${BASES[ui.base].toLowerCase()}`)}${k('Lucro líquido',R(tot.ll),`${pct(tot.ll,tot.rb)} · ${prej.length} item(ns) no prejuízo`,cor(tot.ll))}</div>
 <div class="grid two"><section class="card"><h3>Do faturamento ao lucro líquido</h3>${cascata(tot)}</section>
  <section class="card"><h3>Como ler</h3><p class="caption"><b>Por item:</b> receita, tarifa do marketplace, frete e custo (tabela de preços/Bling + embalagem) saem de cada pedido. <b>Do mês (DRE gerencial):</b> tributos e devoluções pela alíquota efetiva; marketing e demais despesas comerciais pela receita; pessoal, administrativas, outras e depreciação pela base escolhida; resultado financeiro e IRPJ/CSLL pela receita (no lucro presumido o imposto nasce da receita).</p>
  ${semCusto?`<p class="notice" style="margin:8px 0 0">${semCusto} linha(s) de item sem custo cadastrado: aparecem com o selo "sem custo" e lucro superestimado. Cadastre o custo em Preços.</p>`:''}
  ${dre?`<div class="rtconf"><div><small>Lucro líquido da DRE</small><b>${R(dre.d.v['=ll']||0)}</b></div><div><small>Soma dos itens</small><b class="${cor(tot.ll)}">${R(tot.ll)}</b></div><div><small>Diferença</small><b>${R(tot.ll-(dre.d.v['=ll']||0))}</b></div></div><p class="caption">${ui.fonte==='dre'?`Base contabilidade: CMV dos itens × ${fCMV.toFixed(3).replace('.',',')} e tarifas/frete × ${fCom.toFixed(3).replace('.',',')} para fechar com o custo e as comerciais lançados. A diferença que sobra vem de receita fora dos pedidos (cancelamentos, devoluções, outra competência).`:'Base operação: custo da tabela e tarifas informadas pelos marketplaces em cada pedido; não fecha com a DRE.'}</p><p class="caption" style="margin-top:8px">DRE usada: ${mesLabel(dre.ref)} · fonte ${esc(dre.d.fonte)}. Soma dos itens: receita ${R(tot.rb)} × DRE ${R(dre.d.v.receita||0)}${Math.abs((dre.d.v.receita||0)-tot.rb)>1?' (a diferença são pedidos cancelados, devolvidos ou de outra competência)':''}.</p>`:''}</section></div>
 <div class="tablebox" style="overflow-x:auto;margin-top:14px"><table class="rttab"><thead><tr>${th('nome',ui.grupo==='canal'?'Canal':'Produto',false)}${th('un','Unid.')}${th('rb','Receita')}${th('cmv','CMV')}${th('var','Variáveis')}${th('mc','Margem contrib.')}${th('fixas','Fixas rateadas')}${th('ll','Lucro líquido')}<th class="num">% líq.</th><th class="num">Líquido/un.</th></tr></thead><tbody>
 ${lista.map(x=>`<tr data-rt-item="${esc(x.k)}"><td><b>${esc(x.nome)}</b>${x.sku?`<br><small class="caption">${esc(x.sku)} · ${x.np} pedido(s)</small>`:''}${x.semCusto?' <span class="badge warn">sem custo</span>':''}</td><td class="num">${Math.round(x.un)}</td><td class="num">${R(x.rb)}</td><td class="num">${R(x.cmv)}</td><td class="num">${R(x.var)}</td><td class="num ${cor(x.mc)}">${R(x.mc)} <small class="caption">${pct(x.mc,x.rb)}</small></td><td class="num">${R(x.fixas)}</td><td class="num ${cor(x.ll)}"><b>${R(x.ll)}</b></td><td class="num ${cor(x.ll)}">${pct(x.ll,x.rb)}</td><td class="num">${x.un?R(x.ll/x.un):'—'}</td></tr>`).join('')}
 </tbody></table></div><div class="row" style="margin-top:10px;gap:8px"><button class="small" data-rt="csv">${icon('download')} CSV</button><span class="caption">Clique num item para ver a cascata completa até o lucro líquido.</span></div>`}
document.addEventListener('click',e=>{const t=e.target.closest('[data-rt-ord]');if(t){const c=t.dataset.rtOrd;if(ui.ordem===c)ui.dir*=-1;else{ui.ordem=c;ui.dir=c==='nome'?1:-1}render();return}
 const r=e.target.closest('[data-rt-item]');if(r){const {L}=calcular(),x=L.find(y=>y.k===r.dataset.rtItem);if(!x)return;modal(`${esc(x.nome)}${x.sku?' · '+esc(x.sku):''}`,`<p class="caption">${mesLabel(ui.mes)} · ${Math.round(x.un)} unidade(s) · ${x.np} pedido(s)${x.semCusto?' · <span class="badge warn">sem custo cadastrado</span>':''}</p>${cascata(x)}<p class="caption" style="margin-top:10px">Por unidade: receita ${x.un?R(x.rb/x.un):'—'} · margem de contribuição ${x.un?R(x.mc/x.un):'—'} · lucro líquido ${x.un?R(x.ll/x.un):'—'}.</p><div class="modalfoot"><button class="primary" data-action="close">Fechar</button></div>`);return}
 const b=e.target.closest('[data-rt="csv"]');if(b){const {L}=calcular(),cols=[['nome','item'],['sku','sku'],['un','unidades'],['rb','receita_bruta'],['ded','tributos_devolucoes'],['rl','receita_liquida'],['cmv','cmv'],['lb','lucro_bruto'],['tar','tarifas'],['fre','frete'],['outrasCom','marketing_outras_comerciais'],['mc','margem_contribuicao'],['fixas','fixas_rateadas'],['op','resultado_operacional'],['fin','resultado_financeiro'],['ir','irpj_csll'],['ll','lucro_liquido']];
  const txt='﻿'+[cols.map(c=>c[1]).join(';'),...L.map(x=>cols.map(([c])=>typeof x[c]==='number'?String(r2(x[c])).replace('.',','):`"${String(x[c]??'').replace(/"/g,'""')}"`).join(';'))].join('\n');
  const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type:'text/csv;charset=utf-8'}));a.download=`rentabilidade-${ui.mes}.csv`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1500)}});
document.addEventListener('change',e=>{const s=e.target.closest('[data-rt]');if(!s||s.dataset.rt==='csv')return;const k=s.dataset.rt;if(k==='mes'&&!/^\d{4}-\d{2}$/.test(s.value))return;ui[k]=s.value;render()});
document.addEventListener('input',e=>{const s=e.target.closest('[data-rt="busca"]');if(!s)return;ui.busca=s.value;const pos=s.selectionStart;render();const n=document.querySelector('[data-rt="busca"]');if(n){n.focus();n.setSelectionRange(pos,pos)}});
addPage('rentabilidade','piramide','Rentabilidade por item',view,'Do faturamento ao lucro líquido de cada produto: custo, tarifas, frete, margem de contribuição e despesas fixas rateadas, fechando com a DRE do mês.','',()=>{});
window.Rentabilidade={calcular:()=>calcular()};
})();
